import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { ZoneOffset as java_time_ZoneOffset } from "./../ZoneOffset";
import { LocalDateTime as java_time_LocalDateTime } from "./../LocalDateTime";
import { Instant as java_time_Instant } from "./../Instant";
import { Duration as java_time_Duration } from "./../Duration";
import { Long as java_lang_Long } from "./../../lang/Long";
import { Integer as java_lang_Integer } from "./../../lang/Integer";
import { Class as java_lang_Class } from "./../../lang/Class";

/**
 * This class just defines types, you should import ZoneOffsetTransition instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ZoneOffsetTransitionClass extends JavaClass {
    // ================== Method getOffsetAfter ==================
    /**
     * @return original return type: 'java.time.ZoneOffset'
     */
    public getOffsetAfter(): Promise<java_time_ZoneOffset | null>;
    // ================== Method getOffsetAfter ==================
    /**
     * @return original return type: 'java.time.ZoneOffset'
     */
    public getOffsetAfterSync(): java_time_ZoneOffset | null;
    // ================== Method isValidOffset ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'boolean'
     */
    public isValidOffset(var0: java_time_ZoneOffset | null): Promise<boolean>;
    // ================== Method isValidOffset ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'boolean'
     */
    public isValidOffsetSync(var0: java_time_ZoneOffset | null): boolean;
    // ================== Method isGap ==================
    /**
     * @return original return type: 'boolean'
     */
    public isGap(): Promise<boolean>;
    // ================== Method isGap ==================
    /**
     * @return original return type: 'boolean'
     */
    public isGapSync(): boolean;
    // ================== Method isOverlap ==================
    /**
     * @return original return type: 'boolean'
     */
    public isOverlap(): Promise<boolean>;
    // ================== Method isOverlap ==================
    /**
     * @return original return type: 'boolean'
     */
    public isOverlapSync(): boolean;
    // ================== Method getOffsetBefore ==================
    /**
     * @return original return type: 'java.time.ZoneOffset'
     */
    public getOffsetBefore(): Promise<java_time_ZoneOffset | null>;
    // ================== Method getOffsetBefore ==================
    /**
     * @return original return type: 'java.time.ZoneOffset'
     */
    public getOffsetBeforeSync(): java_time_ZoneOffset | null;
    // ================== Method getDateTimeBefore ==================
    /**
     * @return original return type: 'java.time.LocalDateTime'
     */
    public getDateTimeBefore(): Promise<java_time_LocalDateTime | null>;
    // ================== Method getDateTimeBefore ==================
    /**
     * @return original return type: 'java.time.LocalDateTime'
     */
    public getDateTimeBeforeSync(): java_time_LocalDateTime | null;
    // ================== Method getDateTimeAfter ==================
    /**
     * @return original return type: 'java.time.LocalDateTime'
     */
    public getDateTimeAfter(): Promise<java_time_LocalDateTime | null>;
    // ================== Method getDateTimeAfter ==================
    /**
     * @return original return type: 'java.time.LocalDateTime'
     */
    public getDateTimeAfterSync(): java_time_LocalDateTime | null;
    // ================== Method getInstant ==================
    /**
     * @return original return type: 'java.time.Instant'
     */
    public getInstant(): Promise<java_time_Instant | null>;
    // ================== Method getInstant ==================
    /**
     * @return original return type: 'java.time.Instant'
     */
    public getInstantSync(): java_time_Instant | null;
    // ================== Method getDuration ==================
    /**
     * @return original return type: 'java.time.Duration'
     */
    public getDuration(): Promise<java_time_Duration | null>;
    // ================== Method getDuration ==================
    /**
     * @return original return type: 'java.time.Duration'
     */
    public getDurationSync(): java_time_Duration | null;
    // ================== Method toEpochSecond ==================
    /**
     * @return original return type: 'long'
     */
    public toEpochSecond(): Promise<number>;
    // ================== Method toEpochSecond ==================
    /**
     * @return original return type: 'long'
     */
    public toEpochSecondSync(): number;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.time.zone.ZoneOffsetTransition'
     * @return original return type: 'int'
     */
    public compareTo(var0: ZoneOffsetTransitionClass | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.time.zone.ZoneOffsetTransition'
     * @return original return type: 'int'
     */
    public compareToSync(var0: ZoneOffsetTransitionClass | null): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'java.time.LocalDateTime'
     * @param var1 original type: 'java.time.ZoneOffset'
     * @param var2 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.zone.ZoneOffsetTransition'
     */
    public static of(var0: java_time_LocalDateTime | null, var1: java_time_ZoneOffset | null, var2: java_time_ZoneOffset | null): Promise<ZoneOffsetTransition | null>;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'java.time.LocalDateTime'
     * @param var1 original type: 'java.time.ZoneOffset'
     * @param var2 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.zone.ZoneOffsetTransition'
     */
    public static ofSync(var0: java_time_LocalDateTime | null, var1: java_time_ZoneOffset | null, var2: java_time_ZoneOffset | null): ZoneOffsetTransition | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.time.zone.ZoneOffsetTransition.
 *
 * This actually imports the java class for further use.
 * The class ZoneOffsetTransitionClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class ZoneOffsetTransition extends importClass<typeof ZoneOffsetTransitionClass>("java.time.zone.ZoneOffsetTransition") {
}
export default ZoneOffsetTransition;