import { importClass, JavaClass } from "java-bridge";
import { WatchKey as java_nio_file_WatchKey } from "./WatchKey";
import { Long as java_lang_Long } from "./../../lang/Long";
import { TimeUnit as java_util_concurrent_TimeUnit } from "./../../util/concurrent/TimeUnit";

/**
 * This class just defines types, you should import WatchService instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class WatchServiceClass extends JavaClass {
    // ================== Method take ==================
    /**
     * @return original return type: 'java.nio.file.WatchKey'
     */
    public take(): Promise<java_nio_file_WatchKey | null>;
    // ================== Method take ==================
    /**
     * @return original return type: 'java.nio.file.WatchKey'
     */
    public takeSync(): java_nio_file_WatchKey | null;
    // ================== Method poll ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.util.concurrent.TimeUnit'
     * @return original return type: 'java.nio.file.WatchKey'
     */
    public poll(var0: java_lang_Long | bigint | number, var1: java_util_concurrent_TimeUnit | null): Promise<java_nio_file_WatchKey | null>;
    // ================== Method poll ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.util.concurrent.TimeUnit'
     * @return original return type: 'java.nio.file.WatchKey'
     */
    public pollSync(var0: java_lang_Long | bigint | number, var1: java_util_concurrent_TimeUnit | null): java_nio_file_WatchKey | null;
    /**
     * @return original return type: 'java.nio.file.WatchKey'
     */
    public poll(): Promise<java_nio_file_WatchKey | null>;
    /**
     * @return original return type: 'java.nio.file.WatchKey'
     */
    public pollSync(): java_nio_file_WatchKey | null;
    // ================== Method close ==================
    /**
     * @return original return type: 'void'
     */
    public close(): Promise<void>;
    // ================== Method close ==================
    /**
     * @return original return type: 'void'
     */
    public closeSync(): void;
}

/**
 * Class java.nio.file.WatchService.
 *
 * This actually imports the java class for further use.
 * The class WatchServiceClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class WatchService extends importClass<typeof WatchServiceClass>("java.nio.file.WatchService") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default WatchService;