import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Chronology as java_time_chrono_Chronology } from "./Chronology";
import { Instant as java_time_Instant } from "./../Instant";
import { ZoneOffset as java_time_ZoneOffset } from "./../ZoneOffset";
import { TemporalField as java_time_temporal_TemporalField } from "./../temporal/TemporalField";
import { Long as java_lang_Long } from "./../../lang/Long";
import { TemporalAdjuster as java_time_temporal_TemporalAdjuster } from "./../temporal/TemporalAdjuster";
import { Temporal as java_time_temporal_Temporal } from "./../temporal/Temporal";
import { TemporalAmount as java_time_temporal_TemporalAmount } from "./../temporal/TemporalAmount";
import { TemporalUnit as java_time_temporal_TemporalUnit } from "./../temporal/TemporalUnit";
import { ChronoZonedDateTime as java_time_chrono_ChronoZonedDateTime } from "./ChronoZonedDateTime";
import { ZoneId as java_time_ZoneId } from "./../ZoneId";
import { Comparator as java_util_Comparator } from "./../../util/Comparator";
import { ChronoLocalDate as java_time_chrono_ChronoLocalDate } from "./ChronoLocalDate";
import { LocalTime as java_time_LocalTime } from "./../LocalTime";
import { TemporalAccessor as java_time_temporal_TemporalAccessor } from "./../temporal/TemporalAccessor";
import { DateTimeFormatter as java_time_format_DateTimeFormatter } from "./../format/DateTimeFormatter";
import { TemporalQuery as java_time_temporal_TemporalQuery } from "./../temporal/TemporalQuery";
import { ValueRange as java_time_temporal_ValueRange } from "./../temporal/ValueRange";

/**
 * This class just defines types, you should import ChronoLocalDateTime instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ChronoLocalDateTimeClass extends JavaClass {
    // ================== Method getChronology ==================
    /**
     * @return original return type: 'java.time.chrono.Chronology'
     */
    public getChronology(): Promise<java_time_chrono_Chronology | null>;
    // ================== Method getChronology ==================
    /**
     * @return original return type: 'java.time.chrono.Chronology'
     */
    public getChronologySync(): java_time_chrono_Chronology | null;
    // ================== Method toInstant ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.Instant'
     */
    public toInstant(var0: java_time_ZoneOffset | null): Promise<java_time_Instant | null>;
    // ================== Method toInstant ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.Instant'
     */
    public toInstantSync(var0: java_time_ZoneOffset | null): java_time_Instant | null;
    // ================== Method with ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public with(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): Promise<ChronoLocalDateTime | null>;
    // ================== Method with ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public withSync(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public with(var0: java_time_temporal_TemporalAdjuster | null): Promise<ChronoLocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public withSync(var0: java_time_temporal_TemporalAdjuster | null): ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public with(var0: java_time_temporal_TemporalAdjuster | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public withSync(var0: java_time_temporal_TemporalAdjuster | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public with(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public withSync(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): java_time_temporal_Temporal | null;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<ChronoLocalDateTime | null>;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public plus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<ChronoLocalDateTime | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public plusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): java_time_temporal_Temporal | null;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public minus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<ChronoLocalDateTime | null>;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public minusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<ChronoLocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): java_time_temporal_Temporal | null;
    // ================== Method adjustInto ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public adjustInto(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method adjustInto ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public adjustIntoSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method atZone ==================
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.chrono.ChronoZonedDateTime'
     */
    public atZone(var0: java_time_ZoneId | null): Promise<java_time_chrono_ChronoZonedDateTime | null>;
    // ================== Method atZone ==================
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.chrono.ChronoZonedDateTime'
     */
    public atZoneSync(var0: java_time_ZoneId | null): java_time_chrono_ChronoZonedDateTime | null;
    // ================== Method isAfter ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isAfter(var0: ChronoLocalDateTimeClass | null): Promise<boolean>;
    // ================== Method isAfter ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isAfterSync(var0: ChronoLocalDateTimeClass | null): boolean;
    // ================== Method isBefore ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isBefore(var0: ChronoLocalDateTimeClass | null): Promise<boolean>;
    // ================== Method isBefore ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isBeforeSync(var0: ChronoLocalDateTimeClass | null): boolean;
    // ================== Method timeLineOrder ==================
    /**
     * @return original return type: 'java.util.Comparator'
     */
    public static timeLineOrder(): Promise<java_util_Comparator | null>;
    // ================== Method timeLineOrder ==================
    /**
     * @return original return type: 'java.util.Comparator'
     */
    public static timeLineOrderSync(): java_util_Comparator | null;
    // ================== Method toLocalDate ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public toLocalDate(): Promise<java_time_chrono_ChronoLocalDate | null>;
    // ================== Method toLocalDate ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public toLocalDateSync(): java_time_chrono_ChronoLocalDate | null;
    // ================== Method toLocalTime ==================
    /**
     * @return original return type: 'java.time.LocalTime'
     */
    public toLocalTime(): Promise<java_time_LocalTime | null>;
    // ================== Method toLocalTime ==================
    /**
     * @return original return type: 'java.time.LocalTime'
     */
    public toLocalTimeSync(): java_time_LocalTime | null;
    // ================== Method toEpochSecond ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'long'
     */
    public toEpochSecond(var0: java_time_ZoneOffset | null): Promise<number>;
    // ================== Method toEpochSecond ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'long'
     */
    public toEpochSecondSync(var0: java_time_ZoneOffset | null): number;
    // ================== Method isEqual ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isEqual(var0: ChronoLocalDateTimeClass | null): Promise<boolean>;
    // ================== Method isEqual ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isEqualSync(var0: ChronoLocalDateTimeClass | null): boolean;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public static from(var0: java_time_temporal_TemporalAccessor | null): Promise<ChronoLocalDateTime | null>;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public static fromSync(var0: java_time_temporal_TemporalAccessor | null): ChronoLocalDateTime | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'int'
     */
    public compareTo(var0: ChronoLocalDateTimeClass | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'int'
     */
    public compareToSync(var0: ChronoLocalDateTimeClass | null): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.lang.String'
     */
    public format(var0: java_time_format_DateTimeFormatter | null): Promise<string | null>;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.lang.String'
     */
    public formatSync(var0: java_time_format_DateTimeFormatter | null): string | null;
    // ================== Method query ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalQuery'
     * @return original return type: 'java.lang.Object'
     */
    public query(var0: java_time_temporal_TemporalQuery | null): Promise<BasicOrJavaType | null>;
    // ================== Method query ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalQuery'
     * @return original return type: 'java.lang.Object'
     */
    public querySync(var0: java_time_temporal_TemporalQuery | null): BasicOrJavaType | null;
    // ================== Method isSupported ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'boolean'
     */
    public isSupported(var0: java_time_temporal_TemporalField | null): Promise<boolean>;
    // ================== Method isSupported ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'boolean'
     */
    public isSupportedSync(var0: java_time_temporal_TemporalField | null): boolean;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'boolean'
     */
    public isSupported(var0: java_time_temporal_TemporalUnit | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'boolean'
     */
    public isSupportedSync(var0: java_time_temporal_TemporalUnit | null): boolean;
    // ================== Method until ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public until(var0: java_time_temporal_Temporal | null, var1: java_time_temporal_TemporalUnit | null): Promise<number>;
    // ================== Method until ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public untilSync(var0: java_time_temporal_Temporal | null, var1: java_time_temporal_TemporalUnit | null): number;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'int'
     */
    public get(var0: java_time_temporal_TemporalField | null): Promise<number>;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'int'
     */
    public getSync(var0: java_time_temporal_TemporalField | null): number;
    // ================== Method getLong ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'long'
     */
    public getLong(var0: java_time_temporal_TemporalField | null): Promise<number>;
    // ================== Method getLong ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'long'
     */
    public getLongSync(var0: java_time_temporal_TemporalField | null): number;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'java.time.temporal.ValueRange'
     */
    public range(var0: java_time_temporal_TemporalField | null): Promise<java_time_temporal_ValueRange | null>;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'java.time.temporal.ValueRange'
     */
    public rangeSync(var0: java_time_temporal_TemporalField | null): java_time_temporal_ValueRange | null;
}

/**
 * Class java.time.chrono.ChronoLocalDateTime.
 *
 * This actually imports the java class for further use.
 * The class ChronoLocalDateTimeClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class ChronoLocalDateTime extends importClass<typeof ChronoLocalDateTimeClass>("java.time.chrono.ChronoLocalDateTime") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default ChronoLocalDateTime;