import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Chronology as java_time_chrono_Chronology } from "./Chronology";
import { Integer as java_lang_Integer } from "./../../lang/Integer";
import { TemporalAmount as java_time_temporal_TemporalAmount } from "./../temporal/TemporalAmount";
import { Temporal as java_time_temporal_Temporal } from "./../temporal/Temporal";
import { ChronoLocalDate as java_time_chrono_ChronoLocalDate } from "./ChronoLocalDate";
import { List as java_util_List } from "./../../util/List";
import { TemporalUnit as java_time_temporal_TemporalUnit } from "./../temporal/TemporalUnit";

/**
 * This class just defines types, you should import ChronoPeriod instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ChronoPeriodClass extends JavaClass {
    // ================== Method getChronology ==================
    /**
     * @return original return type: 'java.time.chrono.Chronology'
     */
    public getChronology(): Promise<java_time_chrono_Chronology | null>;
    // ================== Method getChronology ==================
    /**
     * @return original return type: 'java.time.chrono.Chronology'
     */
    public getChronologySync(): java_time_chrono_Chronology | null;
    // ================== Method isZero ==================
    /**
     * @return original return type: 'boolean'
     */
    public isZero(): Promise<boolean>;
    // ================== Method isZero ==================
    /**
     * @return original return type: 'boolean'
     */
    public isZeroSync(): boolean;
    // ================== Method multipliedBy ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public multipliedBy(var0: java_lang_Integer | number): Promise<ChronoPeriod | null>;
    // ================== Method multipliedBy ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public multipliedBySync(var0: java_lang_Integer | number): ChronoPeriod | null;
    // ================== Method negated ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public negated(): Promise<ChronoPeriod | null>;
    // ================== Method negated ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public negatedSync(): ChronoPeriod | null;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<ChronoPeriod | null>;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): ChronoPeriod | null;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<ChronoPeriod | null>;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): ChronoPeriod | null;
    // ================== Method addTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public addTo(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method addTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public addToSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method subtractFrom ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public subtractFrom(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method subtractFrom ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public subtractFromSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method between ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDate'
     * @param var1 original type: 'java.time.chrono.ChronoLocalDate'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public static between(var0: java_time_chrono_ChronoLocalDate | null, var1: java_time_chrono_ChronoLocalDate | null): Promise<ChronoPeriod | null>;
    // ================== Method between ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDate'
     * @param var1 original type: 'java.time.chrono.ChronoLocalDate'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public static betweenSync(var0: java_time_chrono_ChronoLocalDate | null, var1: java_time_chrono_ChronoLocalDate | null): ChronoPeriod | null;
    // ================== Method isNegative ==================
    /**
     * @return original return type: 'boolean'
     */
    public isNegative(): Promise<boolean>;
    // ================== Method isNegative ==================
    /**
     * @return original return type: 'boolean'
     */
    public isNegativeSync(): boolean;
    // ================== Method getUnits ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getUnits(): Promise<java_util_List | null>;
    // ================== Method getUnits ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getUnitsSync(): java_util_List | null;
    // ================== Method normalized ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public normalized(): Promise<ChronoPeriod | null>;
    // ================== Method normalized ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public normalizedSync(): ChronoPeriod | null;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public get(var0: java_time_temporal_TemporalUnit | null): Promise<number>;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public getSync(var0: java_time_temporal_TemporalUnit | null): number;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
}

/**
 * Class java.time.chrono.ChronoPeriod.
 *
 * This actually imports the java class for further use.
 * The class ChronoPeriodClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class ChronoPeriod extends importClass<typeof ChronoPeriodClass>("java.time.chrono.ChronoPeriod") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default ChronoPeriod;