import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { ChronoLocalDateTime as java_time_chrono_ChronoLocalDateTime } from "./ChronoLocalDateTime";
import { TemporalAccessor as java_time_temporal_TemporalAccessor } from "./../temporal/TemporalAccessor";
import { LocalDateTime as java_time_LocalDateTime } from "./../LocalDateTime";
import { ZonedDateTime as java_time_ZonedDateTime } from "./../ZonedDateTime";
import { Instant as java_time_Instant } from "./../Instant";
import { ZoneId as java_time_ZoneId } from "./../ZoneId";
import { ChronoZonedDateTime as java_time_chrono_ChronoZonedDateTime } from "./ChronoZonedDateTime";
import { Long as java_lang_Long } from "./../../lang/Long";
import { IsoEra as java_time_chrono_IsoEra } from "./IsoEra";
import { Integer as java_lang_Integer } from "./../../lang/Integer";
import { Era as java_time_chrono_Era } from "./Era";
import { ChronoLocalDate as java_time_chrono_ChronoLocalDate } from "./ChronoLocalDate";
import { LocalDate as java_time_LocalDate } from "./../LocalDate";
import { Clock as java_time_Clock } from "./../Clock";
import { List as java_util_List } from "./../../util/List";
import { Map as java_util_Map } from "./../../util/Map";
import { ResolverStyle as java_time_format_ResolverStyle } from "./../format/ResolverStyle";
import { Period as java_time_Period } from "./../Period";
import { ChronoPeriod as java_time_chrono_ChronoPeriod } from "./ChronoPeriod";
import { ValueRange as java_time_temporal_ValueRange } from "./../temporal/ValueRange";
import { ChronoField as java_time_temporal_ChronoField } from "./../temporal/ChronoField";
import { Chronology as java_time_chrono_Chronology } from "./Chronology";
import { Class as java_lang_Class } from "./../../lang/Class";
import { TextStyle as java_time_format_TextStyle } from "./../format/TextStyle";
import { Locale as java_util_Locale } from "./../../util/Locale";

/**
 * This class just defines types, you should import IsoChronology instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IsoChronologyClass extends JavaClass {
    // ================== Field INSTANCE ==================
    /**
     * Original type: 'java.time.chrono.IsoChronology'
     */
    public static readonly INSTANCE: IsoChronologyClass | null;
    // ================== Method localDateTime ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public localDateTime(var0: java_time_temporal_TemporalAccessor | null): Promise<java_time_chrono_ChronoLocalDateTime | null>;
    // ================== Method localDateTime ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public localDateTimeSync(var0: java_time_temporal_TemporalAccessor | null): java_time_chrono_ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public localDateTime(var0: java_time_temporal_TemporalAccessor | null): Promise<java_time_LocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public localDateTimeSync(var0: java_time_temporal_TemporalAccessor | null): java_time_LocalDateTime | null;
    // ================== Method zonedDateTime ==================
    /**
     * @param var0 original type: 'java.time.Instant'
     * @param var1 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.ZonedDateTime'
     */
    public zonedDateTime(var0: java_time_Instant | null, var1: java_time_ZoneId | null): Promise<java_time_ZonedDateTime | null>;
    // ================== Method zonedDateTime ==================
    /**
     * @param var0 original type: 'java.time.Instant'
     * @param var1 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.ZonedDateTime'
     */
    public zonedDateTimeSync(var0: java_time_Instant | null, var1: java_time_ZoneId | null): java_time_ZonedDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.chrono.ChronoZonedDateTime'
     */
    public zonedDateTime(var0: java_time_temporal_TemporalAccessor | null): Promise<java_time_chrono_ChronoZonedDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.chrono.ChronoZonedDateTime'
     */
    public zonedDateTimeSync(var0: java_time_temporal_TemporalAccessor | null): java_time_chrono_ChronoZonedDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.ZonedDateTime'
     */
    public zonedDateTime(var0: java_time_temporal_TemporalAccessor | null): Promise<java_time_ZonedDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.ZonedDateTime'
     */
    public zonedDateTimeSync(var0: java_time_temporal_TemporalAccessor | null): java_time_ZonedDateTime | null;
    /**
     * @param var0 original type: 'java.time.Instant'
     * @param var1 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.chrono.ChronoZonedDateTime'
     */
    public zonedDateTime(var0: java_time_Instant | null, var1: java_time_ZoneId | null): Promise<java_time_chrono_ChronoZonedDateTime | null>;
    /**
     * @param var0 original type: 'java.time.Instant'
     * @param var1 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.chrono.ChronoZonedDateTime'
     */
    public zonedDateTimeSync(var0: java_time_Instant | null, var1: java_time_ZoneId | null): java_time_chrono_ChronoZonedDateTime | null;
    // ================== Method isLeapYear ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'boolean'
     */
    public isLeapYear(var0: java_lang_Long | bigint | number): Promise<boolean>;
    // ================== Method isLeapYear ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'boolean'
     */
    public isLeapYearSync(var0: java_lang_Long | bigint | number): boolean;
    // ================== Method eraOf ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.chrono.IsoEra'
     */
    public eraOf(var0: java_lang_Integer | number): Promise<java_time_chrono_IsoEra | null>;
    // ================== Method eraOf ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.chrono.IsoEra'
     */
    public eraOfSync(var0: java_lang_Integer | number): java_time_chrono_IsoEra | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.chrono.Era'
     */
    public eraOf(var0: java_lang_Integer | number): Promise<java_time_chrono_Era | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.chrono.Era'
     */
    public eraOfSync(var0: java_lang_Integer | number): java_time_chrono_Era | null;
    // ================== Method getCalendarType ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getCalendarType(): Promise<string | null>;
    // ================== Method getCalendarType ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getCalendarTypeSync(): string | null;
    // ================== Method dateYearDay ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateYearDay(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<java_time_chrono_ChronoLocalDate | null>;
    // ================== Method dateYearDay ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateYearDaySync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): java_time_chrono_ChronoLocalDate | null;
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateYearDay(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_time_LocalDate | null>;
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateYearDaySync(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_time_LocalDate | null;
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateYearDay(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_time_chrono_ChronoLocalDate | null>;
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateYearDaySync(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_time_chrono_ChronoLocalDate | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateYearDay(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<java_time_LocalDate | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateYearDaySync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): java_time_LocalDate | null;
    // ================== Method dateEpochDay ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateEpochDay(var0: java_lang_Long | bigint | number): Promise<java_time_LocalDate | null>;
    // ================== Method dateEpochDay ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateEpochDaySync(var0: java_lang_Long | bigint | number): java_time_LocalDate | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateEpochDay(var0: java_lang_Long | bigint | number): Promise<java_time_chrono_ChronoLocalDate | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateEpochDaySync(var0: java_lang_Long | bigint | number): java_time_chrono_ChronoLocalDate | null;
    // ================== Method dateNow ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateNow(): Promise<java_time_chrono_ChronoLocalDate | null>;
    // ================== Method dateNow ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateNowSync(): java_time_chrono_ChronoLocalDate | null;
    /**
     * @return original return type: 'java.time.LocalDate'
     */
    public dateNow(): Promise<java_time_LocalDate | null>;
    /**
     * @return original return type: 'java.time.LocalDate'
     */
    public dateNowSync(): java_time_LocalDate | null;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateNow(var0: java_time_ZoneId | null): Promise<java_time_LocalDate | null>;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateNowSync(var0: java_time_ZoneId | null): java_time_LocalDate | null;
    /**
     * @param var0 original type: 'java.time.Clock'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateNow(var0: java_time_Clock | null): Promise<java_time_LocalDate | null>;
    /**
     * @param var0 original type: 'java.time.Clock'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateNowSync(var0: java_time_Clock | null): java_time_LocalDate | null;
    /**
     * @param var0 original type: 'java.time.Clock'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateNow(var0: java_time_Clock | null): Promise<java_time_chrono_ChronoLocalDate | null>;
    /**
     * @param var0 original type: 'java.time.Clock'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateNowSync(var0: java_time_Clock | null): java_time_chrono_ChronoLocalDate | null;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateNow(var0: java_time_ZoneId | null): Promise<java_time_chrono_ChronoLocalDate | null>;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateNowSync(var0: java_time_ZoneId | null): java_time_chrono_ChronoLocalDate | null;
    // ================== Method prolepticYear ==================
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @return original return type: 'int'
     */
    public prolepticYear(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number): Promise<number>;
    // ================== Method prolepticYear ==================
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @return original return type: 'int'
     */
    public prolepticYearSync(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number): number;
    // ================== Method eras ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public eras(): Promise<java_util_List | null>;
    // ================== Method eras ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public erasSync(): java_util_List | null;
    // ================== Method resolveDate ==================
    /**
     * @param var0 original type: 'java.util.Map'
     * @param var1 original type: 'java.time.format.ResolverStyle'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public resolveDate(var0: java_util_Map | null, var1: java_time_format_ResolverStyle | null): Promise<java_time_chrono_ChronoLocalDate | null>;
    // ================== Method resolveDate ==================
    /**
     * @param var0 original type: 'java.util.Map'
     * @param var1 original type: 'java.time.format.ResolverStyle'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public resolveDateSync(var0: java_util_Map | null, var1: java_time_format_ResolverStyle | null): java_time_chrono_ChronoLocalDate | null;
    /**
     * @param var0 original type: 'java.util.Map'
     * @param var1 original type: 'java.time.format.ResolverStyle'
     * @return original return type: 'java.time.LocalDate'
     */
    public resolveDate(var0: java_util_Map | null, var1: java_time_format_ResolverStyle | null): Promise<java_time_LocalDate | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @param var1 original type: 'java.time.format.ResolverStyle'
     * @return original return type: 'java.time.LocalDate'
     */
    public resolveDateSync(var0: java_util_Map | null, var1: java_time_format_ResolverStyle | null): java_time_LocalDate | null;
    // ================== Method period ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public period(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_time_Period | null>;
    // ================== Method period ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public periodSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_time_Period | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public period(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_time_chrono_ChronoPeriod | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public periodSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_time_chrono_ChronoPeriod | null;
    // ================== Method date ==================
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @return original return type: 'java.time.LocalDate'
     */
    public date(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number): Promise<java_time_LocalDate | null>;
    // ================== Method date ==================
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateSync(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number): java_time_LocalDate | null;
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public date(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number): Promise<java_time_chrono_ChronoLocalDate | null>;
    /**
     * @param var0 original type: 'java.time.chrono.Era'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateSync(var0: java_time_chrono_Era | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number): java_time_chrono_ChronoLocalDate | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.LocalDate'
     */
    public date(var0: java_time_temporal_TemporalAccessor | null): Promise<java_time_LocalDate | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateSync(var0: java_time_temporal_TemporalAccessor | null): java_time_LocalDate | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public date(var0: java_time_temporal_TemporalAccessor | null): Promise<java_time_chrono_ChronoLocalDate | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateSync(var0: java_time_temporal_TemporalAccessor | null): java_time_chrono_ChronoLocalDate | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.LocalDate'
     */
    public date(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_time_LocalDate | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.LocalDate'
     */
    public dateSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_time_LocalDate | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public date(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_time_chrono_ChronoLocalDate | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public dateSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_time_chrono_ChronoLocalDate | null;
    // ================== Method getId ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getId(): Promise<string | null>;
    // ================== Method getId ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getIdSync(): string | null;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'java.time.temporal.ChronoField'
     * @return original return type: 'java.time.temporal.ValueRange'
     */
    public range(var0: java_time_temporal_ChronoField | null): Promise<java_time_temporal_ValueRange | null>;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'java.time.temporal.ChronoField'
     * @return original return type: 'java.time.temporal.ValueRange'
     */
    public rangeSync(var0: java_time_temporal_ChronoField | null): java_time_temporal_ValueRange | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.time.chrono.Chronology'
     * @return original return type: 'int'
     */
    public compareTo(var0: java_time_chrono_Chronology | null): Promise<number>;
    /**
     * @param var0 original type: 'java.time.chrono.Chronology'
     * @return original return type: 'int'
     */
    public compareToSync(var0: java_time_chrono_Chronology | null): number;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method getDisplayName ==================
    /**
     * @param var0 original type: 'java.time.format.TextStyle'
     * @param var1 original type: 'java.util.Locale'
     * @return original return type: 'java.lang.String'
     */
    public getDisplayName(var0: java_time_format_TextStyle | null, var1: java_util_Locale | null): Promise<string | null>;
    // ================== Method getDisplayName ==================
    /**
     * @param var0 original type: 'java.time.format.TextStyle'
     * @param var1 original type: 'java.util.Locale'
     * @return original return type: 'java.lang.String'
     */
    public getDisplayNameSync(var0: java_time_format_TextStyle | null, var1: java_util_Locale | null): string | null;
}

/**
 * Class java.time.chrono.IsoChronology.
 *
 * This actually imports the java class for further use.
 * The class IsoChronologyClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class IsoChronology extends importClass<typeof IsoChronologyClass>("java.time.chrono.IsoChronology") {
}
export default IsoChronology;