import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Iterator as java_util_Iterator } from "./Iterator";
import { Spliterator as java_util_Spliterator } from "./Spliterator";
import { Stream as java_util_stream_Stream } from "./stream/Stream";
import { Predicate as java_util_function_Predicate } from "./function/Predicate";
import { Consumer as java_util_function_Consumer } from "./function/Consumer";

/**
 * This class just defines types, you should import Collection instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class CollectionClass extends JavaClass {
    // ================== Method add ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public add(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method add ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public addSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method remove ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public remove(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method remove ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public removeSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method clear ==================
    /**
     * @return original return type: 'void'
     */
    public clear(): Promise<void>;
    // ================== Method clear ==================
    /**
     * @return original return type: 'void'
     */
    public clearSync(): void;
    // ================== Method isEmpty ==================
    /**
     * @return original return type: 'boolean'
     */
    public isEmpty(): Promise<boolean>;
    // ================== Method isEmpty ==================
    /**
     * @return original return type: 'boolean'
     */
    public isEmptySync(): boolean;
    // ================== Method contains ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public contains(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method contains ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public containsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method size ==================
    /**
     * @return original return type: 'int'
     */
    public size(): Promise<number>;
    // ================== Method size ==================
    /**
     * @return original return type: 'int'
     */
    public sizeSync(): number;
    // ================== Method toArray ==================
    /**
     * @param var0 original type: 'java.lang.Object[]'
     * @return original return type: 'java.lang.Object[]'
     */
    public toArray(var0: (BasicOrJavaType | null)[] | null): Promise<(BasicOrJavaType | null)[] | null>;
    // ================== Method toArray ==================
    /**
     * @param var0 original type: 'java.lang.Object[]'
     * @return original return type: 'java.lang.Object[]'
     */
    public toArraySync(var0: (BasicOrJavaType | null)[] | null): (BasicOrJavaType | null)[] | null;
    /**
     * @return original return type: 'java.lang.Object[]'
     */
    public toArray(): Promise<(BasicOrJavaType | null)[] | null>;
    /**
     * @return original return type: 'java.lang.Object[]'
     */
    public toArraySync(): (BasicOrJavaType | null)[] | null;
    // ================== Method iterator ==================
    /**
     * @return original return type: 'java.util.Iterator'
     */
    public iterator(): Promise<java_util_Iterator | null>;
    // ================== Method iterator ==================
    /**
     * @return original return type: 'java.util.Iterator'
     */
    public iteratorSync(): java_util_Iterator | null;
    // ================== Method spliterator ==================
    /**
     * @return original return type: 'java.util.Spliterator'
     */
    public spliterator(): Promise<java_util_Spliterator | null>;
    // ================== Method spliterator ==================
    /**
     * @return original return type: 'java.util.Spliterator'
     */
    public spliteratorSync(): java_util_Spliterator | null;
    // ================== Method addAll ==================
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'boolean'
     */
    public addAll(var0: CollectionClass | null): Promise<boolean>;
    // ================== Method addAll ==================
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'boolean'
     */
    public addAllSync(var0: CollectionClass | null): boolean;
    // ================== Method stream ==================
    /**
     * @return original return type: 'java.util.stream.Stream'
     */
    public stream(): Promise<java_util_stream_Stream | null>;
    // ================== Method stream ==================
    /**
     * @return original return type: 'java.util.stream.Stream'
     */
    public streamSync(): java_util_stream_Stream | null;
    // ================== Method containsAll ==================
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'boolean'
     */
    public containsAll(var0: CollectionClass | null): Promise<boolean>;
    // ================== Method containsAll ==================
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'boolean'
     */
    public containsAllSync(var0: CollectionClass | null): boolean;
    // ================== Method removeAll ==================
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'boolean'
     */
    public removeAll(var0: CollectionClass | null): Promise<boolean>;
    // ================== Method removeAll ==================
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'boolean'
     */
    public removeAllSync(var0: CollectionClass | null): boolean;
    // ================== Method retainAll ==================
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'boolean'
     */
    public retainAll(var0: CollectionClass | null): Promise<boolean>;
    // ================== Method retainAll ==================
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'boolean'
     */
    public retainAllSync(var0: CollectionClass | null): boolean;
    // ================== Method removeIf ==================
    /**
     * @param var0 original type: 'java.util.function.Predicate'
     * @return original return type: 'boolean'
     */
    public removeIf(var0: java_util_function_Predicate | null): Promise<boolean>;
    // ================== Method removeIf ==================
    /**
     * @param var0 original type: 'java.util.function.Predicate'
     * @return original return type: 'boolean'
     */
    public removeIfSync(var0: java_util_function_Predicate | null): boolean;
    // ================== Method parallelStream ==================
    /**
     * @return original return type: 'java.util.stream.Stream'
     */
    public parallelStream(): Promise<java_util_stream_Stream | null>;
    // ================== Method parallelStream ==================
    /**
     * @return original return type: 'java.util.stream.Stream'
     */
    public parallelStreamSync(): java_util_stream_Stream | null;
    // ================== Method forEach ==================
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    public forEach(var0: java_util_function_Consumer | null): Promise<void>;
    // ================== Method forEach ==================
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    public forEachSync(var0: java_util_function_Consumer | null): void;
}

/**
 * Class java.util.Collection.
 *
 * This actually imports the java class for further use.
 * The class CollectionClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Collection extends importClass<typeof CollectionClass>("java.util.Collection") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default Collection;