import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Instant as java_time_Instant } from "./../time/Instant";
import { Long as java_lang_Long } from "./../lang/Long";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import Date instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class DateClass extends JavaClass {
    // ================== Method setYear ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setYear(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method setYear ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setYearSync(var0: java_lang_Integer | number): void;
    // ================== Method setMonth ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setMonth(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method setMonth ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setMonthSync(var0: java_lang_Integer | number): void;
    // ================== Method setDate ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setDate(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method setDate ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setDateSync(var0: java_lang_Integer | number): void;
    // ================== Method getDay ==================
    /**
     * @return original return type: 'int'
     */
    public getDay(): Promise<number>;
    // ================== Method getDay ==================
    /**
     * @return original return type: 'int'
     */
    public getDaySync(): number;
    // ================== Method getHours ==================
    /**
     * @return original return type: 'int'
     */
    public getHours(): Promise<number>;
    // ================== Method getHours ==================
    /**
     * @return original return type: 'int'
     */
    public getHoursSync(): number;
    // ================== Method setHours ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setHours(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method setHours ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setHoursSync(var0: java_lang_Integer | number): void;
    // ================== Method getMinutes ==================
    /**
     * @return original return type: 'int'
     */
    public getMinutes(): Promise<number>;
    // ================== Method getMinutes ==================
    /**
     * @return original return type: 'int'
     */
    public getMinutesSync(): number;
    // ================== Method setMinutes ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setMinutes(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method setMinutes ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setMinutesSync(var0: java_lang_Integer | number): void;
    // ================== Method setSeconds ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setSeconds(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method setSeconds ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setSecondsSync(var0: java_lang_Integer | number): void;
    // ================== Method toLocaleString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toLocaleString(): Promise<string | null>;
    // ================== Method toLocaleString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toLocaleStringSync(): string | null;
    // ================== Method toGMTString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toGMTString(): Promise<string | null>;
    // ================== Method toGMTString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toGMTStringSync(): string | null;
    // ================== Method getTimezoneOffset ==================
    /**
     * @return original return type: 'int'
     */
    public getTimezoneOffset(): Promise<number>;
    // ================== Method getTimezoneOffset ==================
    /**
     * @return original return type: 'int'
     */
    public getTimezoneOffsetSync(): number;
    // ================== Method toInstant ==================
    /**
     * @return original return type: 'java.time.Instant'
     */
    public toInstant(): Promise<java_time_Instant | null>;
    // ================== Method toInstant ==================
    /**
     * @return original return type: 'java.time.Instant'
     */
    public toInstantSync(): java_time_Instant | null;
    // ================== Method UTC ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'long'
     */
    public static UTC(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number): Promise<number>;
    // ================== Method UTC ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'long'
     */
    public static UTCSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number): number;
    // ================== Method getYear ==================
    /**
     * @return original return type: 'int'
     */
    public getYear(): Promise<number>;
    // ================== Method getYear ==================
    /**
     * @return original return type: 'int'
     */
    public getYearSync(): number;
    // ================== Method getSeconds ==================
    /**
     * @return original return type: 'int'
     */
    public getSeconds(): Promise<number>;
    // ================== Method getSeconds ==================
    /**
     * @return original return type: 'int'
     */
    public getSecondsSync(): number;
    // ================== Method getMonth ==================
    /**
     * @return original return type: 'int'
     */
    public getMonth(): Promise<number>;
    // ================== Method getMonth ==================
    /**
     * @return original return type: 'int'
     */
    public getMonthSync(): number;
    // ================== Method setTime ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public setTime(var0: java_lang_Long | bigint | number): Promise<void>;
    // ================== Method setTime ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public setTimeSync(var0: java_lang_Long | bigint | number): void;
    // ================== Method getTime ==================
    /**
     * @return original return type: 'long'
     */
    public getTime(): Promise<number>;
    // ================== Method getTime ==================
    /**
     * @return original return type: 'long'
     */
    public getTimeSync(): number;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.Instant'
     * @return original return type: 'java.util.Date'
     */
    public static from(var0: java_time_Instant | null): Promise<Date | null>;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.Instant'
     * @return original return type: 'java.util.Date'
     */
    public static fromSync(var0: java_time_Instant | null): Date | null;
    // ================== Method getDate ==================
    /**
     * @return original return type: 'int'
     */
    public getDate(): Promise<number>;
    // ================== Method getDate ==================
    /**
     * @return original return type: 'int'
     */
    public getDateSync(): number;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method clone ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public clone(): Promise<BasicOrJavaType | null>;
    // ================== Method clone ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public cloneSync(): BasicOrJavaType | null;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'int'
     */
    public compareTo(var0: DateClass | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'int'
     */
    public compareToSync(var0: DateClass | null): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'long'
     */
    public static parse(var0: string | null): Promise<number>;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'long'
     */
    public static parseSync(var0: string | null): number;
    // ================== Method before ==================
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'boolean'
     */
    public before(var0: DateClass | null): Promise<boolean>;
    // ================== Method before ==================
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'boolean'
     */
    public beforeSync(var0: DateClass | null): boolean;
    // ================== Method after ==================
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'boolean'
     */
    public after(var0: DateClass | null): Promise<boolean>;
    // ================== Method after ==================
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'boolean'
     */
    public afterSync(var0: DateClass | null): boolean;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method newInstance ==================
    /**
     * @return original return type: 'java.util.Date'
     */
    public static newInstance(): Promise<Date>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.Date'
     */
    public static newInstance(var0: java_lang_Long | bigint | number): Promise<Date>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @return original return type: 'java.util.Date'
     */
    public static newInstance(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number): Promise<Date>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'java.util.Date'
     */
    public static newInstance(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number): Promise<Date>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.Date'
     */
    public static newInstance(var0: string | null): Promise<Date>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.util.Date'
     */
    public static newInstance(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<Date>;
    // ================== Constructors ==================
    public constructor();
    /**
     * @param var0 original type: 'long'
     */
    public constructor(var0: java_lang_Long | bigint | number);
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     */
    public constructor(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number);
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     */
    public constructor(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number);
    /**
     * @param var0 original type: 'java.lang.String'
     */
    public constructor(var0: string | null);
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     */
    public constructor(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number);
}

/**
 * Class java.util.Date.
 *
 * This actually imports the java class for further use.
 * The class DateClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Date extends importClass<typeof DateClass>("java.util.Date") {
}
export default Date;