import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Consumer as java_util_function_Consumer } from "./function/Consumer";

/**
 * This class just defines types, you should import ListIterator instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ListIteratorClass extends JavaClass {
    // ================== Method add ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public add(var0: BasicOrJavaType | null): Promise<void>;
    // ================== Method add ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public addSync(var0: BasicOrJavaType | null): void;
    // ================== Method remove ==================
    /**
     * @return original return type: 'void'
     */
    public remove(): Promise<void>;
    // ================== Method remove ==================
    /**
     * @return original return type: 'void'
     */
    public removeSync(): void;
    // ================== Method hasNext ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasNext(): Promise<boolean>;
    // ================== Method hasNext ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasNextSync(): boolean;
    // ================== Method next ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public next(): Promise<BasicOrJavaType | null>;
    // ================== Method next ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public nextSync(): BasicOrJavaType | null;
    // ================== Method set ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public set(var0: BasicOrJavaType | null): Promise<void>;
    // ================== Method set ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public setSync(var0: BasicOrJavaType | null): void;
    // ================== Method previousIndex ==================
    /**
     * @return original return type: 'int'
     */
    public previousIndex(): Promise<number>;
    // ================== Method previousIndex ==================
    /**
     * @return original return type: 'int'
     */
    public previousIndexSync(): number;
    // ================== Method hasPrevious ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasPrevious(): Promise<boolean>;
    // ================== Method hasPrevious ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasPreviousSync(): boolean;
    // ================== Method previous ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public previous(): Promise<BasicOrJavaType | null>;
    // ================== Method previous ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public previousSync(): BasicOrJavaType | null;
    // ================== Method nextIndex ==================
    /**
     * @return original return type: 'int'
     */
    public nextIndex(): Promise<number>;
    // ================== Method nextIndex ==================
    /**
     * @return original return type: 'int'
     */
    public nextIndexSync(): number;
    // ================== Method forEachRemaining ==================
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    public forEachRemaining(var0: java_util_function_Consumer | null): Promise<void>;
    // ================== Method forEachRemaining ==================
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    public forEachRemainingSync(var0: java_util_function_Consumer | null): void;
}

/**
 * Class java.util.ListIterator.
 *
 * This actually imports the java class for further use.
 * The class ListIteratorClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class ListIterator extends importClass<typeof ListIteratorClass>("java.util.ListIterator") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default ListIterator;