import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Long as java_lang_Long } from "./../lang/Long";
import { Class as java_lang_Class } from "./../lang/Class";
import { LongConsumer as java_util_function_LongConsumer } from "./function/LongConsumer";
import { IntConsumer as java_util_function_IntConsumer } from "./function/IntConsumer";

/**
 * This class just defines types, you should import LongSummaryStatistics instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LongSummaryStatisticsClass extends JavaClass {
    // ================== Method getCount ==================
    /**
     * @return original return type: 'long'
     */
    public getCount(): Promise<number>;
    // ================== Method getCount ==================
    /**
     * @return original return type: 'long'
     */
    public getCountSync(): number;
    // ================== Method getSum ==================
    /**
     * @return original return type: 'long'
     */
    public getSum(): Promise<number>;
    // ================== Method getSum ==================
    /**
     * @return original return type: 'long'
     */
    public getSumSync(): number;
    // ================== Method getMin ==================
    /**
     * @return original return type: 'long'
     */
    public getMin(): Promise<number>;
    // ================== Method getMin ==================
    /**
     * @return original return type: 'long'
     */
    public getMinSync(): number;
    // ================== Method getMax ==================
    /**
     * @return original return type: 'long'
     */
    public getMax(): Promise<number>;
    // ================== Method getMax ==================
    /**
     * @return original return type: 'long'
     */
    public getMaxSync(): number;
    // ================== Method getAverage ==================
    /**
     * @return original return type: 'double'
     */
    public getAverage(): Promise<number>;
    // ================== Method getAverage ==================
    /**
     * @return original return type: 'double'
     */
    public getAverageSync(): number;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public accept(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public acceptSync(var0: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public accept(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public acceptSync(var0: java_lang_Long | bigint | number): void;
    // ================== Method combine ==================
    /**
     * @param var0 original type: 'java.util.LongSummaryStatistics'
     * @return original return type: 'void'
     */
    public combine(var0: LongSummaryStatisticsClass | null): Promise<void>;
    // ================== Method combine ==================
    /**
     * @param var0 original type: 'java.util.LongSummaryStatistics'
     * @return original return type: 'void'
     */
    public combineSync(var0: LongSummaryStatisticsClass | null): void;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'java.util.function.LongConsumer'
     */
    public andThen(var0: java_util_function_LongConsumer | null): Promise<java_util_function_LongConsumer | null>;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'java.util.function.LongConsumer'
     */
    public andThenSync(var0: java_util_function_LongConsumer | null): java_util_function_LongConsumer | null;
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @return original return type: 'java.util.function.IntConsumer'
     */
    public andThen(var0: java_util_function_IntConsumer | null): Promise<java_util_function_IntConsumer | null>;
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @return original return type: 'java.util.function.IntConsumer'
     */
    public andThenSync(var0: java_util_function_IntConsumer | null): java_util_function_IntConsumer | null;
    // ================== Method newInstance ==================
    /**
     * @return original return type: 'java.util.LongSummaryStatistics'
     */
    public static newInstance(): Promise<LongSummaryStatistics>;
    // ================== Constructors ==================
    public constructor();
}

/**
 * Class java.util.LongSummaryStatistics.
 *
 * This actually imports the java class for further use.
 * The class LongSummaryStatisticsClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class LongSummaryStatistics extends importClass<typeof LongSummaryStatisticsClass>("java.util.LongSummaryStatistics") {
}
export default LongSummaryStatistics;