import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { LongConsumer as java_util_function_LongConsumer } from "./function/LongConsumer";
import { Long as java_lang_Long } from "./../lang/Long";
import { LongSupplier as java_util_function_LongSupplier } from "./function/LongSupplier";
import { Supplier as java_util_function_Supplier } from "./function/Supplier";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import OptionalLong instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class OptionalLongClass extends JavaClass {
    // ================== Method isPresent ==================
    /**
     * @return original return type: 'boolean'
     */
    public isPresent(): Promise<boolean>;
    // ================== Method isPresent ==================
    /**
     * @return original return type: 'boolean'
     */
    public isPresentSync(): boolean;
    // ================== Method ifPresent ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'void'
     */
    public ifPresent(var0: java_util_function_LongConsumer | null): Promise<void>;
    // ================== Method ifPresent ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'void'
     */
    public ifPresentSync(var0: java_util_function_LongConsumer | null): void;
    // ================== Method orElse ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public orElse(var0: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method orElse ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public orElseSync(var0: java_lang_Long | bigint | number): number;
    // ================== Method orElseGet ==================
    /**
     * @param var0 original type: 'java.util.function.LongSupplier'
     * @return original return type: 'long'
     */
    public orElseGet(var0: java_util_function_LongSupplier | null): Promise<number>;
    // ================== Method orElseGet ==================
    /**
     * @param var0 original type: 'java.util.function.LongSupplier'
     * @return original return type: 'long'
     */
    public orElseGetSync(var0: java_util_function_LongSupplier | null): number;
    // ================== Method orElseThrow ==================
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @return original return type: 'long'
     */
    public orElseThrow(var0: java_util_function_Supplier | null): Promise<number>;
    // ================== Method orElseThrow ==================
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @return original return type: 'long'
     */
    public orElseThrowSync(var0: java_util_function_Supplier | null): number;
    // ================== Method getAsLong ==================
    /**
     * @return original return type: 'long'
     */
    public getAsLong(): Promise<number>;
    // ================== Method getAsLong ==================
    /**
     * @return original return type: 'long'
     */
    public getAsLongSync(): number;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.OptionalLong'
     */
    public static of(var0: java_lang_Long | bigint | number): Promise<OptionalLong | null>;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.OptionalLong'
     */
    public static ofSync(var0: java_lang_Long | bigint | number): OptionalLong | null;
    // ================== Method empty ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public static empty(): Promise<OptionalLong | null>;
    // ================== Method empty ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public static emptySync(): OptionalLong | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.util.OptionalLong.
 *
 * This actually imports the java class for further use.
 * The class OptionalLongClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class OptionalLong extends importClass<typeof OptionalLongClass>("java.util.OptionalLong") {
}
export default OptionalLong;