import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Consumer as java_util_function_Consumer } from "./function/Consumer";
import { Supplier as java_util_function_Supplier } from "./function/Supplier";
import { Function as java_util_function_Function } from "./function/Function";
import { Predicate as java_util_function_Predicate } from "./function/Predicate";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import Optional instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class OptionalClass extends JavaClass {
    // ================== Method ofNullable ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.util.Optional'
     */
    public static ofNullable(var0: BasicOrJavaType | null): Promise<Optional | null>;
    // ================== Method ofNullable ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.util.Optional'
     */
    public static ofNullableSync(var0: BasicOrJavaType | null): Optional | null;
    // ================== Method isPresent ==================
    /**
     * @return original return type: 'boolean'
     */
    public isPresent(): Promise<boolean>;
    // ================== Method isPresent ==================
    /**
     * @return original return type: 'boolean'
     */
    public isPresentSync(): boolean;
    // ================== Method ifPresent ==================
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    public ifPresent(var0: java_util_function_Consumer | null): Promise<void>;
    // ================== Method ifPresent ==================
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    public ifPresentSync(var0: java_util_function_Consumer | null): void;
    // ================== Method orElse ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.lang.Object'
     */
    public orElse(var0: BasicOrJavaType | null): Promise<BasicOrJavaType | null>;
    // ================== Method orElse ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.lang.Object'
     */
    public orElseSync(var0: BasicOrJavaType | null): BasicOrJavaType | null;
    // ================== Method orElseGet ==================
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @return original return type: 'java.lang.Object'
     */
    public orElseGet(var0: java_util_function_Supplier | null): Promise<BasicOrJavaType | null>;
    // ================== Method orElseGet ==================
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @return original return type: 'java.lang.Object'
     */
    public orElseGetSync(var0: java_util_function_Supplier | null): BasicOrJavaType | null;
    // ================== Method orElseThrow ==================
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @return original return type: 'java.lang.Object'
     */
    public orElseThrow(var0: java_util_function_Supplier | null): Promise<BasicOrJavaType | null>;
    // ================== Method orElseThrow ==================
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @return original return type: 'java.lang.Object'
     */
    public orElseThrowSync(var0: java_util_function_Supplier | null): BasicOrJavaType | null;
    // ================== Method flatMap ==================
    /**
     * @param var0 original type: 'java.util.function.Function'
     * @return original return type: 'java.util.Optional'
     */
    public flatMap(var0: java_util_function_Function | null): Promise<Optional | null>;
    // ================== Method flatMap ==================
    /**
     * @param var0 original type: 'java.util.function.Function'
     * @return original return type: 'java.util.Optional'
     */
    public flatMapSync(var0: java_util_function_Function | null): Optional | null;
    // ================== Method get ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public get(): Promise<BasicOrJavaType | null>;
    // ================== Method get ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public getSync(): BasicOrJavaType | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.util.Optional'
     */
    public static of(var0: BasicOrJavaType | null): Promise<Optional | null>;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.util.Optional'
     */
    public static ofSync(var0: BasicOrJavaType | null): Optional | null;
    // ================== Method empty ==================
    /**
     * @return original return type: 'java.util.Optional'
     */
    public static empty(): Promise<Optional | null>;
    // ================== Method empty ==================
    /**
     * @return original return type: 'java.util.Optional'
     */
    public static emptySync(): Optional | null;
    // ================== Method filter ==================
    /**
     * @param var0 original type: 'java.util.function.Predicate'
     * @return original return type: 'java.util.Optional'
     */
    public filter(var0: java_util_function_Predicate | null): Promise<Optional | null>;
    // ================== Method filter ==================
    /**
     * @param var0 original type: 'java.util.function.Predicate'
     * @return original return type: 'java.util.Optional'
     */
    public filterSync(var0: java_util_function_Predicate | null): Optional | null;
    // ================== Method map ==================
    /**
     * @param var0 original type: 'java.util.function.Function'
     * @return original return type: 'java.util.Optional'
     */
    public map(var0: java_util_function_Function | null): Promise<Optional | null>;
    // ================== Method map ==================
    /**
     * @param var0 original type: 'java.util.function.Function'
     * @return original return type: 'java.util.Optional'
     */
    public mapSync(var0: java_util_function_Function | null): Optional | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.util.Optional.
 *
 * This actually imports the java class for further use.
 * The class OptionalClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Optional extends importClass<typeof OptionalClass>("java.util.Optional") {
}
export default Optional;