import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { DoubleConsumer as java_util_function_DoubleConsumer } from "./function/DoubleConsumer";
import { Consumer as java_util_function_Consumer } from "./function/Consumer";

/**
 * This class just defines types, you should import PrimitiveIterator$OfDouble instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PrimitiveIterator$OfDoubleClass extends JavaClass {
    // ================== Method next ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public next(): Promise<BasicOrJavaType | null>;
    // ================== Method next ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public nextSync(): BasicOrJavaType | null;
    /**
     * @return original return type: 'java.lang.Double'
     */
    public next(): Promise<number | null>;
    /**
     * @return original return type: 'java.lang.Double'
     */
    public nextSync(): number | null;
    // ================== Method nextDouble ==================
    /**
     * @return original return type: 'double'
     */
    public nextDouble(): Promise<number>;
    // ================== Method nextDouble ==================
    /**
     * @return original return type: 'double'
     */
    public nextDoubleSync(): number;
    // ================== Method forEachRemaining ==================
    /**
     * @param var0 original type: 'java.util.function.DoubleConsumer'
     * @return original return type: 'void'
     */
    public forEachRemaining(var0: java_util_function_DoubleConsumer | null): Promise<void>;
    // ================== Method forEachRemaining ==================
    /**
     * @param var0 original type: 'java.util.function.DoubleConsumer'
     * @return original return type: 'void'
     */
    public forEachRemainingSync(var0: java_util_function_DoubleConsumer | null): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public forEachRemaining(var0: BasicOrJavaType | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public forEachRemainingSync(var0: BasicOrJavaType | null): void;
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    public forEachRemaining(var0: java_util_function_Consumer | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    public forEachRemainingSync(var0: java_util_function_Consumer | null): void;
    // ================== Method remove ==================
    /**
     * @return original return type: 'void'
     */
    public remove(): Promise<void>;
    // ================== Method remove ==================
    /**
     * @return original return type: 'void'
     */
    public removeSync(): void;
    // ================== Method hasNext ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasNext(): Promise<boolean>;
    // ================== Method hasNext ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasNextSync(): boolean;
}

/**
 * Class java.util.PrimitiveIterator$OfDouble.
 *
 * This actually imports the java class for further use.
 * The class PrimitiveIterator$OfDoubleClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class PrimitiveIterator$OfDouble extends importClass<typeof PrimitiveIterator$OfDoubleClass>("java.util.PrimitiveIterator$OfDouble") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default PrimitiveIterator$OfDouble;