import { importClass, JavaClass } from "java-bridge";
import { Temporal as java_time_temporal_Temporal } from "./Temporal";
import { List as java_util_List } from "./../../util/List";
import { TemporalUnit as java_time_temporal_TemporalUnit } from "./TemporalUnit";

/**
 * This class just defines types, you should import TemporalAmount instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class TemporalAmountClass extends JavaClass {
    // ================== Method addTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public addTo(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method addTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public addToSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method subtractFrom ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public subtractFrom(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method subtractFrom ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public subtractFromSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method getUnits ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getUnits(): Promise<java_util_List | null>;
    // ================== Method getUnits ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getUnitsSync(): java_util_List | null;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public get(var0: java_time_temporal_TemporalUnit | null): Promise<number>;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public getSync(var0: java_time_temporal_TemporalUnit | null): number;
}

/**
 * Class java.time.temporal.TemporalAmount.
 *
 * This actually imports the java class for further use.
 * The class TemporalAmountClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class TemporalAmount extends importClass<typeof TemporalAmountClass>("java.time.temporal.TemporalAmount") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default TemporalAmount;