import { importClass, JavaClass } from "java-bridge";
import { DoubleStream as java_util_stream_DoubleStream } from "./DoubleStream";
import { Double as java_lang_Double } from "./../../lang/Double";
import { DoubleConsumer as java_util_function_DoubleConsumer } from "./../function/DoubleConsumer";

/**
 * This class just defines types, you should import DoubleStream$Builder instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class DoubleStream$BuilderClass extends JavaClass {
    // ================== Method build ==================
    /**
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    public build(): Promise<java_util_stream_DoubleStream | null>;
    // ================== Method build ==================
    /**
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    public buildSync(): java_util_stream_DoubleStream | null;
    // ================== Method add ==================
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'java.util.stream.DoubleStream$Builder'
     */
    public add(var0: java_lang_Double | number): Promise<DoubleStream$Builder | null>;
    // ================== Method add ==================
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'java.util.stream.DoubleStream$Builder'
     */
    public addSync(var0: java_lang_Double | number): DoubleStream$Builder | null;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'void'
     */
    public accept(var0: java_lang_Double | number): Promise<void>;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'void'
     */
    public acceptSync(var0: java_lang_Double | number): void;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.DoubleConsumer'
     * @return original return type: 'java.util.function.DoubleConsumer'
     */
    public andThen(var0: java_util_function_DoubleConsumer | null): Promise<java_util_function_DoubleConsumer | null>;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.DoubleConsumer'
     * @return original return type: 'java.util.function.DoubleConsumer'
     */
    public andThenSync(var0: java_util_function_DoubleConsumer | null): java_util_function_DoubleConsumer | null;
}

/**
 * Class java.util.stream.DoubleStream$Builder.
 *
 * This actually imports the java class for further use.
 * The class DoubleStream$BuilderClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class DoubleStream$Builder extends importClass<typeof DoubleStream$BuilderClass>("java.util.stream.DoubleStream$Builder") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default DoubleStream$Builder;