import { importClass, JavaClass } from "java-bridge";
import { IntStream as java_util_stream_IntStream } from "./IntStream";
import { Integer as java_lang_Integer } from "./../../lang/Integer";
import { IntConsumer as java_util_function_IntConsumer } from "./../function/IntConsumer";

/**
 * This class just defines types, you should import IntStream$Builder instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IntStream$BuilderClass extends JavaClass {
    // ================== Method build ==================
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    public build(): Promise<java_util_stream_IntStream | null>;
    // ================== Method build ==================
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    public buildSync(): java_util_stream_IntStream | null;
    // ================== Method add ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.util.stream.IntStream$Builder'
     */
    public add(var0: java_lang_Integer | number): Promise<IntStream$Builder | null>;
    // ================== Method add ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.util.stream.IntStream$Builder'
     */
    public addSync(var0: java_lang_Integer | number): IntStream$Builder | null;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public accept(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public acceptSync(var0: java_lang_Integer | number): void;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @return original return type: 'java.util.function.IntConsumer'
     */
    public andThen(var0: java_util_function_IntConsumer | null): Promise<java_util_function_IntConsumer | null>;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.IntConsumer'
     * @return original return type: 'java.util.function.IntConsumer'
     */
    public andThenSync(var0: java_util_function_IntConsumer | null): java_util_function_IntConsumer | null;
}

/**
 * Class java.util.stream.IntStream$Builder.
 *
 * This actually imports the java class for further use.
 * The class IntStream$BuilderClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class IntStream$Builder extends importClass<typeof IntStream$BuilderClass>("java.util.stream.IntStream$Builder") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default IntStream$Builder;