import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { LongSupplier as java_util_function_LongSupplier } from "./../function/LongSupplier";
import { OptionalDouble as java_util_OptionalDouble } from "./../OptionalDouble";
import { LongSummaryStatistics as java_util_LongSummaryStatistics } from "./../LongSummaryStatistics";
import { DoubleStream as java_util_stream_DoubleStream } from "./DoubleStream";
import { Stream as java_util_stream_Stream } from "./Stream";
import { Long as java_lang_Long } from "./../../lang/Long";
import { IntStream as java_util_stream_IntStream } from "./IntStream";
import { LongToIntFunction as java_util_function_LongToIntFunction } from "./../function/LongToIntFunction";
import { LongToDoubleFunction as java_util_function_LongToDoubleFunction } from "./../function/LongToDoubleFunction";
import { LongFunction as java_util_function_LongFunction } from "./../function/LongFunction";
import { LongConsumer as java_util_function_LongConsumer } from "./../function/LongConsumer";
import { LongPredicate as java_util_function_LongPredicate } from "./../function/LongPredicate";
import { OptionalLong as java_util_OptionalLong } from "./../OptionalLong";
import { LongStream$Builder as java_util_stream_LongStream$Builder } from "./LongStream$Builder";
import { LongUnaryOperator as java_util_function_LongUnaryOperator } from "./../function/LongUnaryOperator";
import { BaseStream as java_util_stream_BaseStream } from "./BaseStream";
import { PrimitiveIterator$OfLong as java_util_PrimitiveIterator$OfLong } from "./../PrimitiveIterator$OfLong";
import { Iterator as java_util_Iterator } from "./../Iterator";
import { Spliterator$OfLong as java_util_Spliterator$OfLong } from "./../Spliterator$OfLong";
import { Spliterator as java_util_Spliterator } from "./../Spliterator";
import { Supplier as java_util_function_Supplier } from "./../function/Supplier";
import { ObjLongConsumer as java_util_function_ObjLongConsumer } from "./../function/ObjLongConsumer";
import { BiConsumer as java_util_function_BiConsumer } from "./../function/BiConsumer";
import { LongBinaryOperator as java_util_function_LongBinaryOperator } from "./../function/LongBinaryOperator";
import { Runnable as java_lang_Runnable } from "./../../lang/Runnable";

/**
 * This class just defines types, you should import LongStream instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LongStreamClass extends JavaClass {
    // ================== Method generate ==================
    /**
     * @param var0 original type: 'java.util.function.LongSupplier'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static generate(var0: java_util_function_LongSupplier | null): Promise<LongStream | null>;
    // ================== Method generate ==================
    /**
     * @param var0 original type: 'java.util.function.LongSupplier'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static generateSync(var0: java_util_function_LongSupplier | null): LongStream | null;
    // ================== Method average ==================
    /**
     * @return original return type: 'java.util.OptionalDouble'
     */
    public average(): Promise<java_util_OptionalDouble | null>;
    // ================== Method average ==================
    /**
     * @return original return type: 'java.util.OptionalDouble'
     */
    public averageSync(): java_util_OptionalDouble | null;
    // ================== Method summaryStatistics ==================
    /**
     * @return original return type: 'java.util.LongSummaryStatistics'
     */
    public summaryStatistics(): Promise<java_util_LongSummaryStatistics | null>;
    // ================== Method summaryStatistics ==================
    /**
     * @return original return type: 'java.util.LongSummaryStatistics'
     */
    public summaryStatisticsSync(): java_util_LongSummaryStatistics | null;
    // ================== Method asDoubleStream ==================
    /**
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    public asDoubleStream(): Promise<java_util_stream_DoubleStream | null>;
    // ================== Method asDoubleStream ==================
    /**
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    public asDoubleStreamSync(): java_util_stream_DoubleStream | null;
    // ================== Method boxed ==================
    /**
     * @return original return type: 'java.util.stream.Stream'
     */
    public boxed(): Promise<java_util_stream_Stream | null>;
    // ================== Method boxed ==================
    /**
     * @return original return type: 'java.util.stream.Stream'
     */
    public boxedSync(): java_util_stream_Stream | null;
    // ================== Method rangeClosed ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static rangeClosed(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): Promise<LongStream | null>;
    // ================== Method rangeClosed ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static rangeClosedSync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): LongStream | null;
    // ================== Method mapToInt ==================
    /**
     * @param var0 original type: 'java.util.function.LongToIntFunction'
     * @return original return type: 'java.util.stream.IntStream'
     */
    public mapToInt(var0: java_util_function_LongToIntFunction | null): Promise<java_util_stream_IntStream | null>;
    // ================== Method mapToInt ==================
    /**
     * @param var0 original type: 'java.util.function.LongToIntFunction'
     * @return original return type: 'java.util.stream.IntStream'
     */
    public mapToIntSync(var0: java_util_function_LongToIntFunction | null): java_util_stream_IntStream | null;
    // ================== Method mapToDouble ==================
    /**
     * @param var0 original type: 'java.util.function.LongToDoubleFunction'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    public mapToDouble(var0: java_util_function_LongToDoubleFunction | null): Promise<java_util_stream_DoubleStream | null>;
    // ================== Method mapToDouble ==================
    /**
     * @param var0 original type: 'java.util.function.LongToDoubleFunction'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    public mapToDoubleSync(var0: java_util_function_LongToDoubleFunction | null): java_util_stream_DoubleStream | null;
    // ================== Method flatMap ==================
    /**
     * @param var0 original type: 'java.util.function.LongFunction'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public flatMap(var0: java_util_function_LongFunction | null): Promise<LongStream | null>;
    // ================== Method flatMap ==================
    /**
     * @param var0 original type: 'java.util.function.LongFunction'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public flatMapSync(var0: java_util_function_LongFunction | null): LongStream | null;
    // ================== Method distinct ==================
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public distinct(): Promise<LongStream | null>;
    // ================== Method distinct ==================
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public distinctSync(): LongStream | null;
    // ================== Method sorted ==================
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public sorted(): Promise<LongStream | null>;
    // ================== Method sorted ==================
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public sortedSync(): LongStream | null;
    // ================== Method forEachOrdered ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'void'
     */
    public forEachOrdered(var0: java_util_function_LongConsumer | null): Promise<void>;
    // ================== Method forEachOrdered ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'void'
     */
    public forEachOrderedSync(var0: java_util_function_LongConsumer | null): void;
    // ================== Method anyMatch ==================
    /**
     * @param var0 original type: 'java.util.function.LongPredicate'
     * @return original return type: 'boolean'
     */
    public anyMatch(var0: java_util_function_LongPredicate | null): Promise<boolean>;
    // ================== Method anyMatch ==================
    /**
     * @param var0 original type: 'java.util.function.LongPredicate'
     * @return original return type: 'boolean'
     */
    public anyMatchSync(var0: java_util_function_LongPredicate | null): boolean;
    // ================== Method allMatch ==================
    /**
     * @param var0 original type: 'java.util.function.LongPredicate'
     * @return original return type: 'boolean'
     */
    public allMatch(var0: java_util_function_LongPredicate | null): Promise<boolean>;
    // ================== Method allMatch ==================
    /**
     * @param var0 original type: 'java.util.function.LongPredicate'
     * @return original return type: 'boolean'
     */
    public allMatchSync(var0: java_util_function_LongPredicate | null): boolean;
    // ================== Method noneMatch ==================
    /**
     * @param var0 original type: 'java.util.function.LongPredicate'
     * @return original return type: 'boolean'
     */
    public noneMatch(var0: java_util_function_LongPredicate | null): Promise<boolean>;
    // ================== Method noneMatch ==================
    /**
     * @param var0 original type: 'java.util.function.LongPredicate'
     * @return original return type: 'boolean'
     */
    public noneMatchSync(var0: java_util_function_LongPredicate | null): boolean;
    // ================== Method findFirst ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public findFirst(): Promise<java_util_OptionalLong | null>;
    // ================== Method findFirst ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public findFirstSync(): java_util_OptionalLong | null;
    // ================== Method findAny ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public findAny(): Promise<java_util_OptionalLong | null>;
    // ================== Method findAny ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public findAnySync(): java_util_OptionalLong | null;
    // ================== Method builder ==================
    /**
     * @return original return type: 'java.util.stream.LongStream$Builder'
     */
    public static builder(): Promise<java_util_stream_LongStream$Builder | null>;
    // ================== Method builder ==================
    /**
     * @return original return type: 'java.util.stream.LongStream$Builder'
     */
    public static builderSync(): java_util_stream_LongStream$Builder | null;
    // ================== Method iterate ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.util.function.LongUnaryOperator'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static iterate(var0: java_lang_Long | bigint | number, var1: java_util_function_LongUnaryOperator | null): Promise<LongStream | null>;
    // ================== Method iterate ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.util.function.LongUnaryOperator'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static iterateSync(var0: java_lang_Long | bigint | number, var1: java_util_function_LongUnaryOperator | null): LongStream | null;
    // ================== Method sequential ==================
    /**
     * @return original return type: 'java.util.stream.BaseStream'
     */
    public sequential(): Promise<java_util_stream_BaseStream | null>;
    // ================== Method sequential ==================
    /**
     * @return original return type: 'java.util.stream.BaseStream'
     */
    public sequentialSync(): java_util_stream_BaseStream | null;
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public sequential(): Promise<LongStream | null>;
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public sequentialSync(): LongStream | null;
    // ================== Method mapToObj ==================
    /**
     * @param var0 original type: 'java.util.function.LongFunction'
     * @return original return type: 'java.util.stream.Stream'
     */
    public mapToObj(var0: java_util_function_LongFunction | null): Promise<java_util_stream_Stream | null>;
    // ================== Method mapToObj ==================
    /**
     * @param var0 original type: 'java.util.function.LongFunction'
     * @return original return type: 'java.util.stream.Stream'
     */
    public mapToObjSync(var0: java_util_function_LongFunction | null): java_util_stream_Stream | null;
    // ================== Method limit ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public limit(var0: java_lang_Long | bigint | number): Promise<LongStream | null>;
    // ================== Method limit ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public limitSync(var0: java_lang_Long | bigint | number): LongStream | null;
    // ================== Method count ==================
    /**
     * @return original return type: 'long'
     */
    public count(): Promise<number>;
    // ================== Method count ==================
    /**
     * @return original return type: 'long'
     */
    public countSync(): number;
    // ================== Method min ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public min(): Promise<java_util_OptionalLong | null>;
    // ================== Method min ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public minSync(): java_util_OptionalLong | null;
    // ================== Method max ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public max(): Promise<java_util_OptionalLong | null>;
    // ================== Method max ==================
    /**
     * @return original return type: 'java.util.OptionalLong'
     */
    public maxSync(): java_util_OptionalLong | null;
    // ================== Method concat ==================
    /**
     * @param var0 original type: 'java.util.stream.LongStream'
     * @param var1 original type: 'java.util.stream.LongStream'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static concat(var0: LongStreamClass | null, var1: LongStreamClass | null): Promise<LongStream | null>;
    // ================== Method concat ==================
    /**
     * @param var0 original type: 'java.util.stream.LongStream'
     * @param var1 original type: 'java.util.stream.LongStream'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static concatSync(var0: LongStreamClass | null, var1: LongStreamClass | null): LongStream | null;
    // ================== Method toArray ==================
    /**
     * @return original return type: 'long[]'
     */
    public toArray(): Promise<(number)[] | null>;
    // ================== Method toArray ==================
    /**
     * @return original return type: 'long[]'
     */
    public toArraySync(): (number)[] | null;
    // ================== Method iterator ==================
    /**
     * @return original return type: 'java.util.PrimitiveIterator$OfLong'
     */
    public iterator(): Promise<java_util_PrimitiveIterator$OfLong | null>;
    // ================== Method iterator ==================
    /**
     * @return original return type: 'java.util.PrimitiveIterator$OfLong'
     */
    public iteratorSync(): java_util_PrimitiveIterator$OfLong | null;
    /**
     * @return original return type: 'java.util.Iterator'
     */
    public iterator(): Promise<java_util_Iterator | null>;
    /**
     * @return original return type: 'java.util.Iterator'
     */
    public iteratorSync(): java_util_Iterator | null;
    // ================== Method spliterator ==================
    /**
     * @return original return type: 'java.util.Spliterator$OfLong'
     */
    public spliterator(): Promise<java_util_Spliterator$OfLong | null>;
    // ================== Method spliterator ==================
    /**
     * @return original return type: 'java.util.Spliterator$OfLong'
     */
    public spliteratorSync(): java_util_Spliterator$OfLong | null;
    /**
     * @return original return type: 'java.util.Spliterator'
     */
    public spliterator(): Promise<java_util_Spliterator | null>;
    /**
     * @return original return type: 'java.util.Spliterator'
     */
    public spliteratorSync(): java_util_Spliterator | null;
    // ================== Method collect ==================
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @param var1 original type: 'java.util.function.ObjLongConsumer'
     * @param var2 original type: 'java.util.function.BiConsumer'
     * @return original return type: 'java.lang.Object'
     */
    public collect(var0: java_util_function_Supplier | null, var1: java_util_function_ObjLongConsumer | null, var2: java_util_function_BiConsumer | null): Promise<BasicOrJavaType | null>;
    // ================== Method collect ==================
    /**
     * @param var0 original type: 'java.util.function.Supplier'
     * @param var1 original type: 'java.util.function.ObjLongConsumer'
     * @param var2 original type: 'java.util.function.BiConsumer'
     * @return original return type: 'java.lang.Object'
     */
    public collectSync(var0: java_util_function_Supplier | null, var1: java_util_function_ObjLongConsumer | null, var2: java_util_function_BiConsumer | null): BasicOrJavaType | null;
    // ================== Method forEach ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'void'
     */
    public forEach(var0: java_util_function_LongConsumer | null): Promise<void>;
    // ================== Method forEach ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'void'
     */
    public forEachSync(var0: java_util_function_LongConsumer | null): void;
    // ================== Method skip ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public skip(var0: java_lang_Long | bigint | number): Promise<LongStream | null>;
    // ================== Method skip ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public skipSync(var0: java_lang_Long | bigint | number): LongStream | null;
    // ================== Method peek ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public peek(var0: java_util_function_LongConsumer | null): Promise<LongStream | null>;
    // ================== Method peek ==================
    /**
     * @param var0 original type: 'java.util.function.LongConsumer'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public peekSync(var0: java_util_function_LongConsumer | null): LongStream | null;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'long[]'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static of(var0: (java_lang_Long | bigint | number)[] | null): Promise<LongStream | null>;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'long[]'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static ofSync(var0: (java_lang_Long | bigint | number)[] | null): LongStream | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static of(var0: java_lang_Long | bigint | number): Promise<LongStream | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static ofSync(var0: java_lang_Long | bigint | number): LongStream | null;
    // ================== Method sum ==================
    /**
     * @return original return type: 'long'
     */
    public sum(): Promise<number>;
    // ================== Method sum ==================
    /**
     * @return original return type: 'long'
     */
    public sumSync(): number;
    // ================== Method empty ==================
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static empty(): Promise<LongStream | null>;
    // ================== Method empty ==================
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static emptySync(): LongStream | null;
    // ================== Method filter ==================
    /**
     * @param var0 original type: 'java.util.function.LongPredicate'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public filter(var0: java_util_function_LongPredicate | null): Promise<LongStream | null>;
    // ================== Method filter ==================
    /**
     * @param var0 original type: 'java.util.function.LongPredicate'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public filterSync(var0: java_util_function_LongPredicate | null): LongStream | null;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static range(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): Promise<LongStream | null>;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public static rangeSync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): LongStream | null;
    // ================== Method parallel ==================
    /**
     * @return original return type: 'java.util.stream.BaseStream'
     */
    public parallel(): Promise<java_util_stream_BaseStream | null>;
    // ================== Method parallel ==================
    /**
     * @return original return type: 'java.util.stream.BaseStream'
     */
    public parallelSync(): java_util_stream_BaseStream | null;
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public parallel(): Promise<LongStream | null>;
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    public parallelSync(): LongStream | null;
    // ================== Method map ==================
    /**
     * @param var0 original type: 'java.util.function.LongUnaryOperator'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public map(var0: java_util_function_LongUnaryOperator | null): Promise<LongStream | null>;
    // ================== Method map ==================
    /**
     * @param var0 original type: 'java.util.function.LongUnaryOperator'
     * @return original return type: 'java.util.stream.LongStream'
     */
    public mapSync(var0: java_util_function_LongUnaryOperator | null): LongStream | null;
    // ================== Method reduce ==================
    /**
     * @param var0 original type: 'java.util.function.LongBinaryOperator'
     * @return original return type: 'java.util.OptionalLong'
     */
    public reduce(var0: java_util_function_LongBinaryOperator | null): Promise<java_util_OptionalLong | null>;
    // ================== Method reduce ==================
    /**
     * @param var0 original type: 'java.util.function.LongBinaryOperator'
     * @return original return type: 'java.util.OptionalLong'
     */
    public reduceSync(var0: java_util_function_LongBinaryOperator | null): java_util_OptionalLong | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.util.function.LongBinaryOperator'
     * @return original return type: 'long'
     */
    public reduce(var0: java_lang_Long | bigint | number, var1: java_util_function_LongBinaryOperator | null): Promise<number>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.util.function.LongBinaryOperator'
     * @return original return type: 'long'
     */
    public reduceSync(var0: java_lang_Long | bigint | number, var1: java_util_function_LongBinaryOperator | null): number;
    // ================== Method isParallel ==================
    /**
     * @return original return type: 'boolean'
     */
    public isParallel(): Promise<boolean>;
    // ================== Method isParallel ==================
    /**
     * @return original return type: 'boolean'
     */
    public isParallelSync(): boolean;
    // ================== Method onClose ==================
    /**
     * @param var0 original type: 'java.lang.Runnable'
     * @return original return type: 'java.util.stream.BaseStream'
     */
    public onClose(var0: java_lang_Runnable | null): Promise<java_util_stream_BaseStream | null>;
    // ================== Method onClose ==================
    /**
     * @param var0 original type: 'java.lang.Runnable'
     * @return original return type: 'java.util.stream.BaseStream'
     */
    public onCloseSync(var0: java_lang_Runnable | null): java_util_stream_BaseStream | null;
    // ================== Method unordered ==================
    /**
     * @return original return type: 'java.util.stream.BaseStream'
     */
    public unordered(): Promise<java_util_stream_BaseStream | null>;
    // ================== Method unordered ==================
    /**
     * @return original return type: 'java.util.stream.BaseStream'
     */
    public unorderedSync(): java_util_stream_BaseStream | null;
    // ================== Method close ==================
    /**
     * @return original return type: 'void'
     */
    public close(): Promise<void>;
    // ================== Method close ==================
    /**
     * @return original return type: 'void'
     */
    public closeSync(): void;
}

/**
 * Class java.util.stream.LongStream.
 *
 * This actually imports the java class for further use.
 * The class LongStreamClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class LongStream extends importClass<typeof LongStreamClass>("java.util.stream.LongStream") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default LongStream;