import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Long as java_lang_Long } from "./../../lang/Long";
import { Thread as java_lang_Thread } from "./../../lang/Thread";
import { Enum as java_lang_Enum } from "./../../lang/Enum";
import { Class as java_lang_Class } from "./../../lang/Class";
import { Integer as java_lang_Integer } from "./../../lang/Integer";

/**
 * This class just defines types, you should import TimeUnit instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class TimeUnitClass extends JavaClass {
    // ================== Field NANOSECONDS ==================
    /**
     * Original type: 'java.util.concurrent.TimeUnit'
     */
    public static readonly NANOSECONDS: TimeUnitClass | null;
    // ================== Field MICROSECONDS ==================
    /**
     * Original type: 'java.util.concurrent.TimeUnit'
     */
    public static readonly MICROSECONDS: TimeUnitClass | null;
    // ================== Field MILLISECONDS ==================
    /**
     * Original type: 'java.util.concurrent.TimeUnit'
     */
    public static readonly MILLISECONDS: TimeUnitClass | null;
    // ================== Field SECONDS ==================
    /**
     * Original type: 'java.util.concurrent.TimeUnit'
     */
    public static readonly SECONDS: TimeUnitClass | null;
    // ================== Field MINUTES ==================
    /**
     * Original type: 'java.util.concurrent.TimeUnit'
     */
    public static readonly MINUTES: TimeUnitClass | null;
    // ================== Field HOURS ==================
    /**
     * Original type: 'java.util.concurrent.TimeUnit'
     */
    public static readonly HOURS: TimeUnitClass | null;
    // ================== Field DAYS ==================
    /**
     * Original type: 'java.util.concurrent.TimeUnit'
     */
    public static readonly DAYS: TimeUnitClass | null;
    // ================== Method convert ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.util.concurrent.TimeUnit'
     * @return original return type: 'long'
     */
    public convert(var0: java_lang_Long | bigint | number, var1: TimeUnitClass | null): Promise<number>;
    // ================== Method convert ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.util.concurrent.TimeUnit'
     * @return original return type: 'long'
     */
    public convertSync(var0: java_lang_Long | bigint | number, var1: TimeUnitClass | null): number;
    // ================== Method toMicros ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toMicros(var0: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method toMicros ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toMicrosSync(var0: java_lang_Long | bigint | number): number;
    // ================== Method toSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toSeconds(var0: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method toSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toSecondsSync(var0: java_lang_Long | bigint | number): number;
    // ================== Method toMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toMinutes(var0: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method toMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toMinutesSync(var0: java_lang_Long | bigint | number): number;
    // ================== Method toHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toHours(var0: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method toHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toHoursSync(var0: java_lang_Long | bigint | number): number;
    // ================== Method toDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toDays(var0: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method toDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toDaysSync(var0: java_lang_Long | bigint | number): number;
    // ================== Method timedWait ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'long'
     * @return original return type: 'void'
     */
    public timedWait(var0: BasicOrJavaType | null, var1: java_lang_Long | bigint | number): Promise<void>;
    // ================== Method timedWait ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'long'
     * @return original return type: 'void'
     */
    public timedWaitSync(var0: BasicOrJavaType | null, var1: java_lang_Long | bigint | number): void;
    // ================== Method timedJoin ==================
    /**
     * @param var0 original type: 'java.lang.Thread'
     * @param var1 original type: 'long'
     * @return original return type: 'void'
     */
    public timedJoin(var0: java_lang_Thread | null, var1: java_lang_Long | bigint | number): Promise<void>;
    // ================== Method timedJoin ==================
    /**
     * @param var0 original type: 'java.lang.Thread'
     * @param var1 original type: 'long'
     * @return original return type: 'void'
     */
    public timedJoinSync(var0: java_lang_Thread | null, var1: java_lang_Long | bigint | number): void;
    // ================== Method toNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toNanos(var0: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method toNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toNanosSync(var0: java_lang_Long | bigint | number): number;
    // ================== Method toMillis ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toMillis(var0: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method toMillis ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    public toMillisSync(var0: java_lang_Long | bigint | number): number;
    // ================== Method values ==================
    /**
     * @return original return type: 'java.util.concurrent.TimeUnit[]'
     */
    public static values(): Promise<(TimeUnit | null)[] | null>;
    // ================== Method values ==================
    /**
     * @return original return type: 'java.util.concurrent.TimeUnit[]'
     */
    public static valuesSync(): (TimeUnit | null)[] | null;
    // ================== Method valueOf ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.concurrent.TimeUnit'
     */
    public static valueOf(var0: string | null): Promise<TimeUnit | null>;
    // ================== Method valueOf ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.concurrent.TimeUnit'
     */
    public static valueOfSync(var0: string | null): TimeUnit | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    public static valueOf(var0: java_lang_Class | null, var1: string | null): Promise<java_lang_Enum | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    public static valueOfSync(var0: java_lang_Class | null, var1: string | null): java_lang_Enum | null;
    // ================== Method sleep ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public sleep(var0: java_lang_Long | bigint | number): Promise<void>;
    // ================== Method sleep ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public sleepSync(var0: java_lang_Long | bigint | number): void;
    // ================== Method name ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public name(): Promise<string | null>;
    // ================== Method name ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public nameSync(): string | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    public compareTo(var0: java_lang_Enum | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    public compareToSync(var0: java_lang_Enum | null): number;
    // ================== Method getDeclaringClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getDeclaringClass(): Promise<java_lang_Class | null>;
    // ================== Method getDeclaringClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getDeclaringClassSync(): java_lang_Class | null;
    // ================== Method ordinal ==================
    /**
     * @return original return type: 'int'
     */
    public ordinal(): Promise<number>;
    // ================== Method ordinal ==================
    /**
     * @return original return type: 'int'
     */
    public ordinalSync(): number;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.util.concurrent.TimeUnit.
 *
 * This actually imports the java class for further use.
 * The class TimeUnitClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class TimeUnit extends importClass<typeof TimeUnitClass>("java.util.concurrent.TimeUnit") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default TimeUnit;