import { importClass, JavaClass } from "java-bridge";
import { File as java_io_File } from "./File";

/**
 * This class just defines types, you should import FileFilter instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FileFilterClass extends JavaClass {
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'java.io.File'
     * @return original return type: 'boolean'
     */
    public accept(var0: java_io_File | null): Promise<boolean>;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'java.io.File'
     * @return original return type: 'boolean'
     */
    public acceptSync(var0: java_io_File | null): boolean;
}

/**
 * Class java.io.FileFilter.
 *
 * This actually imports the java class for further use.
 * The class FileFilterClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class FileFilter extends importClass<typeof FileFilterClass>("java.io.FileFilter") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default FileFilter;