import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Double as java_lang_Double } from "./../lang/Double";
import { Float as java_lang_Float } from "./../lang/Float";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Boolean as java_lang_Boolean } from "./../lang/Boolean";
import { Long as java_lang_Long } from "./../lang/Long";
import { CharSequence as java_lang_CharSequence } from "./../lang/CharSequence";
import { Appendable as java_lang_Appendable } from "./../lang/Appendable";
import { Writer as java_io_Writer } from "./Writer";
import { Locale as java_util_Locale } from "./../util/Locale";
import { Class as java_lang_Class } from "./../lang/Class";
import { OutputStream as java_io_OutputStream } from "./OutputStream";
import { File as java_io_File } from "./File";

/**
 * This class just defines types, you should import PrintWriter instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PrintWriterClass extends JavaClass {
    // ================== Method println ==================
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'void'
     */
    public println(var0: java_lang_Double | number): Promise<void>;
    // ================== Method println ==================
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'void'
     */
    public printlnSync(var0: java_lang_Double | number): void;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'void'
     */
    public println(var0: (string | null)[] | null): Promise<void>;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'void'
     */
    public printlnSync(var0: (string | null)[] | null): void;
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'void'
     */
    public println(var0: java_lang_Float | number): Promise<void>;
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'void'
     */
    public printlnSync(var0: java_lang_Float | number): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public println(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public printlnSync(var0: string | null): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public println(var0: BasicOrJavaType | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public printlnSync(var0: BasicOrJavaType | null): void;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public println(var0: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public printlnSync(var0: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'void'
     */
    public println(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'void'
     */
    public printlnSync(var0: string | null): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public println(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public printlnSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'void'
     */
    public println(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public printlnSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public println(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public printlnSync(var0: java_lang_Long | bigint | number): void;
    // ================== Method append ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.io.PrintWriter'
     */
    public append(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<PrintWriter | null>;
    // ================== Method append ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.io.PrintWriter'
     */
    public appendSync(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): PrintWriter | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.io.PrintWriter'
     */
    public append(var0: java_lang_CharSequence | null): Promise<PrintWriter | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.io.PrintWriter'
     */
    public appendSync(var0: java_lang_CharSequence | null): PrintWriter | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: java_lang_CharSequence | null): Promise<java_lang_Appendable | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: java_lang_CharSequence | null): java_lang_Appendable | null;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: string | null): Promise<java_lang_Appendable | null>;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: string | null): java_lang_Appendable | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.io.Writer'
     */
    public append(var0: java_lang_CharSequence | null): Promise<java_io_Writer | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.io.Writer'
     */
    public appendSync(var0: java_lang_CharSequence | null): java_io_Writer | null;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.io.Writer'
     */
    public append(var0: string | null): Promise<java_io_Writer | null>;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.io.Writer'
     */
    public appendSync(var0: string | null): java_io_Writer | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.io.Writer'
     */
    public append(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_io_Writer | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.io.Writer'
     */
    public appendSync(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_io_Writer | null;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.io.PrintWriter'
     */
    public append(var0: string | null): Promise<PrintWriter | null>;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.io.PrintWriter'
     */
    public appendSync(var0: string | null): PrintWriter | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_lang_Appendable | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_lang_Appendable | null;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.util.Locale'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Object[]'
     * @return original return type: 'java.io.PrintWriter'
     */
    public format(var0: java_util_Locale | null, var1: string | null, var2: (BasicOrJavaType | null)[] | null): Promise<PrintWriter | null>;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.util.Locale'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Object[]'
     * @return original return type: 'java.io.PrintWriter'
     */
    public formatSync(var0: java_util_Locale | null, var1: string | null, var2: (BasicOrJavaType | null)[] | null): PrintWriter | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object[]'
     * @return original return type: 'java.io.PrintWriter'
     */
    public format(var0: string | null, var1: (BasicOrJavaType | null)[] | null): Promise<PrintWriter | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object[]'
     * @return original return type: 'java.io.PrintWriter'
     */
    public formatSync(var0: string | null, var1: (BasicOrJavaType | null)[] | null): PrintWriter | null;
    // ================== Method write ==================
    /**
     * @param var0 original type: 'char[]'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    public write(var0: (string | null)[] | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<void>;
    // ================== Method write ==================
    /**
     * @param var0 original type: 'char[]'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    public writeSync(var0: (string | null)[] | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    public write(var0: string | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    public writeSync(var0: string | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'void'
     */
    public write(var0: (string | null)[] | null): Promise<void>;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'void'
     */
    public writeSync(var0: (string | null)[] | null): void;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public write(var0: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public writeSync(var0: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public write(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public writeSync(var0: string | null): void;
    // ================== Method print ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'void'
     */
    public print(var0: java_lang_Float | number): Promise<void>;
    // ================== Method print ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'void'
     */
    public printSync(var0: java_lang_Float | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public print(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public printSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public print(var0: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public printSync(var0: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'void'
     */
    public print(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'void'
     */
    public printSync(var0: string | null): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public print(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public printSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public print(var0: BasicOrJavaType | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public printSync(var0: BasicOrJavaType | null): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public print(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public printSync(var0: string | null): void;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'void'
     */
    public print(var0: (string | null)[] | null): Promise<void>;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'void'
     */
    public printSync(var0: (string | null)[] | null): void;
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'void'
     */
    public print(var0: java_lang_Double | number): Promise<void>;
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'void'
     */
    public printSync(var0: java_lang_Double | number): void;
    // ================== Method flush ==================
    /**
     * @return original return type: 'void'
     */
    public flush(): Promise<void>;
    // ================== Method flush ==================
    /**
     * @return original return type: 'void'
     */
    public flushSync(): void;
    // ================== Method close ==================
    /**
     * @return original return type: 'void'
     */
    public close(): Promise<void>;
    // ================== Method close ==================
    /**
     * @return original return type: 'void'
     */
    public closeSync(): void;
    // ================== Method checkError ==================
    /**
     * @return original return type: 'boolean'
     */
    public checkError(): Promise<boolean>;
    // ================== Method checkError ==================
    /**
     * @return original return type: 'boolean'
     */
    public checkErrorSync(): boolean;
    // ================== Method printf ==================
    /**
     * @param var0 original type: 'java.util.Locale'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Object[]'
     * @return original return type: 'java.io.PrintWriter'
     */
    public printf(var0: java_util_Locale | null, var1: string | null, var2: (BasicOrJavaType | null)[] | null): Promise<PrintWriter | null>;
    // ================== Method printf ==================
    /**
     * @param var0 original type: 'java.util.Locale'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Object[]'
     * @return original return type: 'java.io.PrintWriter'
     */
    public printfSync(var0: java_util_Locale | null, var1: string | null, var2: (BasicOrJavaType | null)[] | null): PrintWriter | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object[]'
     * @return original return type: 'java.io.PrintWriter'
     */
    public printf(var0: string | null, var1: (BasicOrJavaType | null)[] | null): Promise<PrintWriter | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object[]'
     * @return original return type: 'java.io.PrintWriter'
     */
    public printfSync(var0: string | null, var1: (BasicOrJavaType | null)[] | null): PrintWriter | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method newInstance ==================
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.io.PrintWriter'
     */
    public static newInstance(var0: java_io_OutputStream | null, var1: java_lang_Boolean | boolean): Promise<PrintWriter>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.io.PrintWriter'
     */
    public static newInstance(var0: string | null): Promise<PrintWriter>;
    /**
     * @param var0 original type: 'java.io.File'
     * @return original return type: 'java.io.PrintWriter'
     */
    public static newInstance(var0: java_io_File | null): Promise<PrintWriter>;
    /**
     * @param var0 original type: 'java.io.File'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.io.PrintWriter'
     */
    public static newInstance(var0: java_io_File | null, var1: string | null): Promise<PrintWriter>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.io.PrintWriter'
     */
    public static newInstance(var0: string | null, var1: string | null): Promise<PrintWriter>;
    /**
     * @param var0 original type: 'java.io.Writer'
     * @return original return type: 'java.io.PrintWriter'
     */
    public static newInstance(var0: java_io_Writer | null): Promise<PrintWriter>;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @return original return type: 'java.io.PrintWriter'
     */
    public static newInstance(var0: java_io_OutputStream | null): Promise<PrintWriter>;
    /**
     * @param var0 original type: 'java.io.Writer'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.io.PrintWriter'
     */
    public static newInstance(var0: java_io_Writer | null, var1: java_lang_Boolean | boolean): Promise<PrintWriter>;
    // ================== Constructors ==================
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @param var1 original type: 'boolean'
     */
    public constructor(var0: java_io_OutputStream | null, var1: java_lang_Boolean | boolean);
    /**
     * @param var0 original type: 'java.lang.String'
     */
    public constructor(var0: string | null);
    /**
     * @param var0 original type: 'java.io.File'
     */
    public constructor(var0: java_io_File | null);
    /**
     * @param var0 original type: 'java.io.File'
     * @param var1 original type: 'java.lang.String'
     */
    public constructor(var0: java_io_File | null, var1: string | null);
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     */
    public constructor(var0: string | null, var1: string | null);
    /**
     * @param var0 original type: 'java.io.Writer'
     */
    public constructor(var0: java_io_Writer | null);
    /**
     * @param var0 original type: 'java.io.OutputStream'
     */
    public constructor(var0: java_io_OutputStream | null);
    /**
     * @param var0 original type: 'java.io.Writer'
     * @param var1 original type: 'boolean'
     */
    public constructor(var0: java_io_Writer | null, var1: java_lang_Boolean | boolean);
}

/**
 * Class java.io.PrintWriter.
 *
 * This actually imports the java class for further use.
 * The class PrintWriterClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class PrintWriter extends importClass<typeof PrintWriterClass>("java.io.PrintWriter") {
}
export default PrintWriter;