import { importClass, JavaClass } from "java-bridge";
import { ContentHandler as java_net_ContentHandler } from "./ContentHandler";

/**
 * This class just defines types, you should import ContentHandlerFactory instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ContentHandlerFactoryClass extends JavaClass {
    // ================== Method createContentHandler ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.net.ContentHandler'
     */
    public createContentHandler(var0: string | null): Promise<java_net_ContentHandler | null>;
    // ================== Method createContentHandler ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.net.ContentHandler'
     */
    public createContentHandlerSync(var0: string | null): java_net_ContentHandler | null;
}

/**
 * Class java.net.ContentHandlerFactory.
 *
 * This actually imports the java class for further use.
 * The class ContentHandlerFactoryClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class ContentHandlerFactory extends importClass<typeof ContentHandlerFactoryClass>("java.net.ContentHandlerFactory") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default ContentHandlerFactory;