import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Enumeration as java_util_Enumeration } from "./../util/Enumeration";
import { List as java_util_List } from "./../util/List";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { InetAddress as java_net_InetAddress } from "./InetAddress";
import { Long as java_lang_Long } from "./../lang/Long";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import NetworkInterface instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class NetworkInterfaceClass extends JavaClass {
    // ================== Method getNetworkInterfaces ==================
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    public static getNetworkInterfaces(): Promise<java_util_Enumeration | null>;
    // ================== Method getNetworkInterfaces ==================
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    public static getNetworkInterfacesSync(): java_util_Enumeration | null;
    // ================== Method getInetAddresses ==================
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    public getInetAddresses(): Promise<java_util_Enumeration | null>;
    // ================== Method getInetAddresses ==================
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    public getInetAddressesSync(): java_util_Enumeration | null;
    // ================== Method getInterfaceAddresses ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getInterfaceAddresses(): Promise<java_util_List | null>;
    // ================== Method getInterfaceAddresses ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getInterfaceAddressesSync(): java_util_List | null;
    // ================== Method getSubInterfaces ==================
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    public getSubInterfaces(): Promise<java_util_Enumeration | null>;
    // ================== Method getSubInterfaces ==================
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    public getSubInterfacesSync(): java_util_Enumeration | null;
    // ================== Method getByIndex ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.net.NetworkInterface'
     */
    public static getByIndex(var0: java_lang_Integer | number): Promise<NetworkInterface | null>;
    // ================== Method getByIndex ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.net.NetworkInterface'
     */
    public static getByIndexSync(var0: java_lang_Integer | number): NetworkInterface | null;
    // ================== Method getByInetAddress ==================
    /**
     * @param var0 original type: 'java.net.InetAddress'
     * @return original return type: 'java.net.NetworkInterface'
     */
    public static getByInetAddress(var0: java_net_InetAddress | null): Promise<NetworkInterface | null>;
    // ================== Method getByInetAddress ==================
    /**
     * @param var0 original type: 'java.net.InetAddress'
     * @return original return type: 'java.net.NetworkInterface'
     */
    public static getByInetAddressSync(var0: java_net_InetAddress | null): NetworkInterface | null;
    // ================== Method isUp ==================
    /**
     * @return original return type: 'boolean'
     */
    public isUp(): Promise<boolean>;
    // ================== Method isUp ==================
    /**
     * @return original return type: 'boolean'
     */
    public isUpSync(): boolean;
    // ================== Method isLoopback ==================
    /**
     * @return original return type: 'boolean'
     */
    public isLoopback(): Promise<boolean>;
    // ================== Method isLoopback ==================
    /**
     * @return original return type: 'boolean'
     */
    public isLoopbackSync(): boolean;
    // ================== Method isPointToPoint ==================
    /**
     * @return original return type: 'boolean'
     */
    public isPointToPoint(): Promise<boolean>;
    // ================== Method isPointToPoint ==================
    /**
     * @return original return type: 'boolean'
     */
    public isPointToPointSync(): boolean;
    // ================== Method supportsMulticast ==================
    /**
     * @return original return type: 'boolean'
     */
    public supportsMulticast(): Promise<boolean>;
    // ================== Method supportsMulticast ==================
    /**
     * @return original return type: 'boolean'
     */
    public supportsMulticastSync(): boolean;
    // ================== Method getHardwareAddress ==================
    /**
     * @return original return type: 'byte[]'
     */
    public getHardwareAddress(): Promise<Buffer | null>;
    // ================== Method getHardwareAddress ==================
    /**
     * @return original return type: 'byte[]'
     */
    public getHardwareAddressSync(): Buffer | null;
    // ================== Method getMTU ==================
    /**
     * @return original return type: 'int'
     */
    public getMTU(): Promise<number>;
    // ================== Method getMTU ==================
    /**
     * @return original return type: 'int'
     */
    public getMTUSync(): number;
    // ================== Method isVirtual ==================
    /**
     * @return original return type: 'boolean'
     */
    public isVirtual(): Promise<boolean>;
    // ================== Method isVirtual ==================
    /**
     * @return original return type: 'boolean'
     */
    public isVirtualSync(): boolean;
    // ================== Method getIndex ==================
    /**
     * @return original return type: 'int'
     */
    public getIndex(): Promise<number>;
    // ================== Method getIndex ==================
    /**
     * @return original return type: 'int'
     */
    public getIndexSync(): number;
    // ================== Method getByName ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.net.NetworkInterface'
     */
    public static getByName(var0: string | null): Promise<NetworkInterface | null>;
    // ================== Method getByName ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.net.NetworkInterface'
     */
    public static getByNameSync(var0: string | null): NetworkInterface | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getName(): Promise<string | null>;
    // ================== Method getName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getNameSync(): string | null;
    // ================== Method getParent ==================
    /**
     * @return original return type: 'java.net.NetworkInterface'
     */
    public getParent(): Promise<NetworkInterface | null>;
    // ================== Method getParent ==================
    /**
     * @return original return type: 'java.net.NetworkInterface'
     */
    public getParentSync(): NetworkInterface | null;
    // ================== Method getDisplayName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getDisplayName(): Promise<string | null>;
    // ================== Method getDisplayName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getDisplayNameSync(): string | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.net.NetworkInterface.
 *
 * This actually imports the java class for further use.
 * The class NetworkInterfaceClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class NetworkInterface extends importClass<typeof NetworkInterfaceClass>("java.net.NetworkInterface") {
}
export default NetworkInterface;