import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import PasswordAuthentication instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PasswordAuthenticationClass extends JavaClass {
    // ================== Method getUserName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getUserName(): Promise<string | null>;
    // ================== Method getUserName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getUserNameSync(): string | null;
    // ================== Method getPassword ==================
    /**
     * @return original return type: 'char[]'
     */
    public getPassword(): Promise<(string | null)[] | null>;
    // ================== Method getPassword ==================
    /**
     * @return original return type: 'char[]'
     */
    public getPasswordSync(): (string | null)[] | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method newInstance ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'char[]'
     * @return original return type: 'java.net.PasswordAuthentication'
     */
    public static newInstance(var0: string | null, var1: (string | null)[] | null): Promise<PasswordAuthentication>;
    // ================== Constructors ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'char[]'
     */
    public constructor(var0: string | null, var1: (string | null)[] | null);
}

/**
 * Class java.net.PasswordAuthentication.
 *
 * This actually imports the java class for further use.
 * The class PasswordAuthenticationClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class PasswordAuthentication extends importClass<typeof PasswordAuthenticationClass>("java.net.PasswordAuthentication") {
}
export default PasswordAuthentication;