import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Proxy$Type as java_net_Proxy$Type } from "./Proxy$Type";
import { SocketAddress as java_net_SocketAddress } from "./SocketAddress";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import Proxy instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ProxyClass extends JavaClass {
    // ================== Field NO_PROXY ==================
    /**
     * Original type: 'java.net.Proxy'
     */
    public static readonly NO_PROXY: ProxyClass | null;
    // ================== Method type ==================
    /**
     * @return original return type: 'java.net.Proxy$Type'
     */
    public type(): Promise<java_net_Proxy$Type | null>;
    // ================== Method type ==================
    /**
     * @return original return type: 'java.net.Proxy$Type'
     */
    public typeSync(): java_net_Proxy$Type | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method address ==================
    /**
     * @return original return type: 'java.net.SocketAddress'
     */
    public address(): Promise<java_net_SocketAddress | null>;
    // ================== Method address ==================
    /**
     * @return original return type: 'java.net.SocketAddress'
     */
    public addressSync(): java_net_SocketAddress | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method newInstance ==================
    /**
     * @param var0 original type: 'java.net.Proxy$Type'
     * @param var1 original type: 'java.net.SocketAddress'
     * @return original return type: 'java.net.Proxy'
     */
    public static newInstance(var0: java_net_Proxy$Type | null, var1: java_net_SocketAddress | null): Promise<Proxy>;
    // ================== Constructors ==================
    /**
     * @param var0 original type: 'java.net.Proxy$Type'
     * @param var1 original type: 'java.net.SocketAddress'
     */
    public constructor(var0: java_net_Proxy$Type | null, var1: java_net_SocketAddress | null);
}

/**
 * Class java.net.Proxy.
 *
 * This actually imports the java class for further use.
 * The class ProxyClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Proxy extends importClass<typeof ProxyClass>("java.net.Proxy") {
}
export default Proxy;