import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Boolean as java_lang_Boolean } from "./../lang/Boolean";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { FileNameMap as java_net_FileNameMap } from "./FileNameMap";
import { Map as java_util_Map } from "./../util/Map";
import { InputStream as java_io_InputStream } from "./../io/InputStream";
import { Long as java_lang_Long } from "./../lang/Long";
import { OutputStream as java_io_OutputStream } from "./../io/OutputStream";
import { ContentHandlerFactory as java_net_ContentHandlerFactory } from "./ContentHandlerFactory";
import { URL as java_net_URL } from "./URL";
import { Permission as java_security_Permission } from "./../security/Permission";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import URLConnection instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class URLConnectionClass extends JavaClass {
    // ================== Method setRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public setRequestProperty(var0: string | null, var1: string | null): Promise<void>;
    // ================== Method setRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public setRequestPropertySync(var0: string | null, var1: string | null): void;
    // ================== Method setUseCaches ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setUseCaches(var0: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setUseCaches ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setUseCachesSync(var0: java_lang_Boolean | boolean): void;
    // ================== Method getContentLength ==================
    /**
     * @return original return type: 'int'
     */
    public getContentLength(): Promise<number>;
    // ================== Method getContentLength ==================
    /**
     * @return original return type: 'int'
     */
    public getContentLengthSync(): number;
    // ================== Method getHeaderField ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    public getHeaderField(var0: string | null): Promise<string | null>;
    // ================== Method getHeaderField ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    public getHeaderFieldSync(var0: string | null): string | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.lang.String'
     */
    public getHeaderField(var0: java_lang_Integer | number): Promise<string | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.lang.String'
     */
    public getHeaderFieldSync(var0: java_lang_Integer | number): string | null;
    // ================== Method getContentLengthLong ==================
    /**
     * @return original return type: 'long'
     */
    public getContentLengthLong(): Promise<number>;
    // ================== Method getContentLengthLong ==================
    /**
     * @return original return type: 'long'
     */
    public getContentLengthLongSync(): number;
    // ================== Method getHeaderFieldKey ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.lang.String'
     */
    public getHeaderFieldKey(var0: java_lang_Integer | number): Promise<string | null>;
    // ================== Method getHeaderFieldKey ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.lang.String'
     */
    public getHeaderFieldKeySync(var0: java_lang_Integer | number): string | null;
    // ================== Method getLastModified ==================
    /**
     * @return original return type: 'long'
     */
    public getLastModified(): Promise<number>;
    // ================== Method getLastModified ==================
    /**
     * @return original return type: 'long'
     */
    public getLastModifiedSync(): number;
    // ================== Method getFileNameMap ==================
    /**
     * @return original return type: 'java.net.FileNameMap'
     */
    public static getFileNameMap(): Promise<java_net_FileNameMap | null>;
    // ================== Method getFileNameMap ==================
    /**
     * @return original return type: 'java.net.FileNameMap'
     */
    public static getFileNameMapSync(): java_net_FileNameMap | null;
    // ================== Method addRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public addRequestProperty(var0: string | null, var1: string | null): Promise<void>;
    // ================== Method addRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public addRequestPropertySync(var0: string | null, var1: string | null): void;
    // ================== Method getRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    public getRequestProperty(var0: string | null): Promise<string | null>;
    // ================== Method getRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    public getRequestPropertySync(var0: string | null): string | null;
    // ================== Method getRequestProperties ==================
    /**
     * @return original return type: 'java.util.Map'
     */
    public getRequestProperties(): Promise<java_util_Map | null>;
    // ================== Method getRequestProperties ==================
    /**
     * @return original return type: 'java.util.Map'
     */
    public getRequestPropertiesSync(): java_util_Map | null;
    // ================== Method getContentType ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getContentType(): Promise<string | null>;
    // ================== Method getContentType ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getContentTypeSync(): string | null;
    // ================== Method guessContentTypeFromStream ==================
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'java.lang.String'
     */
    public static guessContentTypeFromStream(var0: java_io_InputStream | null): Promise<string | null>;
    // ================== Method guessContentTypeFromStream ==================
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'java.lang.String'
     */
    public static guessContentTypeFromStreamSync(var0: java_io_InputStream | null): string | null;
    // ================== Method guessContentTypeFromName ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    public static guessContentTypeFromName(var0: string | null): Promise<string | null>;
    // ================== Method guessContentTypeFromName ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    public static guessContentTypeFromNameSync(var0: string | null): string | null;
    // ================== Method setFileNameMap ==================
    /**
     * @param var0 original type: 'java.net.FileNameMap'
     * @return original return type: 'void'
     */
    public static setFileNameMap(var0: java_net_FileNameMap | null): Promise<void>;
    // ================== Method setFileNameMap ==================
    /**
     * @param var0 original type: 'java.net.FileNameMap'
     * @return original return type: 'void'
     */
    public static setFileNameMapSync(var0: java_net_FileNameMap | null): void;
    // ================== Method setConnectTimeout ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setConnectTimeout(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method setConnectTimeout ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setConnectTimeoutSync(var0: java_lang_Integer | number): void;
    // ================== Method getConnectTimeout ==================
    /**
     * @return original return type: 'int'
     */
    public getConnectTimeout(): Promise<number>;
    // ================== Method getConnectTimeout ==================
    /**
     * @return original return type: 'int'
     */
    public getConnectTimeoutSync(): number;
    // ================== Method setReadTimeout ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setReadTimeout(var0: java_lang_Integer | number): Promise<void>;
    // ================== Method setReadTimeout ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    public setReadTimeoutSync(var0: java_lang_Integer | number): void;
    // ================== Method getReadTimeout ==================
    /**
     * @return original return type: 'int'
     */
    public getReadTimeout(): Promise<number>;
    // ================== Method getReadTimeout ==================
    /**
     * @return original return type: 'int'
     */
    public getReadTimeoutSync(): number;
    // ================== Method getContentEncoding ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getContentEncoding(): Promise<string | null>;
    // ================== Method getContentEncoding ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getContentEncodingSync(): string | null;
    // ================== Method getExpiration ==================
    /**
     * @return original return type: 'long'
     */
    public getExpiration(): Promise<number>;
    // ================== Method getExpiration ==================
    /**
     * @return original return type: 'long'
     */
    public getExpirationSync(): number;
    // ================== Method getDate ==================
    /**
     * @return original return type: 'long'
     */
    public getDate(): Promise<number>;
    // ================== Method getDate ==================
    /**
     * @return original return type: 'long'
     */
    public getDateSync(): number;
    // ================== Method getHeaderFields ==================
    /**
     * @return original return type: 'java.util.Map'
     */
    public getHeaderFields(): Promise<java_util_Map | null>;
    // ================== Method getHeaderFields ==================
    /**
     * @return original return type: 'java.util.Map'
     */
    public getHeaderFieldsSync(): java_util_Map | null;
    // ================== Method getHeaderFieldInt ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'int'
     * @return original return type: 'int'
     */
    public getHeaderFieldInt(var0: string | null, var1: java_lang_Integer | number): Promise<number>;
    // ================== Method getHeaderFieldInt ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'int'
     * @return original return type: 'int'
     */
    public getHeaderFieldIntSync(var0: string | null, var1: java_lang_Integer | number): number;
    // ================== Method getHeaderFieldLong ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    public getHeaderFieldLong(var0: string | null, var1: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method getHeaderFieldLong ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    public getHeaderFieldLongSync(var0: string | null, var1: java_lang_Long | bigint | number): number;
    // ================== Method getHeaderFieldDate ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    public getHeaderFieldDate(var0: string | null, var1: java_lang_Long | bigint | number): Promise<number>;
    // ================== Method getHeaderFieldDate ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    public getHeaderFieldDateSync(var0: string | null, var1: java_lang_Long | bigint | number): number;
    // ================== Method getOutputStream ==================
    /**
     * @return original return type: 'java.io.OutputStream'
     */
    public getOutputStream(): Promise<java_io_OutputStream | null>;
    // ================== Method getOutputStream ==================
    /**
     * @return original return type: 'java.io.OutputStream'
     */
    public getOutputStreamSync(): java_io_OutputStream | null;
    // ================== Method setDoInput ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setDoInput(var0: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setDoInput ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setDoInputSync(var0: java_lang_Boolean | boolean): void;
    // ================== Method getDoInput ==================
    /**
     * @return original return type: 'boolean'
     */
    public getDoInput(): Promise<boolean>;
    // ================== Method getDoInput ==================
    /**
     * @return original return type: 'boolean'
     */
    public getDoInputSync(): boolean;
    // ================== Method setDoOutput ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setDoOutput(var0: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setDoOutput ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setDoOutputSync(var0: java_lang_Boolean | boolean): void;
    // ================== Method getDoOutput ==================
    /**
     * @return original return type: 'boolean'
     */
    public getDoOutput(): Promise<boolean>;
    // ================== Method getDoOutput ==================
    /**
     * @return original return type: 'boolean'
     */
    public getDoOutputSync(): boolean;
    // ================== Method setAllowUserInteraction ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setAllowUserInteraction(var0: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setAllowUserInteraction ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setAllowUserInteractionSync(var0: java_lang_Boolean | boolean): void;
    // ================== Method getAllowUserInteraction ==================
    /**
     * @return original return type: 'boolean'
     */
    public getAllowUserInteraction(): Promise<boolean>;
    // ================== Method getAllowUserInteraction ==================
    /**
     * @return original return type: 'boolean'
     */
    public getAllowUserInteractionSync(): boolean;
    // ================== Method setDefaultAllowUserInteraction ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public static setDefaultAllowUserInteraction(var0: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setDefaultAllowUserInteraction ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public static setDefaultAllowUserInteractionSync(var0: java_lang_Boolean | boolean): void;
    // ================== Method getDefaultAllowUserInteraction ==================
    /**
     * @return original return type: 'boolean'
     */
    public static getDefaultAllowUserInteraction(): Promise<boolean>;
    // ================== Method getDefaultAllowUserInteraction ==================
    /**
     * @return original return type: 'boolean'
     */
    public static getDefaultAllowUserInteractionSync(): boolean;
    // ================== Method getUseCaches ==================
    /**
     * @return original return type: 'boolean'
     */
    public getUseCaches(): Promise<boolean>;
    // ================== Method getUseCaches ==================
    /**
     * @return original return type: 'boolean'
     */
    public getUseCachesSync(): boolean;
    // ================== Method setIfModifiedSince ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public setIfModifiedSince(var0: java_lang_Long | bigint | number): Promise<void>;
    // ================== Method setIfModifiedSince ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public setIfModifiedSinceSync(var0: java_lang_Long | bigint | number): void;
    // ================== Method getIfModifiedSince ==================
    /**
     * @return original return type: 'long'
     */
    public getIfModifiedSince(): Promise<number>;
    // ================== Method getIfModifiedSince ==================
    /**
     * @return original return type: 'long'
     */
    public getIfModifiedSinceSync(): number;
    // ================== Method getDefaultUseCaches ==================
    /**
     * @return original return type: 'boolean'
     */
    public getDefaultUseCaches(): Promise<boolean>;
    // ================== Method getDefaultUseCaches ==================
    /**
     * @return original return type: 'boolean'
     */
    public getDefaultUseCachesSync(): boolean;
    // ================== Method setDefaultUseCaches ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setDefaultUseCaches(var0: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setDefaultUseCaches ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setDefaultUseCachesSync(var0: java_lang_Boolean | boolean): void;
    // ================== Method setDefaultRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public static setDefaultRequestProperty(var0: string | null, var1: string | null): Promise<void>;
    // ================== Method setDefaultRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public static setDefaultRequestPropertySync(var0: string | null, var1: string | null): void;
    // ================== Method getDefaultRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    public static getDefaultRequestProperty(var0: string | null): Promise<string | null>;
    // ================== Method getDefaultRequestProperty ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    public static getDefaultRequestPropertySync(var0: string | null): string | null;
    // ================== Method setContentHandlerFactory ==================
    /**
     * @param var0 original type: 'java.net.ContentHandlerFactory'
     * @return original return type: 'void'
     */
    public static setContentHandlerFactory(var0: java_net_ContentHandlerFactory | null): Promise<void>;
    // ================== Method setContentHandlerFactory ==================
    /**
     * @param var0 original type: 'java.net.ContentHandlerFactory'
     * @return original return type: 'void'
     */
    public static setContentHandlerFactorySync(var0: java_net_ContentHandlerFactory | null): void;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method getURL ==================
    /**
     * @return original return type: 'java.net.URL'
     */
    public getURL(): Promise<java_net_URL | null>;
    // ================== Method getURL ==================
    /**
     * @return original return type: 'java.net.URL'
     */
    public getURLSync(): java_net_URL | null;
    // ================== Method connect ==================
    /**
     * @return original return type: 'void'
     */
    public connect(): Promise<void>;
    // ================== Method connect ==================
    /**
     * @return original return type: 'void'
     */
    public connectSync(): void;
    // ================== Method getInputStream ==================
    /**
     * @return original return type: 'java.io.InputStream'
     */
    public getInputStream(): Promise<java_io_InputStream | null>;
    // ================== Method getInputStream ==================
    /**
     * @return original return type: 'java.io.InputStream'
     */
    public getInputStreamSync(): java_io_InputStream | null;
    // ================== Method getPermission ==================
    /**
     * @return original return type: 'java.security.Permission'
     */
    public getPermission(): Promise<java_security_Permission | null>;
    // ================== Method getPermission ==================
    /**
     * @return original return type: 'java.security.Permission'
     */
    public getPermissionSync(): java_security_Permission | null;
    // ================== Method getContent ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public getContent(): Promise<BasicOrJavaType | null>;
    // ================== Method getContent ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public getContentSync(): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.Class[]'
     * @return original return type: 'java.lang.Object'
     */
    public getContent(var0: (java_lang_Class | null)[] | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'java.lang.Class[]'
     * @return original return type: 'java.lang.Object'
     */
    public getContentSync(var0: (java_lang_Class | null)[] | null): BasicOrJavaType | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.net.URLConnection.
 *
 * This actually imports the java class for further use.
 * The class URLConnectionClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class URLConnection extends importClass<typeof URLConnectionClass>("java.net.URLConnection") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default URLConnection;