import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { PublicKey as java_security_PublicKey } from "./../PublicKey";
import { Provider as java_security_Provider } from "./../Provider";
import { Long as java_lang_Long } from "./../../lang/Long";
import { Integer as java_lang_Integer } from "./../../lang/Integer";
import { Class as java_lang_Class } from "./../../lang/Class";

/**
 * This class just defines types, you should import Certificate instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class CertificateClass extends JavaClass {
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getType ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getType(): Promise<string | null>;
    // ================== Method getType ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getTypeSync(): string | null;
    // ================== Method getEncoded ==================
    /**
     * @return original return type: 'byte[]'
     */
    public getEncoded(): Promise<Buffer | null>;
    // ================== Method getEncoded ==================
    /**
     * @return original return type: 'byte[]'
     */
    public getEncodedSync(): Buffer | null;
    // ================== Method verify ==================
    /**
     * @param var0 original type: 'java.security.PublicKey'
     * @param var1 original type: 'java.security.Provider'
     * @return original return type: 'void'
     */
    public verify(var0: java_security_PublicKey | null, var1: java_security_Provider | null): Promise<void>;
    // ================== Method verify ==================
    /**
     * @param var0 original type: 'java.security.PublicKey'
     * @param var1 original type: 'java.security.Provider'
     * @return original return type: 'void'
     */
    public verifySync(var0: java_security_PublicKey | null, var1: java_security_Provider | null): void;
    /**
     * @param var0 original type: 'java.security.PublicKey'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public verify(var0: java_security_PublicKey | null, var1: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.security.PublicKey'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    public verifySync(var0: java_security_PublicKey | null, var1: string | null): void;
    /**
     * @param var0 original type: 'java.security.PublicKey'
     * @return original return type: 'void'
     */
    public verify(var0: java_security_PublicKey | null): Promise<void>;
    /**
     * @param var0 original type: 'java.security.PublicKey'
     * @return original return type: 'void'
     */
    public verifySync(var0: java_security_PublicKey | null): void;
    // ================== Method getPublicKey ==================
    /**
     * @return original return type: 'java.security.PublicKey'
     */
    public getPublicKey(): Promise<java_security_PublicKey | null>;
    // ================== Method getPublicKey ==================
    /**
     * @return original return type: 'java.security.PublicKey'
     */
    public getPublicKeySync(): java_security_PublicKey | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.security.cert.Certificate.
 *
 * This actually imports the java class for further use.
 * The class CertificateClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Certificate extends importClass<typeof CertificateClass>("java.security.cert.Certificate") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default Certificate;