import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Set as java_util_Set } from "./../util/Set";
import { AttributedCharacterIterator$Attribute as java_text_AttributedCharacterIterator$Attribute } from "./AttributedCharacterIterator$Attribute";
import { Map as java_util_Map } from "./../util/Map";
import { Integer as java_lang_Integer } from "./../lang/Integer";

/**
 * This class just defines types, you should import AttributedCharacterIterator instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class AttributedCharacterIteratorClass extends JavaClass {
    // ================== Field DONE ==================
    /**
     * Original type: 'char'
     */
    public static readonly DONE: string | null;
    // ================== Method getRunStart ==================
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'int'
     */
    public getRunStart(var0: java_util_Set | null): Promise<number>;
    // ================== Method getRunStart ==================
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'int'
     */
    public getRunStartSync(var0: java_util_Set | null): number;
    /**
     * @param var0 original type: 'java.text.AttributedCharacterIterator$Attribute'
     * @return original return type: 'int'
     */
    public getRunStart(var0: java_text_AttributedCharacterIterator$Attribute | null): Promise<number>;
    /**
     * @param var0 original type: 'java.text.AttributedCharacterIterator$Attribute'
     * @return original return type: 'int'
     */
    public getRunStartSync(var0: java_text_AttributedCharacterIterator$Attribute | null): number;
    /**
     * @return original return type: 'int'
     */
    public getRunStart(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    public getRunStartSync(): number;
    // ================== Method getRunLimit ==================
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'int'
     */
    public getRunLimit(var0: java_util_Set | null): Promise<number>;
    // ================== Method getRunLimit ==================
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'int'
     */
    public getRunLimitSync(var0: java_util_Set | null): number;
    /**
     * @param var0 original type: 'java.text.AttributedCharacterIterator$Attribute'
     * @return original return type: 'int'
     */
    public getRunLimit(var0: java_text_AttributedCharacterIterator$Attribute | null): Promise<number>;
    /**
     * @param var0 original type: 'java.text.AttributedCharacterIterator$Attribute'
     * @return original return type: 'int'
     */
    public getRunLimitSync(var0: java_text_AttributedCharacterIterator$Attribute | null): number;
    /**
     * @return original return type: 'int'
     */
    public getRunLimit(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    public getRunLimitSync(): number;
    // ================== Method getAllAttributeKeys ==================
    /**
     * @return original return type: 'java.util.Set'
     */
    public getAllAttributeKeys(): Promise<java_util_Set | null>;
    // ================== Method getAllAttributeKeys ==================
    /**
     * @return original return type: 'java.util.Set'
     */
    public getAllAttributeKeysSync(): java_util_Set | null;
    // ================== Method getAttribute ==================
    /**
     * @param var0 original type: 'java.text.AttributedCharacterIterator$Attribute'
     * @return original return type: 'java.lang.Object'
     */
    public getAttribute(var0: java_text_AttributedCharacterIterator$Attribute | null): Promise<BasicOrJavaType | null>;
    // ================== Method getAttribute ==================
    /**
     * @param var0 original type: 'java.text.AttributedCharacterIterator$Attribute'
     * @return original return type: 'java.lang.Object'
     */
    public getAttributeSync(var0: java_text_AttributedCharacterIterator$Attribute | null): BasicOrJavaType | null;
    // ================== Method getAttributes ==================
    /**
     * @return original return type: 'java.util.Map'
     */
    public getAttributes(): Promise<java_util_Map | null>;
    // ================== Method getAttributes ==================
    /**
     * @return original return type: 'java.util.Map'
     */
    public getAttributesSync(): java_util_Map | null;
    // ================== Method getIndex ==================
    /**
     * @return original return type: 'int'
     */
    public getIndex(): Promise<number>;
    // ================== Method getIndex ==================
    /**
     * @return original return type: 'int'
     */
    public getIndexSync(): number;
    // ================== Method getBeginIndex ==================
    /**
     * @return original return type: 'int'
     */
    public getBeginIndex(): Promise<number>;
    // ================== Method getBeginIndex ==================
    /**
     * @return original return type: 'int'
     */
    public getBeginIndexSync(): number;
    // ================== Method getEndIndex ==================
    /**
     * @return original return type: 'int'
     */
    public getEndIndex(): Promise<number>;
    // ================== Method getEndIndex ==================
    /**
     * @return original return type: 'int'
     */
    public getEndIndexSync(): number;
    // ================== Method current ==================
    /**
     * @return original return type: 'char'
     */
    public current(): Promise<string | null>;
    // ================== Method current ==================
    /**
     * @return original return type: 'char'
     */
    public currentSync(): string | null;
    // ================== Method last ==================
    /**
     * @return original return type: 'char'
     */
    public last(): Promise<string | null>;
    // ================== Method last ==================
    /**
     * @return original return type: 'char'
     */
    public lastSync(): string | null;
    // ================== Method setIndex ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'char'
     */
    public setIndex(var0: java_lang_Integer | number): Promise<string | null>;
    // ================== Method setIndex ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'char'
     */
    public setIndexSync(var0: java_lang_Integer | number): string | null;
    // ================== Method clone ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public clone(): Promise<BasicOrJavaType | null>;
    // ================== Method clone ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public cloneSync(): BasicOrJavaType | null;
    // ================== Method next ==================
    /**
     * @return original return type: 'char'
     */
    public next(): Promise<string | null>;
    // ================== Method next ==================
    /**
     * @return original return type: 'char'
     */
    public nextSync(): string | null;
    // ================== Method first ==================
    /**
     * @return original return type: 'char'
     */
    public first(): Promise<string | null>;
    // ================== Method first ==================
    /**
     * @return original return type: 'char'
     */
    public firstSync(): string | null;
    // ================== Method previous ==================
    /**
     * @return original return type: 'char'
     */
    public previous(): Promise<string | null>;
    // ================== Method previous ==================
    /**
     * @return original return type: 'char'
     */
    public previousSync(): string | null;
}

/**
 * Class java.text.AttributedCharacterIterator.
 *
 * This actually imports the java class for further use.
 * The class AttributedCharacterIteratorClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class AttributedCharacterIterator extends importClass<typeof AttributedCharacterIteratorClass>("java.text.AttributedCharacterIterator") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default AttributedCharacterIterator;