import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { AttributedCharacterIterator as java_text_AttributedCharacterIterator } from "./AttributedCharacterIterator";
import { ParsePosition as java_text_ParsePosition } from "./ParsePosition";
import { StringBuffer as java_lang_StringBuffer } from "./../lang/StringBuffer";
import { FieldPosition as java_text_FieldPosition } from "./FieldPosition";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import Format instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FormatClass extends JavaClass {
    // ================== Method formatToCharacterIterator ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.text.AttributedCharacterIterator'
     */
    public formatToCharacterIterator(var0: BasicOrJavaType | null): Promise<java_text_AttributedCharacterIterator | null>;
    // ================== Method formatToCharacterIterator ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.text.AttributedCharacterIterator'
     */
    public formatToCharacterIteratorSync(var0: BasicOrJavaType | null): java_text_AttributedCharacterIterator | null;
    // ================== Method parseObject ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.text.ParsePosition'
     * @return original return type: 'java.lang.Object'
     */
    public parseObject(var0: string | null, var1: java_text_ParsePosition | null): Promise<BasicOrJavaType | null>;
    // ================== Method parseObject ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.text.ParsePosition'
     * @return original return type: 'java.lang.Object'
     */
    public parseObjectSync(var0: string | null, var1: java_text_ParsePosition | null): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    public parseObject(var0: string | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    public parseObjectSync(var0: string | null): BasicOrJavaType | null;
    // ================== Method clone ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public clone(): Promise<BasicOrJavaType | null>;
    // ================== Method clone ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public cloneSync(): BasicOrJavaType | null;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.lang.String'
     */
    public format(var0: BasicOrJavaType | null): Promise<string | null>;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'java.lang.String'
     */
    public formatSync(var0: BasicOrJavaType | null): string | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.lang.StringBuffer'
     * @param var2 original type: 'java.text.FieldPosition'
     * @return original return type: 'java.lang.StringBuffer'
     */
    public format(var0: BasicOrJavaType | null, var1: java_lang_StringBuffer | null, var2: java_text_FieldPosition | null): Promise<java_lang_StringBuffer | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.lang.StringBuffer'
     * @param var2 original type: 'java.text.FieldPosition'
     * @return original return type: 'java.lang.StringBuffer'
     */
    public formatSync(var0: BasicOrJavaType | null, var1: java_lang_StringBuffer | null, var2: java_text_FieldPosition | null): java_lang_StringBuffer | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.text.Format.
 *
 * This actually imports the java class for further use.
 * The class FormatClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Format extends importClass<typeof FormatClass>("java.text.Format") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default Format;