import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Comparator as java_util_Comparator } from "./../Comparator";
import { BiFunction as java_util_function_BiFunction } from "./BiFunction";
import { Function as java_util_function_Function } from "./Function";

/**
 * This class just defines types, you should import BinaryOperator instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BinaryOperatorClass extends JavaClass {
    // ================== Method minBy ==================
    /**
     * @param var0 original type: 'java.util.Comparator'
     * @return original return type: 'java.util.function.BinaryOperator'
     */
    public static minBy(var0: java_util_Comparator | null): Promise<BinaryOperator | null>;
    // ================== Method minBy ==================
    /**
     * @param var0 original type: 'java.util.Comparator'
     * @return original return type: 'java.util.function.BinaryOperator'
     */
    public static minBySync(var0: java_util_Comparator | null): BinaryOperator | null;
    // ================== Method maxBy ==================
    /**
     * @param var0 original type: 'java.util.Comparator'
     * @return original return type: 'java.util.function.BinaryOperator'
     */
    public static maxBy(var0: java_util_Comparator | null): Promise<BinaryOperator | null>;
    // ================== Method maxBy ==================
    /**
     * @param var0 original type: 'java.util.Comparator'
     * @return original return type: 'java.util.function.BinaryOperator'
     */
    public static maxBySync(var0: java_util_Comparator | null): BinaryOperator | null;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.Function'
     * @return original return type: 'java.util.function.BiFunction'
     */
    public andThen(var0: java_util_function_Function | null): Promise<java_util_function_BiFunction | null>;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.Function'
     * @return original return type: 'java.util.function.BiFunction'
     */
    public andThenSync(var0: java_util_function_Function | null): java_util_function_BiFunction | null;
    // ================== Method apply ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.lang.Object'
     * @return original return type: 'java.lang.Object'
     */
    public apply(var0: BasicOrJavaType | null, var1: BasicOrJavaType | null): Promise<BasicOrJavaType | null>;
    // ================== Method apply ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.lang.Object'
     * @return original return type: 'java.lang.Object'
     */
    public applySync(var0: BasicOrJavaType | null, var1: BasicOrJavaType | null): BasicOrJavaType | null;
}

/**
 * Class java.util.function.BinaryOperator.
 *
 * This actually imports the java class for further use.
 * The class BinaryOperatorClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class BinaryOperator extends importClass<typeof BinaryOperatorClass>("java.util.function.BinaryOperator") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default BinaryOperator;