import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";

/**
 * This class just defines types, you should import Consumer instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ConsumerClass extends JavaClass {
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'java.util.function.Consumer'
     */
    public andThen(var0: ConsumerClass | null): Promise<Consumer | null>;
    // ================== Method andThen ==================
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'java.util.function.Consumer'
     */
    public andThenSync(var0: ConsumerClass | null): Consumer | null;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public accept(var0: BasicOrJavaType | null): Promise<void>;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    public acceptSync(var0: BasicOrJavaType | null): void;
}

/**
 * Class java.util.function.Consumer.
 *
 * This actually imports the java class for further use.
 * The class ConsumerClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Consumer extends importClass<typeof ConsumerClass>("java.util.function.Consumer") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default Consumer;