import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Long as java_lang_Long } from "./../../lang/Long";

/**
 * This class just defines types, you should import ObjLongConsumer instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ObjLongConsumerClass extends JavaClass {
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'long'
     * @return original return type: 'void'
     */
    public accept(var0: BasicOrJavaType | null, var1: java_lang_Long | bigint | number): Promise<void>;
    // ================== Method accept ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'long'
     * @return original return type: 'void'
     */
    public acceptSync(var0: BasicOrJavaType | null, var1: java_lang_Long | bigint | number): void;
}

/**
 * Class java.util.function.ObjLongConsumer.
 *
 * This actually imports the java class for further use.
 * The class ObjLongConsumerClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class ObjLongConsumer extends importClass<typeof ObjLongConsumerClass>("java.util.function.ObjLongConsumer") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default ObjLongConsumer;