import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";

/**
 * This class just defines types, you should import Supplier instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class SupplierClass extends JavaClass {
    // ================== Method get ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public get(): Promise<BasicOrJavaType | null>;
    // ================== Method get ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public getSync(): BasicOrJavaType | null;
}

/**
 * Class java.util.function.Supplier.
 *
 * This actually imports the java class for further use.
 * The class SupplierClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Supplier extends importClass<typeof SupplierClass>("java.util.function.Supplier") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default Supplier;