import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { CharSequence as java_lang_CharSequence } from "./../lang/CharSequence";
import { Appendable as java_lang_Appendable } from "./../lang/Appendable";
import { IntStream as java_util_stream_IntStream } from "./../util/stream/IntStream";
import { ByteOrder as java_nio_ByteOrder } from "./ByteOrder";
import { Buffer as java_nio_Buffer } from "./Buffer";
import { Long as java_lang_Long } from "./../lang/Long";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import CharBuffer instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class CharBufferClass extends JavaClass {
    // ================== Method get ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'char'
     */
    public get(var0: java_lang_Integer | number): Promise<string | null>;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'char'
     */
    public getSync(var0: java_lang_Integer | number): string | null;
    /**
     * @return original return type: 'char'
     */
    public get(): Promise<string | null>;
    /**
     * @return original return type: 'char'
     */
    public getSync(): string | null;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public get(var0: (string | null)[] | null): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public getSync(var0: (string | null)[] | null): CharBuffer | null;
    /**
     * @param var0 original type: 'char[]'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public get(var0: (string | null)[] | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'char[]'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public getSync(var0: (string | null)[] | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): CharBuffer | null;
    // ================== Method put ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'char'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public put(var0: java_lang_Integer | number, var1: string | null): Promise<CharBuffer | null>;
    // ================== Method put ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'char'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public putSync(var0: java_lang_Integer | number, var1: string | null): CharBuffer | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public put(var0: string | null): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public putSync(var0: string | null): CharBuffer | null;
    /**
     * @param var0 original type: 'char[]'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public put(var0: (string | null)[] | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'char[]'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public putSync(var0: (string | null)[] | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): CharBuffer | null;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public put(var0: (string | null)[] | null): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public putSync(var0: (string | null)[] | null): CharBuffer | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public put(var0: string | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public putSync(var0: string | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): CharBuffer | null;
    /**
     * @param var0 original type: 'java.nio.CharBuffer'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public put(var0: CharBufferClass | null): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'java.nio.CharBuffer'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public putSync(var0: CharBufferClass | null): CharBuffer | null;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public put(var0: string | null): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public putSync(var0: string | null): CharBuffer | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method append ==================
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public append(var0: string | null): Promise<CharBuffer | null>;
    // ================== Method append ==================
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public appendSync(var0: string | null): CharBuffer | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public append(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public appendSync(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): CharBuffer | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_lang_Appendable | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_lang_Appendable | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: java_lang_CharSequence | null): Promise<java_lang_Appendable | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: java_lang_CharSequence | null): java_lang_Appendable | null;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: string | null): Promise<java_lang_Appendable | null>;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: string | null): java_lang_Appendable | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public append(var0: java_lang_CharSequence | null): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public appendSync(var0: java_lang_CharSequence | null): CharBuffer | null;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.nio.CharBuffer'
     * @return original return type: 'int'
     */
    public compareTo(var0: CharBufferClass | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.nio.CharBuffer'
     * @return original return type: 'int'
     */
    public compareToSync(var0: CharBufferClass | null): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    // ================== Method length ==================
    /**
     * @return original return type: 'int'
     */
    public length(): Promise<number>;
    // ================== Method length ==================
    /**
     * @return original return type: 'int'
     */
    public lengthSync(): number;
    // ================== Method charAt ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'char'
     */
    public charAt(var0: java_lang_Integer | number): Promise<string | null>;
    // ================== Method charAt ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'char'
     */
    public charAtSync(var0: java_lang_Integer | number): string | null;
    // ================== Method subSequence ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.lang.CharSequence'
     */
    public subSequence(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<java_lang_CharSequence | null>;
    // ================== Method subSequence ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.lang.CharSequence'
     */
    public subSequenceSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): java_lang_CharSequence | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public subSequence(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public subSequenceSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): CharBuffer | null;
    // ================== Method chars ==================
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    public chars(): Promise<java_util_stream_IntStream | null>;
    // ================== Method chars ==================
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    public charsSync(): java_util_stream_IntStream | null;
    // ================== Method isDirect ==================
    /**
     * @return original return type: 'boolean'
     */
    public isDirect(): Promise<boolean>;
    // ================== Method isDirect ==================
    /**
     * @return original return type: 'boolean'
     */
    public isDirectSync(): boolean;
    // ================== Method hasArray ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasArray(): Promise<boolean>;
    // ================== Method hasArray ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasArraySync(): boolean;
    // ================== Method array ==================
    /**
     * @return original return type: 'char[]'
     */
    public array(): Promise<(string | null)[] | null>;
    // ================== Method array ==================
    /**
     * @return original return type: 'char[]'
     */
    public arraySync(): (string | null)[] | null;
    /**
     * @return original return type: 'java.lang.Object'
     */
    public array(): Promise<BasicOrJavaType | null>;
    /**
     * @return original return type: 'java.lang.Object'
     */
    public arraySync(): BasicOrJavaType | null;
    // ================== Method arrayOffset ==================
    /**
     * @return original return type: 'int'
     */
    public arrayOffset(): Promise<number>;
    // ================== Method arrayOffset ==================
    /**
     * @return original return type: 'int'
     */
    public arrayOffsetSync(): number;
    // ================== Method read ==================
    /**
     * @param var0 original type: 'java.nio.CharBuffer'
     * @return original return type: 'int'
     */
    public read(var0: CharBufferClass | null): Promise<number>;
    // ================== Method read ==================
    /**
     * @param var0 original type: 'java.nio.CharBuffer'
     * @return original return type: 'int'
     */
    public readSync(var0: CharBufferClass | null): number;
    // ================== Method wrap ==================
    /**
     * @param var0 original type: 'char[]'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static wrap(var0: (string | null)[] | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<CharBuffer | null>;
    // ================== Method wrap ==================
    /**
     * @param var0 original type: 'char[]'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static wrapSync(var0: (string | null)[] | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): CharBuffer | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static wrap(var0: java_lang_CharSequence | null): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static wrapSync(var0: java_lang_CharSequence | null): CharBuffer | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static wrap(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static wrapSync(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): CharBuffer | null;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static wrap(var0: (string | null)[] | null): Promise<CharBuffer | null>;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static wrapSync(var0: (string | null)[] | null): CharBuffer | null;
    // ================== Method allocate ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static allocate(var0: java_lang_Integer | number): Promise<CharBuffer | null>;
    // ================== Method allocate ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.CharBuffer'
     */
    public static allocateSync(var0: java_lang_Integer | number): CharBuffer | null;
    // ================== Method duplicate ==================
    /**
     * @return original return type: 'java.nio.CharBuffer'
     */
    public duplicate(): Promise<CharBuffer | null>;
    // ================== Method duplicate ==================
    /**
     * @return original return type: 'java.nio.CharBuffer'
     */
    public duplicateSync(): CharBuffer | null;
    // ================== Method slice ==================
    /**
     * @return original return type: 'java.nio.CharBuffer'
     */
    public slice(): Promise<CharBuffer | null>;
    // ================== Method slice ==================
    /**
     * @return original return type: 'java.nio.CharBuffer'
     */
    public sliceSync(): CharBuffer | null;
    // ================== Method asReadOnlyBuffer ==================
    /**
     * @return original return type: 'java.nio.CharBuffer'
     */
    public asReadOnlyBuffer(): Promise<CharBuffer | null>;
    // ================== Method asReadOnlyBuffer ==================
    /**
     * @return original return type: 'java.nio.CharBuffer'
     */
    public asReadOnlyBufferSync(): CharBuffer | null;
    // ================== Method compact ==================
    /**
     * @return original return type: 'java.nio.CharBuffer'
     */
    public compact(): Promise<CharBuffer | null>;
    // ================== Method compact ==================
    /**
     * @return original return type: 'java.nio.CharBuffer'
     */
    public compactSync(): CharBuffer | null;
    // ================== Method order ==================
    /**
     * @return original return type: 'java.nio.ByteOrder'
     */
    public order(): Promise<java_nio_ByteOrder | null>;
    // ================== Method order ==================
    /**
     * @return original return type: 'java.nio.ByteOrder'
     */
    public orderSync(): java_nio_ByteOrder | null;
    // ================== Method limit ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.Buffer'
     */
    public limit(var0: java_lang_Integer | number): Promise<java_nio_Buffer | null>;
    // ================== Method limit ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.Buffer'
     */
    public limitSync(var0: java_lang_Integer | number): java_nio_Buffer | null;
    /**
     * @return original return type: 'int'
     */
    public limit(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    public limitSync(): number;
    // ================== Method clear ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public clear(): Promise<java_nio_Buffer | null>;
    // ================== Method clear ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public clearSync(): java_nio_Buffer | null;
    // ================== Method remaining ==================
    /**
     * @return original return type: 'int'
     */
    public remaining(): Promise<number>;
    // ================== Method remaining ==================
    /**
     * @return original return type: 'int'
     */
    public remainingSync(): number;
    // ================== Method position ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.Buffer'
     */
    public position(var0: java_lang_Integer | number): Promise<java_nio_Buffer | null>;
    // ================== Method position ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.Buffer'
     */
    public positionSync(var0: java_lang_Integer | number): java_nio_Buffer | null;
    /**
     * @return original return type: 'int'
     */
    public position(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    public positionSync(): number;
    // ================== Method capacity ==================
    /**
     * @return original return type: 'int'
     */
    public capacity(): Promise<number>;
    // ================== Method capacity ==================
    /**
     * @return original return type: 'int'
     */
    public capacitySync(): number;
    // ================== Method mark ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public mark(): Promise<java_nio_Buffer | null>;
    // ================== Method mark ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public markSync(): java_nio_Buffer | null;
    // ================== Method reset ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public reset(): Promise<java_nio_Buffer | null>;
    // ================== Method reset ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public resetSync(): java_nio_Buffer | null;
    // ================== Method flip ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public flip(): Promise<java_nio_Buffer | null>;
    // ================== Method flip ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public flipSync(): java_nio_Buffer | null;
    // ================== Method rewind ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public rewind(): Promise<java_nio_Buffer | null>;
    // ================== Method rewind ==================
    /**
     * @return original return type: 'java.nio.Buffer'
     */
    public rewindSync(): java_nio_Buffer | null;
    // ================== Method hasRemaining ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasRemaining(): Promise<boolean>;
    // ================== Method hasRemaining ==================
    /**
     * @return original return type: 'boolean'
     */
    public hasRemainingSync(): boolean;
    // ================== Method isReadOnly ==================
    /**
     * @return original return type: 'boolean'
     */
    public isReadOnly(): Promise<boolean>;
    // ================== Method isReadOnly ==================
    /**
     * @return original return type: 'boolean'
     */
    public isReadOnlySync(): boolean;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method codePoints ==================
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    public codePoints(): Promise<java_util_stream_IntStream | null>;
    // ================== Method codePoints ==================
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    public codePointsSync(): java_util_stream_IntStream | null;
}

/**
 * Class java.nio.CharBuffer.
 *
 * This actually imports the java class for further use.
 * The class CharBufferClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class CharBuffer extends importClass<typeof CharBufferClass>("java.nio.CharBuffer") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default CharBuffer;