import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Permission as java_security_Permission } from "./Permission";
import { DomainCombiner as java_security_DomainCombiner } from "./DomainCombiner";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";
import { ProtectionDomain as java_security_ProtectionDomain } from "./ProtectionDomain";

/**
 * This class just defines types, you should import AccessControlContext instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class AccessControlContextClass extends JavaClass {
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method checkPermission ==================
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'void'
     */
    public checkPermission(var0: java_security_Permission | null): Promise<void>;
    // ================== Method checkPermission ==================
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'void'
     */
    public checkPermissionSync(var0: java_security_Permission | null): void;
    // ================== Method getDomainCombiner ==================
    /**
     * @return original return type: 'java.security.DomainCombiner'
     */
    public getDomainCombiner(): Promise<java_security_DomainCombiner | null>;
    // ================== Method getDomainCombiner ==================
    /**
     * @return original return type: 'java.security.DomainCombiner'
     */
    public getDomainCombinerSync(): java_security_DomainCombiner | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method newInstance ==================
    /**
     * @param var0 original type: 'java.security.ProtectionDomain[]'
     * @return original return type: 'java.security.AccessControlContext'
     */
    public static newInstance(var0: (java_security_ProtectionDomain | null)[] | null): Promise<AccessControlContext>;
    /**
     * @param var0 original type: 'java.security.AccessControlContext'
     * @param var1 original type: 'java.security.DomainCombiner'
     * @return original return type: 'java.security.AccessControlContext'
     */
    public static newInstance(var0: AccessControlContextClass | null, var1: java_security_DomainCombiner | null): Promise<AccessControlContext>;
    // ================== Constructors ==================
    /**
     * @param var0 original type: 'java.security.ProtectionDomain[]'
     */
    public constructor(var0: (java_security_ProtectionDomain | null)[] | null);
    /**
     * @param var0 original type: 'java.security.AccessControlContext'
     * @param var1 original type: 'java.security.DomainCombiner'
     */
    public constructor(var0: AccessControlContextClass | null, var1: java_security_DomainCombiner | null);
}

/**
 * Class java.security.AccessControlContext.
 *
 * This actually imports the java class for further use.
 * The class AccessControlContextClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class AccessControlContext extends importClass<typeof AccessControlContextClass>("java.security.AccessControlContext") {
}
export default AccessControlContext;