import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Permission as java_security_Permission } from "./Permission";
import { Enumeration as java_util_Enumeration } from "./../util/Enumeration";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import PermissionCollection instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PermissionCollectionClass extends JavaClass {
    // ================== Method add ==================
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'void'
     */
    public add(var0: java_security_Permission | null): Promise<void>;
    // ================== Method add ==================
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'void'
     */
    public addSync(var0: java_security_Permission | null): void;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method implies ==================
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'boolean'
     */
    public implies(var0: java_security_Permission | null): Promise<boolean>;
    // ================== Method implies ==================
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'boolean'
     */
    public impliesSync(var0: java_security_Permission | null): boolean;
    // ================== Method setReadOnly ==================
    /**
     * @return original return type: 'void'
     */
    public setReadOnly(): Promise<void>;
    // ================== Method setReadOnly ==================
    /**
     * @return original return type: 'void'
     */
    public setReadOnlySync(): void;
    // ================== Method elements ==================
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    public elements(): Promise<java_util_Enumeration | null>;
    // ================== Method elements ==================
    /**
     * @return original return type: 'java.util.Enumeration'
     */
    public elementsSync(): java_util_Enumeration | null;
    // ================== Method isReadOnly ==================
    /**
     * @return original return type: 'boolean'
     */
    public isReadOnly(): Promise<boolean>;
    // ================== Method isReadOnly ==================
    /**
     * @return original return type: 'boolean'
     */
    public isReadOnlySync(): boolean;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.security.PermissionCollection.
 *
 * This actually imports the java class for further use.
 * The class PermissionCollectionClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class PermissionCollection extends importClass<typeof PermissionCollectionClass>("java.security.PermissionCollection") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default PermissionCollection;