import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { ClassLoader as java_lang_ClassLoader } from "./../lang/ClassLoader";
import { CodeSource as java_security_CodeSource } from "./CodeSource";
import { Principal as java_security_Principal } from "./Principal";
import { PermissionCollection as java_security_PermissionCollection } from "./PermissionCollection";
import { Permission as java_security_Permission } from "./Permission";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import ProtectionDomain instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ProtectionDomainClass extends JavaClass {
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method getClassLoader ==================
    /**
     * @return original return type: 'java.lang.ClassLoader'
     */
    public getClassLoader(): Promise<java_lang_ClassLoader | null>;
    // ================== Method getClassLoader ==================
    /**
     * @return original return type: 'java.lang.ClassLoader'
     */
    public getClassLoaderSync(): java_lang_ClassLoader | null;
    // ================== Method getCodeSource ==================
    /**
     * @return original return type: 'java.security.CodeSource'
     */
    public getCodeSource(): Promise<java_security_CodeSource | null>;
    // ================== Method getCodeSource ==================
    /**
     * @return original return type: 'java.security.CodeSource'
     */
    public getCodeSourceSync(): java_security_CodeSource | null;
    // ================== Method getPrincipals ==================
    /**
     * @return original return type: 'java.security.Principal[]'
     */
    public getPrincipals(): Promise<(java_security_Principal | null)[] | null>;
    // ================== Method getPrincipals ==================
    /**
     * @return original return type: 'java.security.Principal[]'
     */
    public getPrincipalsSync(): (java_security_Principal | null)[] | null;
    // ================== Method getPermissions ==================
    /**
     * @return original return type: 'java.security.PermissionCollection'
     */
    public getPermissions(): Promise<java_security_PermissionCollection | null>;
    // ================== Method getPermissions ==================
    /**
     * @return original return type: 'java.security.PermissionCollection'
     */
    public getPermissionsSync(): java_security_PermissionCollection | null;
    // ================== Method implies ==================
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'boolean'
     */
    public implies(var0: java_security_Permission | null): Promise<boolean>;
    // ================== Method implies ==================
    /**
     * @param var0 original type: 'java.security.Permission'
     * @return original return type: 'boolean'
     */
    public impliesSync(var0: java_security_Permission | null): boolean;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method newInstance ==================
    /**
     * @param var0 original type: 'java.security.CodeSource'
     * @param var1 original type: 'java.security.PermissionCollection'
     * @return original return type: 'java.security.ProtectionDomain'
     */
    public static newInstance(var0: java_security_CodeSource | null, var1: java_security_PermissionCollection | null): Promise<ProtectionDomain>;
    /**
     * @param var0 original type: 'java.security.CodeSource'
     * @param var1 original type: 'java.security.PermissionCollection'
     * @param var2 original type: 'java.lang.ClassLoader'
     * @param var3 original type: 'java.security.Principal[]'
     * @return original return type: 'java.security.ProtectionDomain'
     */
    public static newInstance(var0: java_security_CodeSource | null, var1: java_security_PermissionCollection | null, var2: java_lang_ClassLoader | null, var3: (java_security_Principal | null)[] | null): Promise<ProtectionDomain>;
    // ================== Constructors ==================
    /**
     * @param var0 original type: 'java.security.CodeSource'
     * @param var1 original type: 'java.security.PermissionCollection'
     */
    public constructor(var0: java_security_CodeSource | null, var1: java_security_PermissionCollection | null);
    /**
     * @param var0 original type: 'java.security.CodeSource'
     * @param var1 original type: 'java.security.PermissionCollection'
     * @param var2 original type: 'java.lang.ClassLoader'
     * @param var3 original type: 'java.security.Principal[]'
     */
    public constructor(var0: java_security_CodeSource | null, var1: java_security_PermissionCollection | null, var2: java_lang_ClassLoader | null, var3: (java_security_Principal | null)[] | null);
}

/**
 * Class java.security.ProtectionDomain.
 *
 * This actually imports the java class for further use.
 * The class ProtectionDomainClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class ProtectionDomain extends importClass<typeof ProtectionDomainClass>("java.security.ProtectionDomain") {
}
export default ProtectionDomain;