import { importClass, JavaClass } from "java-bridge";
import { Long as java_lang_Long } from "./../lang/Long";

/**
 * This class just defines types, you should import PublicKey instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PublicKeyClass extends JavaClass {
    // ================== Field serialVersionUID ==================
    /**
     * Original type: 'long'
     */
    public static readonly serialVersionUID: java_lang_Long | bigint | number;
    // ================== Method getAlgorithm ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getAlgorithm(): Promise<string | null>;
    // ================== Method getAlgorithm ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getAlgorithmSync(): string | null;
    // ================== Method getFormat ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getFormat(): Promise<string | null>;
    // ================== Method getFormat ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getFormatSync(): string | null;
    // ================== Method getEncoded ==================
    /**
     * @return original return type: 'byte[]'
     */
    public getEncoded(): Promise<Buffer | null>;
    // ================== Method getEncoded ==================
    /**
     * @return original return type: 'byte[]'
     */
    public getEncodedSync(): Buffer | null;
}

/**
 * Class java.security.PublicKey.
 *
 * This actually imports the java class for further use.
 * The class PublicKeyClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class PublicKey extends importClass<typeof PublicKeyClass>("java.security.PublicKey") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default PublicKey;