import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Integer as java_lang_Integer } from "./../Integer";
import { TypeVariable as java_lang_reflect_TypeVariable } from "./TypeVariable";
import { Class as java_lang_Class } from "./../Class";
import { Annotation as java_lang_annotation_Annotation } from "./../annotation/Annotation";
import { Type as java_lang_reflect_Type } from "./Type";
import { AnnotatedType as java_lang_reflect_AnnotatedType } from "./AnnotatedType";
import { Parameter as java_lang_reflect_Parameter } from "./Parameter";
import { AccessibleObject as java_lang_reflect_AccessibleObject } from "./AccessibleObject";
import { Boolean as java_lang_Boolean } from "./../Boolean";
import { Long as java_lang_Long } from "./../Long";

/**
 * This class just defines types, you should import Method instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class MethodClass extends JavaClass {
    // ================== Field PUBLIC ==================
    /**
     * Original type: 'int'
     */
    public static readonly PUBLIC: java_lang_Integer | number;
    // ================== Field DECLARED ==================
    /**
     * Original type: 'int'
     */
    public static readonly DECLARED: java_lang_Integer | number;
    // ================== Method invoke ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.lang.Object[]'
     * @return original return type: 'java.lang.Object'
     */
    public invoke(var0: BasicOrJavaType | null, var1: (BasicOrJavaType | null)[] | null): Promise<BasicOrJavaType | null>;
    // ================== Method invoke ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.lang.Object[]'
     * @return original return type: 'java.lang.Object'
     */
    public invokeSync(var0: BasicOrJavaType | null, var1: (BasicOrJavaType | null)[] | null): BasicOrJavaType | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getModifiers ==================
    /**
     * @return original return type: 'int'
     */
    public getModifiers(): Promise<number>;
    // ================== Method getModifiers ==================
    /**
     * @return original return type: 'int'
     */
    public getModifiersSync(): number;
    // ================== Method getName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getName(): Promise<string | null>;
    // ================== Method getName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getNameSync(): string | null;
    // ================== Method toGenericString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toGenericString(): Promise<string | null>;
    // ================== Method toGenericString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toGenericStringSync(): string | null;
    // ================== Method isSynthetic ==================
    /**
     * @return original return type: 'boolean'
     */
    public isSynthetic(): Promise<boolean>;
    // ================== Method isSynthetic ==================
    /**
     * @return original return type: 'boolean'
     */
    public isSyntheticSync(): boolean;
    // ================== Method getTypeParameters ==================
    /**
     * @return original return type: 'java.lang.reflect.TypeVariable[]'
     */
    public getTypeParameters(): Promise<(java_lang_reflect_TypeVariable | null)[] | null>;
    // ================== Method getTypeParameters ==================
    /**
     * @return original return type: 'java.lang.reflect.TypeVariable[]'
     */
    public getTypeParametersSync(): (java_lang_reflect_TypeVariable | null)[] | null;
    // ================== Method getDeclaringClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getDeclaringClass(): Promise<java_lang_Class | null>;
    // ================== Method getDeclaringClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getDeclaringClassSync(): java_lang_Class | null;
    // ================== Method getAnnotation ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation'
     */
    public getAnnotation(var0: java_lang_Class | null): Promise<java_lang_annotation_Annotation | null>;
    // ================== Method getAnnotation ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation'
     */
    public getAnnotationSync(var0: java_lang_Class | null): java_lang_annotation_Annotation | null;
    // ================== Method getDeclaredAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getDeclaredAnnotations(): Promise<(java_lang_annotation_Annotation | null)[] | null>;
    // ================== Method getDeclaredAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getDeclaredAnnotationsSync(): (java_lang_annotation_Annotation | null)[] | null;
    // ================== Method getReturnType ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getReturnType(): Promise<java_lang_Class | null>;
    // ================== Method getReturnType ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getReturnTypeSync(): java_lang_Class | null;
    // ================== Method getParameterTypes ==================
    /**
     * @return original return type: 'java.lang.Class[]'
     */
    public getParameterTypes(): Promise<(java_lang_Class | null)[] | null>;
    // ================== Method getParameterTypes ==================
    /**
     * @return original return type: 'java.lang.Class[]'
     */
    public getParameterTypesSync(): (java_lang_Class | null)[] | null;
    // ================== Method isDefault ==================
    /**
     * @return original return type: 'boolean'
     */
    public isDefault(): Promise<boolean>;
    // ================== Method isDefault ==================
    /**
     * @return original return type: 'boolean'
     */
    public isDefaultSync(): boolean;
    // ================== Method isVarArgs ==================
    /**
     * @return original return type: 'boolean'
     */
    public isVarArgs(): Promise<boolean>;
    // ================== Method isVarArgs ==================
    /**
     * @return original return type: 'boolean'
     */
    public isVarArgsSync(): boolean;
    // ================== Method getParameterCount ==================
    /**
     * @return original return type: 'int'
     */
    public getParameterCount(): Promise<number>;
    // ================== Method getParameterCount ==================
    /**
     * @return original return type: 'int'
     */
    public getParameterCountSync(): number;
    // ================== Method getParameterAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[][]'
     */
    public getParameterAnnotations(): Promise<((java_lang_annotation_Annotation | null)[] | null)[] | null>;
    // ================== Method getParameterAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[][]'
     */
    public getParameterAnnotationsSync(): ((java_lang_annotation_Annotation | null)[] | null)[] | null;
    // ================== Method getGenericReturnType ==================
    /**
     * @return original return type: 'java.lang.reflect.Type'
     */
    public getGenericReturnType(): Promise<java_lang_reflect_Type | null>;
    // ================== Method getGenericReturnType ==================
    /**
     * @return original return type: 'java.lang.reflect.Type'
     */
    public getGenericReturnTypeSync(): java_lang_reflect_Type | null;
    // ================== Method getGenericParameterTypes ==================
    /**
     * @return original return type: 'java.lang.reflect.Type[]'
     */
    public getGenericParameterTypes(): Promise<(java_lang_reflect_Type | null)[] | null>;
    // ================== Method getGenericParameterTypes ==================
    /**
     * @return original return type: 'java.lang.reflect.Type[]'
     */
    public getGenericParameterTypesSync(): (java_lang_reflect_Type | null)[] | null;
    // ================== Method getExceptionTypes ==================
    /**
     * @return original return type: 'java.lang.Class[]'
     */
    public getExceptionTypes(): Promise<(java_lang_Class | null)[] | null>;
    // ================== Method getExceptionTypes ==================
    /**
     * @return original return type: 'java.lang.Class[]'
     */
    public getExceptionTypesSync(): (java_lang_Class | null)[] | null;
    // ================== Method getGenericExceptionTypes ==================
    /**
     * @return original return type: 'java.lang.reflect.Type[]'
     */
    public getGenericExceptionTypes(): Promise<(java_lang_reflect_Type | null)[] | null>;
    // ================== Method getGenericExceptionTypes ==================
    /**
     * @return original return type: 'java.lang.reflect.Type[]'
     */
    public getGenericExceptionTypesSync(): (java_lang_reflect_Type | null)[] | null;
    // ================== Method isBridge ==================
    /**
     * @return original return type: 'boolean'
     */
    public isBridge(): Promise<boolean>;
    // ================== Method isBridge ==================
    /**
     * @return original return type: 'boolean'
     */
    public isBridgeSync(): boolean;
    // ================== Method getDefaultValue ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public getDefaultValue(): Promise<BasicOrJavaType | null>;
    // ================== Method getDefaultValue ==================
    /**
     * @return original return type: 'java.lang.Object'
     */
    public getDefaultValueSync(): BasicOrJavaType | null;
    // ================== Method getAnnotatedReturnType ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType'
     */
    public getAnnotatedReturnType(): Promise<java_lang_reflect_AnnotatedType | null>;
    // ================== Method getAnnotatedReturnType ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType'
     */
    public getAnnotatedReturnTypeSync(): java_lang_reflect_AnnotatedType | null;
    // ================== Method getAnnotationsByType ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getAnnotationsByType(var0: java_lang_Class | null): Promise<(java_lang_annotation_Annotation | null)[] | null>;
    // ================== Method getAnnotationsByType ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getAnnotationsByTypeSync(var0: java_lang_Class | null): (java_lang_annotation_Annotation | null)[] | null;
    // ================== Method getAnnotatedParameterTypes ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType[]'
     */
    public getAnnotatedParameterTypes(): Promise<(java_lang_reflect_AnnotatedType | null)[] | null>;
    // ================== Method getAnnotatedParameterTypes ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType[]'
     */
    public getAnnotatedParameterTypesSync(): (java_lang_reflect_AnnotatedType | null)[] | null;
    // ================== Method getParameters ==================
    /**
     * @return original return type: 'java.lang.reflect.Parameter[]'
     */
    public getParameters(): Promise<(java_lang_reflect_Parameter | null)[] | null>;
    // ================== Method getParameters ==================
    /**
     * @return original return type: 'java.lang.reflect.Parameter[]'
     */
    public getParametersSync(): (java_lang_reflect_Parameter | null)[] | null;
    // ================== Method getAnnotatedReceiverType ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType'
     */
    public getAnnotatedReceiverType(): Promise<java_lang_reflect_AnnotatedType | null>;
    // ================== Method getAnnotatedReceiverType ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType'
     */
    public getAnnotatedReceiverTypeSync(): java_lang_reflect_AnnotatedType | null;
    // ================== Method getAnnotatedExceptionTypes ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType[]'
     */
    public getAnnotatedExceptionTypes(): Promise<(java_lang_reflect_AnnotatedType | null)[] | null>;
    // ================== Method getAnnotatedExceptionTypes ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType[]'
     */
    public getAnnotatedExceptionTypesSync(): (java_lang_reflect_AnnotatedType | null)[] | null;
    // ================== Method isAnnotationPresent ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'boolean'
     */
    public isAnnotationPresent(var0: java_lang_Class | null): Promise<boolean>;
    // ================== Method isAnnotationPresent ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'boolean'
     */
    public isAnnotationPresentSync(var0: java_lang_Class | null): boolean;
    // ================== Method getAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getAnnotations(): Promise<(java_lang_annotation_Annotation | null)[] | null>;
    // ================== Method getAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getAnnotationsSync(): (java_lang_annotation_Annotation | null)[] | null;
    // ================== Method getDeclaredAnnotation ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation'
     */
    public getDeclaredAnnotation(var0: java_lang_Class | null): Promise<java_lang_annotation_Annotation | null>;
    // ================== Method getDeclaredAnnotation ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation'
     */
    public getDeclaredAnnotationSync(var0: java_lang_Class | null): java_lang_annotation_Annotation | null;
    // ================== Method getDeclaredAnnotationsByType ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getDeclaredAnnotationsByType(var0: java_lang_Class | null): Promise<(java_lang_annotation_Annotation | null)[] | null>;
    // ================== Method getDeclaredAnnotationsByType ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getDeclaredAnnotationsByTypeSync(var0: java_lang_Class | null): (java_lang_annotation_Annotation | null)[] | null;
    // ================== Method setAccessible ==================
    /**
     * @param var0 original type: 'java.lang.reflect.AccessibleObject[]'
     * @param var1 original type: 'boolean'
     * @return original return type: 'void'
     */
    public static setAccessible(var0: (java_lang_reflect_AccessibleObject | null)[] | null, var1: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setAccessible ==================
    /**
     * @param var0 original type: 'java.lang.reflect.AccessibleObject[]'
     * @param var1 original type: 'boolean'
     * @return original return type: 'void'
     */
    public static setAccessibleSync(var0: (java_lang_reflect_AccessibleObject | null)[] | null, var1: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setAccessible(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setAccessibleSync(var0: java_lang_Boolean | boolean): void;
    // ================== Method isAccessible ==================
    /**
     * @return original return type: 'boolean'
     */
    public isAccessible(): Promise<boolean>;
    // ================== Method isAccessible ==================
    /**
     * @return original return type: 'boolean'
     */
    public isAccessibleSync(): boolean;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.lang.reflect.Method.
 *
 * This actually imports the java class for further use.
 * The class MethodClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Method extends importClass<typeof MethodClass>("java.lang.reflect.Method") {
}
export default Method;