import { importClass, JavaClass } from "java-bridge";
import { Type as java_lang_reflect_Type } from "./Type";
import { GenericDeclaration as java_lang_reflect_GenericDeclaration } from "./GenericDeclaration";
import { AnnotatedType as java_lang_reflect_AnnotatedType } from "./AnnotatedType";
import { Annotation as java_lang_annotation_Annotation } from "./../annotation/Annotation";
import { Class as java_lang_Class } from "./../Class";

/**
 * This class just defines types, you should import TypeVariable instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class TypeVariableClass extends JavaClass {
    // ================== Method getBounds ==================
    /**
     * @return original return type: 'java.lang.reflect.Type[]'
     */
    public getBounds(): Promise<(java_lang_reflect_Type | null)[] | null>;
    // ================== Method getBounds ==================
    /**
     * @return original return type: 'java.lang.reflect.Type[]'
     */
    public getBoundsSync(): (java_lang_reflect_Type | null)[] | null;
    // ================== Method getGenericDeclaration ==================
    /**
     * @return original return type: 'java.lang.reflect.GenericDeclaration'
     */
    public getGenericDeclaration(): Promise<java_lang_reflect_GenericDeclaration | null>;
    // ================== Method getGenericDeclaration ==================
    /**
     * @return original return type: 'java.lang.reflect.GenericDeclaration'
     */
    public getGenericDeclarationSync(): java_lang_reflect_GenericDeclaration | null;
    // ================== Method getAnnotatedBounds ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType[]'
     */
    public getAnnotatedBounds(): Promise<(java_lang_reflect_AnnotatedType | null)[] | null>;
    // ================== Method getAnnotatedBounds ==================
    /**
     * @return original return type: 'java.lang.reflect.AnnotatedType[]'
     */
    public getAnnotatedBoundsSync(): (java_lang_reflect_AnnotatedType | null)[] | null;
    // ================== Method getName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getName(): Promise<string | null>;
    // ================== Method getName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getNameSync(): string | null;
    // ================== Method getTypeName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getTypeName(): Promise<string | null>;
    // ================== Method getTypeName ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public getTypeNameSync(): string | null;
    // ================== Method getAnnotation ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation'
     */
    public getAnnotation(var0: java_lang_Class | null): Promise<java_lang_annotation_Annotation | null>;
    // ================== Method getAnnotation ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation'
     */
    public getAnnotationSync(var0: java_lang_Class | null): java_lang_annotation_Annotation | null;
    // ================== Method isAnnotationPresent ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'boolean'
     */
    public isAnnotationPresent(var0: java_lang_Class | null): Promise<boolean>;
    // ================== Method isAnnotationPresent ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'boolean'
     */
    public isAnnotationPresentSync(var0: java_lang_Class | null): boolean;
    // ================== Method getAnnotationsByType ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getAnnotationsByType(var0: java_lang_Class | null): Promise<(java_lang_annotation_Annotation | null)[] | null>;
    // ================== Method getAnnotationsByType ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getAnnotationsByTypeSync(var0: java_lang_Class | null): (java_lang_annotation_Annotation | null)[] | null;
    // ================== Method getAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getAnnotations(): Promise<(java_lang_annotation_Annotation | null)[] | null>;
    // ================== Method getAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getAnnotationsSync(): (java_lang_annotation_Annotation | null)[] | null;
    // ================== Method getDeclaredAnnotation ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation'
     */
    public getDeclaredAnnotation(var0: java_lang_Class | null): Promise<java_lang_annotation_Annotation | null>;
    // ================== Method getDeclaredAnnotation ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation'
     */
    public getDeclaredAnnotationSync(var0: java_lang_Class | null): java_lang_annotation_Annotation | null;
    // ================== Method getDeclaredAnnotationsByType ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getDeclaredAnnotationsByType(var0: java_lang_Class | null): Promise<(java_lang_annotation_Annotation | null)[] | null>;
    // ================== Method getDeclaredAnnotationsByType ==================
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getDeclaredAnnotationsByTypeSync(var0: java_lang_Class | null): (java_lang_annotation_Annotation | null)[] | null;
    // ================== Method getDeclaredAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getDeclaredAnnotations(): Promise<(java_lang_annotation_Annotation | null)[] | null>;
    // ================== Method getDeclaredAnnotations ==================
    /**
     * @return original return type: 'java.lang.annotation.Annotation[]'
     */
    public getDeclaredAnnotationsSync(): (java_lang_annotation_Annotation | null)[] | null;
}

/**
 * Class java.lang.reflect.TypeVariable.
 *
 * This actually imports the java class for further use.
 * The class TypeVariableClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class TypeVariable extends importClass<typeof TypeVariableClass>("java.lang.reflect.TypeVariable") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default TypeVariable;