import { importClass, JavaClass } from "java-bridge";
import { CharSequence as java_lang_CharSequence } from "./CharSequence";
import { Integer as java_lang_Integer } from "./Integer";

/**
 * This class just defines types, you should import Appendable instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class AppendableClass extends JavaClass {
    // ================== Method append ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: java_lang_CharSequence | null): Promise<Appendable | null>;
    // ================== Method append ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: java_lang_CharSequence | null): Appendable | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<Appendable | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: java_lang_CharSequence | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Appendable | null;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.lang.Appendable'
     */
    public append(var0: string | null): Promise<Appendable | null>;
    /**
     * @param var0 original type: 'char'
     * @return original return type: 'java.lang.Appendable'
     */
    public appendSync(var0: string | null): Appendable | null;
}

/**
 * Class java.lang.Appendable.
 *
 * This actually imports the java class for further use.
 * The class AppendableClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Appendable extends importClass<typeof AppendableClass>("java.lang.Appendable") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default Appendable;