import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Class as java_lang_Class } from "./Class";
import { InputStream as java_io_InputStream } from "./../io/InputStream";
import { URL as java_net_URL } from "./../net/URL";
import { Enumeration as java_util_Enumeration } from "./../util/Enumeration";
import { Boolean as java_lang_Boolean } from "./Boolean";
import { Long as java_lang_Long } from "./Long";
import { Integer as java_lang_Integer } from "./Integer";

/**
 * This class just defines types, you should import ClassLoader instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ClassLoaderClass extends JavaClass {
    // ================== Method loadClass ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Class'
     */
    public loadClass(var0: string | null): Promise<java_lang_Class | null>;
    // ================== Method loadClass ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Class'
     */
    public loadClassSync(var0: string | null): java_lang_Class | null;
    // ================== Method getSystemClassLoader ==================
    /**
     * @return original return type: 'java.lang.ClassLoader'
     */
    public static getSystemClassLoader(): Promise<ClassLoader | null>;
    // ================== Method getSystemClassLoader ==================
    /**
     * @return original return type: 'java.lang.ClassLoader'
     */
    public static getSystemClassLoaderSync(): ClassLoader | null;
    // ================== Method getResourceAsStream ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.io.InputStream'
     */
    public getResourceAsStream(var0: string | null): Promise<java_io_InputStream | null>;
    // ================== Method getResourceAsStream ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.io.InputStream'
     */
    public getResourceAsStreamSync(var0: string | null): java_io_InputStream | null;
    // ================== Method getResource ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.net.URL'
     */
    public getResource(var0: string | null): Promise<java_net_URL | null>;
    // ================== Method getResource ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.net.URL'
     */
    public getResourceSync(var0: string | null): java_net_URL | null;
    // ================== Method getSystemResourceAsStream ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.io.InputStream'
     */
    public static getSystemResourceAsStream(var0: string | null): Promise<java_io_InputStream | null>;
    // ================== Method getSystemResourceAsStream ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.io.InputStream'
     */
    public static getSystemResourceAsStreamSync(var0: string | null): java_io_InputStream | null;
    // ================== Method getSystemResource ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.net.URL'
     */
    public static getSystemResource(var0: string | null): Promise<java_net_URL | null>;
    // ================== Method getSystemResource ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.net.URL'
     */
    public static getSystemResourceSync(var0: string | null): java_net_URL | null;
    // ================== Method getResources ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.Enumeration'
     */
    public getResources(var0: string | null): Promise<java_util_Enumeration | null>;
    // ================== Method getResources ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.Enumeration'
     */
    public getResourcesSync(var0: string | null): java_util_Enumeration | null;
    // ================== Method getSystemResources ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.Enumeration'
     */
    public static getSystemResources(var0: string | null): Promise<java_util_Enumeration | null>;
    // ================== Method getSystemResources ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.Enumeration'
     */
    public static getSystemResourcesSync(var0: string | null): java_util_Enumeration | null;
    // ================== Method getParent ==================
    /**
     * @return original return type: 'java.lang.ClassLoader'
     */
    public getParent(): Promise<ClassLoader | null>;
    // ================== Method getParent ==================
    /**
     * @return original return type: 'java.lang.ClassLoader'
     */
    public getParentSync(): ClassLoader | null;
    // ================== Method setDefaultAssertionStatus ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setDefaultAssertionStatus(var0: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setDefaultAssertionStatus ==================
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setDefaultAssertionStatusSync(var0: java_lang_Boolean | boolean): void;
    // ================== Method setPackageAssertionStatus ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setPackageAssertionStatus(var0: string | null, var1: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setPackageAssertionStatus ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setPackageAssertionStatusSync(var0: string | null, var1: java_lang_Boolean | boolean): void;
    // ================== Method setClassAssertionStatus ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setClassAssertionStatus(var0: string | null, var1: java_lang_Boolean | boolean): Promise<void>;
    // ================== Method setClassAssertionStatus ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @return original return type: 'void'
     */
    public setClassAssertionStatusSync(var0: string | null, var1: java_lang_Boolean | boolean): void;
    // ================== Method clearAssertionStatus ==================
    /**
     * @return original return type: 'void'
     */
    public clearAssertionStatus(): Promise<void>;
    // ================== Method clearAssertionStatus ==================
    /**
     * @return original return type: 'void'
     */
    public clearAssertionStatusSync(): void;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.lang.ClassLoader.
 *
 * This actually imports the java class for further use.
 * The class ClassLoaderClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class ClassLoader extends importClass<typeof ClassLoaderClass>("java.lang.ClassLoader") {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor() {
        super();
    }
}
export default ClassLoader;