import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Integer as java_lang_Integer } from "./Integer";
import { Class as java_lang_Class } from "./Class";
import { Long as java_lang_Long } from "./Long";
import { Double as java_lang_Double } from "./Double";

/**
 * This class just defines types, you should import Float instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FloatClass extends JavaClass {
    // ================== Field POSITIVE_INFINITY ==================
    /**
     * Original type: 'float'
     */
    public static readonly POSITIVE_INFINITY: FloatClass | number;
    // ================== Field NEGATIVE_INFINITY ==================
    /**
     * Original type: 'float'
     */
    public static readonly NEGATIVE_INFINITY: FloatClass | number;
    // ================== Field NaN ==================
    /**
     * Original type: 'float'
     */
    public static readonly NaN: FloatClass | number;
    // ================== Field MAX_VALUE ==================
    /**
     * Original type: 'float'
     */
    public static readonly MAX_VALUE: FloatClass | number;
    // ================== Field MIN_NORMAL ==================
    /**
     * Original type: 'float'
     */
    public static readonly MIN_NORMAL: FloatClass | number;
    // ================== Field MIN_VALUE ==================
    /**
     * Original type: 'float'
     */
    public static readonly MIN_VALUE: FloatClass | number;
    // ================== Field MAX_EXPONENT ==================
    /**
     * Original type: 'int'
     */
    public static readonly MAX_EXPONENT: java_lang_Integer | number;
    // ================== Field MIN_EXPONENT ==================
    /**
     * Original type: 'int'
     */
    public static readonly MIN_EXPONENT: java_lang_Integer | number;
    // ================== Field SIZE ==================
    /**
     * Original type: 'int'
     */
    public static readonly SIZE: java_lang_Integer | number;
    // ================== Field BYTES ==================
    /**
     * Original type: 'int'
     */
    public static readonly BYTES: java_lang_Integer | number;
    // ================== Field TYPE ==================
    /**
     * Original type: 'java.lang.Class'
     */
    public static readonly TYPE: java_lang_Class | null;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'java.lang.String'
     */
    public static toString(var0: FloatClass | number): Promise<string>;
    // ================== Method toString ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'java.lang.String'
     */
    public static toStringSync(var0: FloatClass | number): string;
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'int'
     */
    public static hashCode(var0: FloatClass | number): Promise<number>;
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'int'
     */
    public static hashCodeSync(var0: FloatClass | number): number;
    // ================== Method min ==================
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    public static min(var0: FloatClass | number, var1: FloatClass | number): Promise<number>;
    // ================== Method min ==================
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    public static minSync(var0: FloatClass | number, var1: FloatClass | number): number;
    // ================== Method max ==================
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    public static max(var0: FloatClass | number, var1: FloatClass | number): Promise<number>;
    // ================== Method max ==================
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    public static maxSync(var0: FloatClass | number, var1: FloatClass | number): number;
    // ================== Method floatToRawIntBits ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'int'
     */
    public static floatToRawIntBits(var0: FloatClass | number): Promise<number>;
    // ================== Method floatToRawIntBits ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'int'
     */
    public static floatToRawIntBitsSync(var0: FloatClass | number): number;
    // ================== Method floatToIntBits ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'int'
     */
    public static floatToIntBits(var0: FloatClass | number): Promise<number>;
    // ================== Method floatToIntBits ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'int'
     */
    public static floatToIntBitsSync(var0: FloatClass | number): number;
    // ================== Method intBitsToFloat ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'float'
     */
    public static intBitsToFloat(var0: java_lang_Integer | number): Promise<number>;
    // ================== Method intBitsToFloat ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'float'
     */
    public static intBitsToFloatSync(var0: java_lang_Integer | number): number;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.lang.Float'
     * @return original return type: 'int'
     */
    public compareTo(var0: FloatClass | number | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.lang.Float'
     * @return original return type: 'int'
     */
    public compareToSync(var0: FloatClass | number | null): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    // ================== Method byteValue ==================
    /**
     * @return original return type: 'byte'
     */
    public byteValue(): Promise<number>;
    // ================== Method byteValue ==================
    /**
     * @return original return type: 'byte'
     */
    public byteValueSync(): number;
    // ================== Method shortValue ==================
    /**
     * @return original return type: 'short'
     */
    public shortValue(): Promise<number>;
    // ================== Method shortValue ==================
    /**
     * @return original return type: 'short'
     */
    public shortValueSync(): number;
    // ================== Method intValue ==================
    /**
     * @return original return type: 'int'
     */
    public intValue(): Promise<number>;
    // ================== Method intValue ==================
    /**
     * @return original return type: 'int'
     */
    public intValueSync(): number;
    // ================== Method longValue ==================
    /**
     * @return original return type: 'long'
     */
    public longValue(): Promise<number>;
    // ================== Method longValue ==================
    /**
     * @return original return type: 'long'
     */
    public longValueSync(): number;
    // ================== Method floatValue ==================
    /**
     * @return original return type: 'float'
     */
    public floatValue(): Promise<number>;
    // ================== Method floatValue ==================
    /**
     * @return original return type: 'float'
     */
    public floatValueSync(): number;
    // ================== Method doubleValue ==================
    /**
     * @return original return type: 'double'
     */
    public doubleValue(): Promise<number>;
    // ================== Method doubleValue ==================
    /**
     * @return original return type: 'double'
     */
    public doubleValueSync(): number;
    // ================== Method valueOf ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'java.lang.Float'
     */
    public static valueOf(var0: FloatClass | number): Promise<number | null>;
    // ================== Method valueOf ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'java.lang.Float'
     */
    public static valueOfSync(var0: FloatClass | number): number | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Float'
     */
    public static valueOf(var0: string | null): Promise<number | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Float'
     */
    public static valueOfSync(var0: string | null): number | null;
    // ================== Method toHexString ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'java.lang.String'
     */
    public static toHexString(var0: FloatClass | number): Promise<string | null>;
    // ================== Method toHexString ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'java.lang.String'
     */
    public static toHexStringSync(var0: FloatClass | number): string | null;
    // ================== Method compare ==================
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'int'
     */
    public static compare(var0: FloatClass | number, var1: FloatClass | number): Promise<number>;
    // ================== Method compare ==================
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'int'
     */
    public static compareSync(var0: FloatClass | number, var1: FloatClass | number): number;
    // ================== Method isNaN ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'boolean'
     */
    public static isNaN(var0: FloatClass | number): Promise<boolean>;
    // ================== Method isNaN ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'boolean'
     */
    public static isNaNSync(var0: FloatClass | number): boolean;
    /**
     * @return original return type: 'boolean'
     */
    public isNaN(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    public isNaNSync(): boolean;
    // ================== Method parseFloat ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'float'
     */
    public static parseFloat(var0: string | null): Promise<number>;
    // ================== Method parseFloat ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'float'
     */
    public static parseFloatSync(var0: string | null): number;
    // ================== Method isInfinite ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'boolean'
     */
    public static isInfinite(var0: FloatClass | number): Promise<boolean>;
    // ================== Method isInfinite ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'boolean'
     */
    public static isInfiniteSync(var0: FloatClass | number): boolean;
    /**
     * @return original return type: 'boolean'
     */
    public isInfinite(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    public isInfiniteSync(): boolean;
    // ================== Method isFinite ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'boolean'
     */
    public static isFinite(var0: FloatClass | number): Promise<boolean>;
    // ================== Method isFinite ==================
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'boolean'
     */
    public static isFiniteSync(var0: FloatClass | number): boolean;
    // ================== Method sum ==================
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    public static sum(var0: FloatClass | number, var1: FloatClass | number): Promise<number>;
    // ================== Method sum ==================
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    public static sumSync(var0: FloatClass | number, var1: FloatClass | number): number;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method newInstance ==================
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Float'
     */
    public static newInstance(var0: string | null): Promise<number>;
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'java.lang.Float'
     */
    public static newInstance(var0: java_lang_Double | number): Promise<number>;
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'java.lang.Float'
     */
    public static newInstance(var0: FloatClass | number): Promise<number>;
    // ================== Constructors ==================
    /**
     * @param var0 original type: 'java.lang.String'
     */
    public constructor(var0: string | null);
    /**
     * @param var0 original type: 'double'
     */
    public constructor(var0: java_lang_Double | number);
    /**
     * @param var0 original type: 'float'
     */
    public constructor(var0: FloatClass | number);
}

/**
 * Class java.lang.Float.
 *
 * This actually imports the java class for further use.
 * The class FloatClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Float extends importClass<typeof FloatClass>("java.lang.Float") {
}
export default Float;