import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { TemporalUnit as java_time_temporal_TemporalUnit } from "./temporal/TemporalUnit";
import { Temporal as java_time_temporal_Temporal } from "./temporal/Temporal";
import { List as java_util_List } from "./../util/List";
import { TemporalAmount as java_time_temporal_TemporalAmount } from "./temporal/TemporalAmount";
import { CharSequence as java_lang_CharSequence } from "./../lang/CharSequence";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import Duration instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class DurationClass extends JavaClass {
    // ================== Field ZERO ==================
    /**
     * Original type: 'java.time.Duration'
     */
    public static readonly ZERO: DurationClass | null;
    // ================== Method ofDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofDays(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method ofDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofDaysSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method ofMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofMinutes(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method ofMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofMinutesSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method ofSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofSeconds(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method ofSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofSecondsSync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): Duration | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofSeconds(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofSecondsSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method ofMillis ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofMillis(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method ofMillis ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofMillisSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method ofNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofNanos(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method ofNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofNanosSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method isZero ==================
    /**
     * @return original return type: 'boolean'
     */
    public isZero(): Promise<boolean>;
    // ================== Method isZero ==================
    /**
     * @return original return type: 'boolean'
     */
    public isZeroSync(): boolean;
    // ================== Method withSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public withSeconds(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method withSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public withSecondsSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method withNanos ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Duration'
     */
    public withNanos(var0: java_lang_Integer | number): Promise<Duration | null>;
    // ================== Method withNanos ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Duration'
     */
    public withNanosSync(var0: java_lang_Integer | number): Duration | null;
    // ================== Method multipliedBy ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public multipliedBy(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method multipliedBy ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public multipliedBySync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method dividedBy ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public dividedBy(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method dividedBy ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public dividedBySync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method negated ==================
    /**
     * @return original return type: 'java.time.Duration'
     */
    public negated(): Promise<Duration | null>;
    // ================== Method negated ==================
    /**
     * @return original return type: 'java.time.Duration'
     */
    public negatedSync(): Duration | null;
    // ================== Method toMinutes ==================
    /**
     * @return original return type: 'long'
     */
    public toMinutes(): Promise<number>;
    // ================== Method toMinutes ==================
    /**
     * @return original return type: 'long'
     */
    public toMinutesSync(): number;
    // ================== Method toHours ==================
    /**
     * @return original return type: 'long'
     */
    public toHours(): Promise<number>;
    // ================== Method toHours ==================
    /**
     * @return original return type: 'long'
     */
    public toHoursSync(): number;
    // ================== Method toDays ==================
    /**
     * @return original return type: 'long'
     */
    public toDays(): Promise<number>;
    // ================== Method toDays ==================
    /**
     * @return original return type: 'long'
     */
    public toDaysSync(): number;
    // ================== Method getNano ==================
    /**
     * @return original return type: 'int'
     */
    public getNano(): Promise<number>;
    // ================== Method getNano ==================
    /**
     * @return original return type: 'int'
     */
    public getNanoSync(): number;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.Duration'
     * @return original return type: 'java.time.Duration'
     */
    public plus(var0: DurationClass | null): Promise<Duration | null>;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.Duration'
     * @return original return type: 'java.time.Duration'
     */
    public plusSync(var0: DurationClass | null): Duration | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.Duration'
     */
    public plus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<Duration | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.Duration'
     */
    public plusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Duration | null;
    // ================== Method plusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusSeconds(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method plusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusSecondsSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method plusMillis ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusMillis(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method plusMillis ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusMillisSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method plusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusNanos(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method plusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusNanosSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'java.time.Duration'
     * @return original return type: 'java.time.Duration'
     */
    public minus(var0: DurationClass | null): Promise<Duration | null>;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'java.time.Duration'
     * @return original return type: 'java.time.Duration'
     */
    public minusSync(var0: DurationClass | null): Duration | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.Duration'
     */
    public minus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<Duration | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.Duration'
     */
    public minusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Duration | null;
    // ================== Method minusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusSeconds(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method minusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusSecondsSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method minusMillis ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusMillis(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method minusMillis ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusMillisSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method minusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusNanos(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method minusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusNanosSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method getSeconds ==================
    /**
     * @return original return type: 'long'
     */
    public getSeconds(): Promise<number>;
    // ================== Method getSeconds ==================
    /**
     * @return original return type: 'long'
     */
    public getSecondsSync(): number;
    // ================== Method addTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public addTo(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method addTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public addToSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method subtractFrom ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public subtractFrom(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method subtractFrom ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public subtractFromSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method between ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @param var1 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.Duration'
     */
    public static between(var0: java_time_temporal_Temporal | null, var1: java_time_temporal_Temporal | null): Promise<Duration | null>;
    // ================== Method between ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @param var1 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.Duration'
     */
    public static betweenSync(var0: java_time_temporal_Temporal | null, var1: java_time_temporal_Temporal | null): Duration | null;
    // ================== Method isNegative ==================
    /**
     * @return original return type: 'boolean'
     */
    public isNegative(): Promise<boolean>;
    // ================== Method isNegative ==================
    /**
     * @return original return type: 'boolean'
     */
    public isNegativeSync(): boolean;
    // ================== Method getUnits ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getUnits(): Promise<java_util_List | null>;
    // ================== Method getUnits ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getUnitsSync(): java_util_List | null;
    // ================== Method ofHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofHours(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method ofHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public static ofHoursSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method plusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusDays(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method plusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusDaysSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method plusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusHours(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method plusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusHoursSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method plusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusMinutes(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method plusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public plusMinutesSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method minusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusDays(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method minusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusDaysSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method minusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusHours(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method minusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusHoursSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method minusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusMinutes(var0: java_lang_Long | bigint | number): Promise<Duration | null>;
    // ================== Method minusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Duration'
     */
    public minusMinutesSync(var0: java_lang_Long | bigint | number): Duration | null;
    // ================== Method toNanos ==================
    /**
     * @return original return type: 'long'
     */
    public toNanos(): Promise<number>;
    // ================== Method toNanos ==================
    /**
     * @return original return type: 'long'
     */
    public toNanosSync(): number;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.Duration'
     */
    public static from(var0: java_time_temporal_TemporalAmount | null): Promise<Duration | null>;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.Duration'
     */
    public static fromSync(var0: java_time_temporal_TemporalAmount | null): Duration | null;
    // ================== Method toMillis ==================
    /**
     * @return original return type: 'long'
     */
    public toMillis(): Promise<number>;
    // ================== Method toMillis ==================
    /**
     * @return original return type: 'long'
     */
    public toMillisSync(): number;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public get(var0: java_time_temporal_TemporalUnit | null): Promise<number>;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public getSync(var0: java_time_temporal_TemporalUnit | null): number;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method abs ==================
    /**
     * @return original return type: 'java.time.Duration'
     */
    public abs(): Promise<Duration | null>;
    // ================== Method abs ==================
    /**
     * @return original return type: 'java.time.Duration'
     */
    public absSync(): Duration | null;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.time.Duration'
     * @return original return type: 'int'
     */
    public compareTo(var0: DurationClass | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.time.Duration'
     * @return original return type: 'int'
     */
    public compareToSync(var0: DurationClass | null): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.Duration'
     */
    public static of(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<Duration | null>;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.Duration'
     */
    public static ofSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Duration | null;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.time.Duration'
     */
    public static parse(var0: java_lang_CharSequence | null): Promise<Duration | null>;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.time.Duration'
     */
    public static parseSync(var0: java_lang_CharSequence | null): Duration | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.time.Duration.
 *
 * This actually imports the java class for further use.
 * The class DurationClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Duration extends importClass<typeof DurationClass>("java.time.Duration") {
}
export default Duration;