import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { Long as java_lang_Long } from "./../lang/Long";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { ZoneOffset as java_time_ZoneOffset } from "./ZoneOffset";
import { ZoneId as java_time_ZoneId } from "./ZoneId";
import { Clock as java_time_Clock } from "./Clock";
import { ChronoLocalDateTime as java_time_chrono_ChronoLocalDateTime } from "./chrono/ChronoLocalDateTime";
import { TemporalAdjuster as java_time_temporal_TemporalAdjuster } from "./temporal/TemporalAdjuster";
import { TemporalField as java_time_temporal_TemporalField } from "./temporal/TemporalField";
import { Temporal as java_time_temporal_Temporal } from "./temporal/Temporal";
import { TemporalUnit as java_time_temporal_TemporalUnit } from "./temporal/TemporalUnit";
import { TemporalAmount as java_time_temporal_TemporalAmount } from "./temporal/TemporalAmount";
import { OffsetDateTime as java_time_OffsetDateTime } from "./OffsetDateTime";
import { ChronoZonedDateTime as java_time_chrono_ChronoZonedDateTime } from "./chrono/ChronoZonedDateTime";
import { ZonedDateTime as java_time_ZonedDateTime } from "./ZonedDateTime";
import { Instant as java_time_Instant } from "./Instant";
import { ChronoLocalDate as java_time_chrono_ChronoLocalDate } from "./chrono/ChronoLocalDate";
import { LocalDate as java_time_LocalDate } from "./LocalDate";
import { Month as java_time_Month } from "./Month";
import { DayOfWeek as java_time_DayOfWeek } from "./DayOfWeek";
import { LocalTime as java_time_LocalTime } from "./LocalTime";
import { TemporalAccessor as java_time_temporal_TemporalAccessor } from "./temporal/TemporalAccessor";
import { DateTimeFormatter as java_time_format_DateTimeFormatter } from "./format/DateTimeFormatter";
import { TemporalQuery as java_time_temporal_TemporalQuery } from "./temporal/TemporalQuery";
import { CharSequence as java_lang_CharSequence } from "./../lang/CharSequence";
import { ValueRange as java_time_temporal_ValueRange } from "./temporal/ValueRange";
import { Class as java_lang_Class } from "./../lang/Class";
import { Chronology as java_time_chrono_Chronology } from "./chrono/Chronology";

/**
 * This class just defines types, you should import LocalDateTime instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LocalDateTimeClass extends JavaClass {
    // ================== Field MIN ==================
    /**
     * Original type: 'java.time.LocalDateTime'
     */
    public static readonly MIN: LocalDateTimeClass | null;
    // ================== Field MAX ==================
    /**
     * Original type: 'java.time.LocalDateTime'
     */
    public static readonly MAX: LocalDateTimeClass | null;
    // ================== Method getNano ==================
    /**
     * @return original return type: 'int'
     */
    public getNano(): Promise<number>;
    // ================== Method getNano ==================
    /**
     * @return original return type: 'int'
     */
    public getNanoSync(): number;
    // ================== Method ofEpochSecond ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @param var2 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofEpochSecond(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number, var2: java_time_ZoneOffset | null): Promise<LocalDateTime | null>;
    // ================== Method ofEpochSecond ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @param var2 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofEpochSecondSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number, var2: java_time_ZoneOffset | null): LocalDateTime | null;
    // ================== Method getYear ==================
    /**
     * @return original return type: 'int'
     */
    public getYear(): Promise<number>;
    // ================== Method getYear ==================
    /**
     * @return original return type: 'int'
     */
    public getYearSync(): number;
    // ================== Method getMonthValue ==================
    /**
     * @return original return type: 'int'
     */
    public getMonthValue(): Promise<number>;
    // ================== Method getMonthValue ==================
    /**
     * @return original return type: 'int'
     */
    public getMonthValueSync(): number;
    // ================== Method getDayOfMonth ==================
    /**
     * @return original return type: 'int'
     */
    public getDayOfMonth(): Promise<number>;
    // ================== Method getDayOfMonth ==================
    /**
     * @return original return type: 'int'
     */
    public getDayOfMonthSync(): number;
    // ================== Method getHour ==================
    /**
     * @return original return type: 'int'
     */
    public getHour(): Promise<number>;
    // ================== Method getHour ==================
    /**
     * @return original return type: 'int'
     */
    public getHourSync(): number;
    // ================== Method getMinute ==================
    /**
     * @return original return type: 'int'
     */
    public getMinute(): Promise<number>;
    // ================== Method getMinute ==================
    /**
     * @return original return type: 'int'
     */
    public getMinuteSync(): number;
    // ================== Method getSecond ==================
    /**
     * @return original return type: 'int'
     */
    public getSecond(): Promise<number>;
    // ================== Method getSecond ==================
    /**
     * @return original return type: 'int'
     */
    public getSecondSync(): number;
    // ================== Method now ==================
    /**
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static now(): Promise<LocalDateTime | null>;
    // ================== Method now ==================
    /**
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static nowSync(): LocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static now(var0: java_time_ZoneId | null): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static nowSync(var0: java_time_ZoneId | null): LocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.Clock'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static now(var0: java_time_Clock | null): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.Clock'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static nowSync(var0: java_time_Clock | null): LocalDateTime | null;
    // ================== Method with ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public with(var0: java_time_temporal_TemporalAdjuster | null): Promise<java_time_chrono_ChronoLocalDateTime | null>;
    // ================== Method with ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public withSync(var0: java_time_temporal_TemporalAdjuster | null): java_time_chrono_ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public with(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): Promise<java_time_chrono_ChronoLocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public withSync(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): java_time_chrono_ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public with(var0: java_time_temporal_TemporalAdjuster | null): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withSync(var0: java_time_temporal_TemporalAdjuster | null): LocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public with(var0: java_time_temporal_TemporalAdjuster | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public withSync(var0: java_time_temporal_TemporalAdjuster | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public with(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public withSync(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public with(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withSync(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method truncatedTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public truncatedTo(var0: java_time_temporal_TemporalUnit | null): Promise<LocalDateTime | null>;
    // ================== Method truncatedTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public truncatedToSync(var0: java_time_temporal_TemporalUnit | null): LocalDateTime | null;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<LocalDateTime | null>;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): LocalDateTime | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public plus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<java_time_chrono_ChronoLocalDateTime | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public plusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): java_time_chrono_ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_chrono_ChronoLocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): java_time_chrono_ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): LocalDateTime | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): java_time_temporal_Temporal | null;
    // ================== Method plusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusSeconds(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method plusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusSecondsSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method plusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusNanos(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method plusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusNanosSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public minus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<java_time_chrono_ChronoLocalDateTime | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public minusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): java_time_chrono_ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_chrono_ChronoLocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoLocalDateTime'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): java_time_chrono_ChronoLocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): LocalDateTime | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): LocalDateTime | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): java_time_temporal_Temporal | null;
    // ================== Method minusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusSeconds(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method minusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusSecondsSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method minusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusNanos(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method minusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusNanosSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method adjustInto ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public adjustInto(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method adjustInto ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public adjustIntoSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method until ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public until(var0: java_time_temporal_Temporal | null, var1: java_time_temporal_TemporalUnit | null): Promise<number>;
    // ================== Method until ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public untilSync(var0: java_time_temporal_Temporal | null, var1: java_time_temporal_TemporalUnit | null): number;
    // ================== Method atOffset ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetDateTime'
     */
    public atOffset(var0: java_time_ZoneOffset | null): Promise<java_time_OffsetDateTime | null>;
    // ================== Method atOffset ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetDateTime'
     */
    public atOffsetSync(var0: java_time_ZoneOffset | null): java_time_OffsetDateTime | null;
    // ================== Method atZone ==================
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.chrono.ChronoZonedDateTime'
     */
    public atZone(var0: java_time_ZoneId | null): Promise<java_time_chrono_ChronoZonedDateTime | null>;
    // ================== Method atZone ==================
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.chrono.ChronoZonedDateTime'
     */
    public atZoneSync(var0: java_time_ZoneId | null): java_time_chrono_ChronoZonedDateTime | null;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.ZonedDateTime'
     */
    public atZone(var0: java_time_ZoneId | null): Promise<java_time_ZonedDateTime | null>;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.ZonedDateTime'
     */
    public atZoneSync(var0: java_time_ZoneId | null): java_time_ZonedDateTime | null;
    // ================== Method isAfter ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isAfter(var0: java_time_chrono_ChronoLocalDateTime | null): Promise<boolean>;
    // ================== Method isAfter ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isAfterSync(var0: java_time_chrono_ChronoLocalDateTime | null): boolean;
    // ================== Method isBefore ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isBefore(var0: java_time_chrono_ChronoLocalDateTime | null): Promise<boolean>;
    // ================== Method isBefore ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isBeforeSync(var0: java_time_chrono_ChronoLocalDateTime | null): boolean;
    // ================== Method ofInstant ==================
    /**
     * @param var0 original type: 'java.time.Instant'
     * @param var1 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofInstant(var0: java_time_Instant | null, var1: java_time_ZoneId | null): Promise<LocalDateTime | null>;
    // ================== Method ofInstant ==================
    /**
     * @param var0 original type: 'java.time.Instant'
     * @param var1 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofInstantSync(var0: java_time_Instant | null, var1: java_time_ZoneId | null): LocalDateTime | null;
    // ================== Method toLocalDate ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public toLocalDate(): Promise<java_time_chrono_ChronoLocalDate | null>;
    // ================== Method toLocalDate ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoLocalDate'
     */
    public toLocalDateSync(): java_time_chrono_ChronoLocalDate | null;
    /**
     * @return original return type: 'java.time.LocalDate'
     */
    public toLocalDate(): Promise<java_time_LocalDate | null>;
    /**
     * @return original return type: 'java.time.LocalDate'
     */
    public toLocalDateSync(): java_time_LocalDate | null;
    // ================== Method getMonth ==================
    /**
     * @return original return type: 'java.time.Month'
     */
    public getMonth(): Promise<java_time_Month | null>;
    // ================== Method getMonth ==================
    /**
     * @return original return type: 'java.time.Month'
     */
    public getMonthSync(): java_time_Month | null;
    // ================== Method getDayOfYear ==================
    /**
     * @return original return type: 'int'
     */
    public getDayOfYear(): Promise<number>;
    // ================== Method getDayOfYear ==================
    /**
     * @return original return type: 'int'
     */
    public getDayOfYearSync(): number;
    // ================== Method getDayOfWeek ==================
    /**
     * @return original return type: 'java.time.DayOfWeek'
     */
    public getDayOfWeek(): Promise<java_time_DayOfWeek | null>;
    // ================== Method getDayOfWeek ==================
    /**
     * @return original return type: 'java.time.DayOfWeek'
     */
    public getDayOfWeekSync(): java_time_DayOfWeek | null;
    // ================== Method toLocalTime ==================
    /**
     * @return original return type: 'java.time.LocalTime'
     */
    public toLocalTime(): Promise<java_time_LocalTime | null>;
    // ================== Method toLocalTime ==================
    /**
     * @return original return type: 'java.time.LocalTime'
     */
    public toLocalTimeSync(): java_time_LocalTime | null;
    // ================== Method withYear ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withYear(var0: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method withYear ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withYearSync(var0: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method withMonth ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withMonth(var0: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method withMonth ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withMonthSync(var0: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method withDayOfMonth ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withDayOfMonth(var0: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method withDayOfMonth ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withDayOfMonthSync(var0: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method withDayOfYear ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withDayOfYear(var0: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method withDayOfYear ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withDayOfYearSync(var0: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method withHour ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withHour(var0: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method withHour ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withHourSync(var0: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method withMinute ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withMinute(var0: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method withMinute ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withMinuteSync(var0: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method withSecond ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withSecond(var0: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method withSecond ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withSecondSync(var0: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method withNano ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withNano(var0: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method withNano ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public withNanoSync(var0: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method plusYears ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusYears(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method plusYears ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusYearsSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method plusMonths ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusMonths(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method plusMonths ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusMonthsSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method plusWeeks ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusWeeks(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method plusWeeks ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusWeeksSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method plusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusDays(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method plusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusDaysSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method plusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusHours(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method plusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusHoursSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method plusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusMinutes(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method plusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public plusMinutesSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method minusYears ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusYears(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method minusYears ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusYearsSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method minusMonths ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusMonths(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method minusMonths ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusMonthsSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method minusWeeks ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusWeeks(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method minusWeeks ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusWeeksSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method minusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusDays(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method minusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusDaysSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method minusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusHours(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method minusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusHoursSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method minusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusMinutes(var0: java_lang_Long | bigint | number): Promise<LocalDateTime | null>;
    // ================== Method minusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public minusMinutesSync(var0: java_lang_Long | bigint | number): LocalDateTime | null;
    // ================== Method isEqual ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isEqual(var0: java_time_chrono_ChronoLocalDateTime | null): Promise<boolean>;
    // ================== Method isEqual ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'boolean'
     */
    public isEqualSync(var0: java_time_chrono_ChronoLocalDateTime | null): boolean;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static from(var0: java_time_temporal_TemporalAccessor | null): Promise<LocalDateTime | null>;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static fromSync(var0: java_time_temporal_TemporalAccessor | null): LocalDateTime | null;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'int'
     */
    public get(var0: java_time_temporal_TemporalField | null): Promise<number>;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'int'
     */
    public getSync(var0: java_time_temporal_TemporalField | null): number;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'int'
     */
    public compareTo(var0: java_time_chrono_ChronoLocalDateTime | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.time.chrono.ChronoLocalDateTime'
     * @return original return type: 'int'
     */
    public compareToSync(var0: java_time_chrono_ChronoLocalDateTime | null): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    // ================== Method getLong ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'long'
     */
    public getLong(var0: java_time_temporal_TemporalField | null): Promise<number>;
    // ================== Method getLong ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'long'
     */
    public getLongSync(var0: java_time_temporal_TemporalField | null): number;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.lang.String'
     */
    public format(var0: java_time_format_DateTimeFormatter | null): Promise<string | null>;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.lang.String'
     */
    public formatSync(var0: java_time_format_DateTimeFormatter | null): string | null;
    // ================== Method query ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalQuery'
     * @return original return type: 'java.lang.Object'
     */
    public query(var0: java_time_temporal_TemporalQuery | null): Promise<BasicOrJavaType | null>;
    // ================== Method query ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalQuery'
     * @return original return type: 'java.lang.Object'
     */
    public querySync(var0: java_time_temporal_TemporalQuery | null): BasicOrJavaType | null;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'java.time.Month'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static of(var0: java_lang_Integer | number, var1: java_time_Month | null, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number): Promise<LocalDateTime | null>;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'java.time.Month'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofSync(var0: java_lang_Integer | number, var1: java_time_Month | null, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number): LocalDateTime | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static of(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number): LocalDateTime | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static of(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number): LocalDateTime | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'java.time.Month'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static of(var0: java_lang_Integer | number, var1: java_time_Month | null, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'java.time.Month'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofSync(var0: java_lang_Integer | number, var1: java_time_Month | null, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number): LocalDateTime | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'java.time.Month'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @param var6 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static of(var0: java_lang_Integer | number, var1: java_time_Month | null, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number, var6: java_lang_Integer | number): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'java.time.Month'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @param var6 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofSync(var0: java_lang_Integer | number, var1: java_time_Month | null, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number, var6: java_lang_Integer | number): LocalDateTime | null;
    /**
     * @param var0 original type: 'java.time.LocalDate'
     * @param var1 original type: 'java.time.LocalTime'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static of(var0: java_time_LocalDate | null, var1: java_time_LocalTime | null): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'java.time.LocalDate'
     * @param var1 original type: 'java.time.LocalTime'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofSync(var0: java_time_LocalDate | null, var1: java_time_LocalTime | null): LocalDateTime | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @param var6 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static of(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number, var6: java_lang_Integer | number): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @param var6 original type: 'int'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static ofSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_lang_Integer | number, var5: java_lang_Integer | number, var6: java_lang_Integer | number): LocalDateTime | null;
    // ================== Method isSupported ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'boolean'
     */
    public isSupported(var0: java_time_temporal_TemporalField | null): Promise<boolean>;
    // ================== Method isSupported ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'boolean'
     */
    public isSupportedSync(var0: java_time_temporal_TemporalField | null): boolean;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'boolean'
     */
    public isSupported(var0: java_time_temporal_TemporalUnit | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'boolean'
     */
    public isSupportedSync(var0: java_time_temporal_TemporalUnit | null): boolean;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static parse(var0: java_lang_CharSequence | null, var1: java_time_format_DateTimeFormatter | null): Promise<LocalDateTime | null>;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static parseSync(var0: java_lang_CharSequence | null, var1: java_time_format_DateTimeFormatter | null): LocalDateTime | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static parse(var0: java_lang_CharSequence | null): Promise<LocalDateTime | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.time.LocalDateTime'
     */
    public static parseSync(var0: java_lang_CharSequence | null): LocalDateTime | null;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'java.time.temporal.ValueRange'
     */
    public range(var0: java_time_temporal_TemporalField | null): Promise<java_time_temporal_ValueRange | null>;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'java.time.temporal.ValueRange'
     */
    public rangeSync(var0: java_time_temporal_TemporalField | null): java_time_temporal_ValueRange | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
    // ================== Method getChronology ==================
    /**
     * @return original return type: 'java.time.chrono.Chronology'
     */
    public getChronology(): Promise<java_time_chrono_Chronology | null>;
    // ================== Method getChronology ==================
    /**
     * @return original return type: 'java.time.chrono.Chronology'
     */
    public getChronologySync(): java_time_chrono_Chronology | null;
    // ================== Method toInstant ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.Instant'
     */
    public toInstant(var0: java_time_ZoneOffset | null): Promise<java_time_Instant | null>;
    // ================== Method toInstant ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.Instant'
     */
    public toInstantSync(var0: java_time_ZoneOffset | null): java_time_Instant | null;
    // ================== Method toEpochSecond ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'long'
     */
    public toEpochSecond(var0: java_time_ZoneOffset | null): Promise<number>;
    // ================== Method toEpochSecond ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'long'
     */
    public toEpochSecondSync(var0: java_time_ZoneOffset | null): number;
}

/**
 * Class java.time.LocalDateTime.
 *
 * This actually imports the java class for further use.
 * The class LocalDateTimeClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class LocalDateTime extends importClass<typeof LocalDateTimeClass>("java.time.LocalDateTime") {
}
export default LocalDateTime;