import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { ZoneId as java_time_ZoneId } from "./ZoneId";
import { Clock as java_time_Clock } from "./Clock";
import { TemporalAdjuster as java_time_temporal_TemporalAdjuster } from "./temporal/TemporalAdjuster";
import { TemporalField as java_time_temporal_TemporalField } from "./temporal/TemporalField";
import { Long as java_lang_Long } from "./../lang/Long";
import { Temporal as java_time_temporal_Temporal } from "./temporal/Temporal";
import { TemporalUnit as java_time_temporal_TemporalUnit } from "./temporal/TemporalUnit";
import { TemporalAmount as java_time_temporal_TemporalAmount } from "./temporal/TemporalAmount";
import { Instant as java_time_Instant } from "./Instant";
import { ZoneOffset as java_time_ZoneOffset } from "./ZoneOffset";
import { LocalTime as java_time_LocalTime } from "./LocalTime";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { OffsetDateTime as java_time_OffsetDateTime } from "./OffsetDateTime";
import { LocalDate as java_time_LocalDate } from "./LocalDate";
import { TemporalAccessor as java_time_temporal_TemporalAccessor } from "./temporal/TemporalAccessor";
import { DateTimeFormatter as java_time_format_DateTimeFormatter } from "./format/DateTimeFormatter";
import { TemporalQuery as java_time_temporal_TemporalQuery } from "./temporal/TemporalQuery";
import { CharSequence as java_lang_CharSequence } from "./../lang/CharSequence";
import { ValueRange as java_time_temporal_ValueRange } from "./temporal/ValueRange";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import OffsetTime instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class OffsetTimeClass extends JavaClass {
    // ================== Field MIN ==================
    /**
     * Original type: 'java.time.OffsetTime'
     */
    public static readonly MIN: OffsetTimeClass | null;
    // ================== Field MAX ==================
    /**
     * Original type: 'java.time.OffsetTime'
     */
    public static readonly MAX: OffsetTimeClass | null;
    // ================== Method getNano ==================
    /**
     * @return original return type: 'int'
     */
    public getNano(): Promise<number>;
    // ================== Method getNano ==================
    /**
     * @return original return type: 'int'
     */
    public getNanoSync(): number;
    // ================== Method getHour ==================
    /**
     * @return original return type: 'int'
     */
    public getHour(): Promise<number>;
    // ================== Method getHour ==================
    /**
     * @return original return type: 'int'
     */
    public getHourSync(): number;
    // ================== Method getMinute ==================
    /**
     * @return original return type: 'int'
     */
    public getMinute(): Promise<number>;
    // ================== Method getMinute ==================
    /**
     * @return original return type: 'int'
     */
    public getMinuteSync(): number;
    // ================== Method getSecond ==================
    /**
     * @return original return type: 'int'
     */
    public getSecond(): Promise<number>;
    // ================== Method getSecond ==================
    /**
     * @return original return type: 'int'
     */
    public getSecondSync(): number;
    // ================== Method now ==================
    /**
     * @return original return type: 'java.time.OffsetTime'
     */
    public static now(): Promise<OffsetTime | null>;
    // ================== Method now ==================
    /**
     * @return original return type: 'java.time.OffsetTime'
     */
    public static nowSync(): OffsetTime | null;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static now(var0: java_time_ZoneId | null): Promise<OffsetTime | null>;
    /**
     * @param var0 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static nowSync(var0: java_time_ZoneId | null): OffsetTime | null;
    /**
     * @param var0 original type: 'java.time.Clock'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static now(var0: java_time_Clock | null): Promise<OffsetTime | null>;
    /**
     * @param var0 original type: 'java.time.Clock'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static nowSync(var0: java_time_Clock | null): OffsetTime | null;
    // ================== Method with ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.OffsetTime'
     */
    public with(var0: java_time_temporal_TemporalAdjuster | null): Promise<OffsetTime | null>;
    // ================== Method with ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withSync(var0: java_time_temporal_TemporalAdjuster | null): OffsetTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public with(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withSync(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): OffsetTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public with(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @param var1 original type: 'long'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public withSync(var0: java_time_temporal_TemporalField | null, var1: java_lang_Long | bigint | number): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public with(var0: java_time_temporal_TemporalAdjuster | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAdjuster'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public withSync(var0: java_time_temporal_TemporalAdjuster | null): java_time_temporal_Temporal | null;
    // ================== Method truncatedTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.OffsetTime'
     */
    public truncatedTo(var0: java_time_temporal_TemporalUnit | null): Promise<OffsetTime | null>;
    // ================== Method truncatedTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.OffsetTime'
     */
    public truncatedToSync(var0: java_time_temporal_TemporalUnit | null): OffsetTime | null;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<OffsetTime | null>;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): OffsetTime | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<OffsetTime | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): OffsetTime | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public plusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): java_time_temporal_Temporal | null;
    // ================== Method plusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusSeconds(var0: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    // ================== Method plusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusSecondsSync(var0: java_lang_Long | bigint | number): OffsetTime | null;
    // ================== Method plusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusNanos(var0: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    // ================== Method plusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusNanosSync(var0: java_lang_Long | bigint | number): OffsetTime | null;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_temporal_Temporal | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): java_time_temporal_Temporal | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<OffsetTime | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): OffsetTime | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minus(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): Promise<OffsetTime | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusSync(var0: java_lang_Long | bigint | number, var1: java_time_temporal_TemporalUnit | null): OffsetTime | null;
    // ================== Method minusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusSeconds(var0: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    // ================== Method minusSeconds ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusSecondsSync(var0: java_lang_Long | bigint | number): OffsetTime | null;
    // ================== Method minusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusNanos(var0: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    // ================== Method minusNanos ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusNanosSync(var0: java_lang_Long | bigint | number): OffsetTime | null;
    // ================== Method adjustInto ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public adjustInto(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method adjustInto ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public adjustIntoSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method until ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public until(var0: java_time_temporal_Temporal | null, var1: java_time_temporal_TemporalUnit | null): Promise<number>;
    // ================== Method until ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @param var1 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public untilSync(var0: java_time_temporal_Temporal | null, var1: java_time_temporal_TemporalUnit | null): number;
    // ================== Method isAfter ==================
    /**
     * @param var0 original type: 'java.time.OffsetTime'
     * @return original return type: 'boolean'
     */
    public isAfter(var0: OffsetTimeClass | null): Promise<boolean>;
    // ================== Method isAfter ==================
    /**
     * @param var0 original type: 'java.time.OffsetTime'
     * @return original return type: 'boolean'
     */
    public isAfterSync(var0: OffsetTimeClass | null): boolean;
    // ================== Method isBefore ==================
    /**
     * @param var0 original type: 'java.time.OffsetTime'
     * @return original return type: 'boolean'
     */
    public isBefore(var0: OffsetTimeClass | null): Promise<boolean>;
    // ================== Method isBefore ==================
    /**
     * @param var0 original type: 'java.time.OffsetTime'
     * @return original return type: 'boolean'
     */
    public isBeforeSync(var0: OffsetTimeClass | null): boolean;
    // ================== Method ofInstant ==================
    /**
     * @param var0 original type: 'java.time.Instant'
     * @param var1 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static ofInstant(var0: java_time_Instant | null, var1: java_time_ZoneId | null): Promise<OffsetTime | null>;
    // ================== Method ofInstant ==================
    /**
     * @param var0 original type: 'java.time.Instant'
     * @param var1 original type: 'java.time.ZoneId'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static ofInstantSync(var0: java_time_Instant | null, var1: java_time_ZoneId | null): OffsetTime | null;
    // ================== Method withOffsetSameLocal ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withOffsetSameLocal(var0: java_time_ZoneOffset | null): Promise<OffsetTime | null>;
    // ================== Method withOffsetSameLocal ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withOffsetSameLocalSync(var0: java_time_ZoneOffset | null): OffsetTime | null;
    // ================== Method withOffsetSameInstant ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withOffsetSameInstant(var0: java_time_ZoneOffset | null): Promise<OffsetTime | null>;
    // ================== Method withOffsetSameInstant ==================
    /**
     * @param var0 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withOffsetSameInstantSync(var0: java_time_ZoneOffset | null): OffsetTime | null;
    // ================== Method toLocalTime ==================
    /**
     * @return original return type: 'java.time.LocalTime'
     */
    public toLocalTime(): Promise<java_time_LocalTime | null>;
    // ================== Method toLocalTime ==================
    /**
     * @return original return type: 'java.time.LocalTime'
     */
    public toLocalTimeSync(): java_time_LocalTime | null;
    // ================== Method withHour ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withHour(var0: java_lang_Integer | number): Promise<OffsetTime | null>;
    // ================== Method withHour ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withHourSync(var0: java_lang_Integer | number): OffsetTime | null;
    // ================== Method withMinute ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withMinute(var0: java_lang_Integer | number): Promise<OffsetTime | null>;
    // ================== Method withMinute ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withMinuteSync(var0: java_lang_Integer | number): OffsetTime | null;
    // ================== Method withSecond ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withSecond(var0: java_lang_Integer | number): Promise<OffsetTime | null>;
    // ================== Method withSecond ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withSecondSync(var0: java_lang_Integer | number): OffsetTime | null;
    // ================== Method withNano ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withNano(var0: java_lang_Integer | number): Promise<OffsetTime | null>;
    // ================== Method withNano ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.OffsetTime'
     */
    public withNanoSync(var0: java_lang_Integer | number): OffsetTime | null;
    // ================== Method plusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusHours(var0: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    // ================== Method plusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusHoursSync(var0: java_lang_Long | bigint | number): OffsetTime | null;
    // ================== Method plusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusMinutes(var0: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    // ================== Method plusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public plusMinutesSync(var0: java_lang_Long | bigint | number): OffsetTime | null;
    // ================== Method minusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusHours(var0: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    // ================== Method minusHours ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusHoursSync(var0: java_lang_Long | bigint | number): OffsetTime | null;
    // ================== Method minusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusMinutes(var0: java_lang_Long | bigint | number): Promise<OffsetTime | null>;
    // ================== Method minusMinutes ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.OffsetTime'
     */
    public minusMinutesSync(var0: java_lang_Long | bigint | number): OffsetTime | null;
    // ================== Method atDate ==================
    /**
     * @param var0 original type: 'java.time.LocalDate'
     * @return original return type: 'java.time.OffsetDateTime'
     */
    public atDate(var0: java_time_LocalDate | null): Promise<java_time_OffsetDateTime | null>;
    // ================== Method atDate ==================
    /**
     * @param var0 original type: 'java.time.LocalDate'
     * @return original return type: 'java.time.OffsetDateTime'
     */
    public atDateSync(var0: java_time_LocalDate | null): java_time_OffsetDateTime | null;
    // ================== Method isEqual ==================
    /**
     * @param var0 original type: 'java.time.OffsetTime'
     * @return original return type: 'boolean'
     */
    public isEqual(var0: OffsetTimeClass | null): Promise<boolean>;
    // ================== Method isEqual ==================
    /**
     * @param var0 original type: 'java.time.OffsetTime'
     * @return original return type: 'boolean'
     */
    public isEqualSync(var0: OffsetTimeClass | null): boolean;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static from(var0: java_time_temporal_TemporalAccessor | null): Promise<OffsetTime | null>;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAccessor'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static fromSync(var0: java_time_temporal_TemporalAccessor | null): OffsetTime | null;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'int'
     */
    public get(var0: java_time_temporal_TemporalField | null): Promise<number>;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'int'
     */
    public getSync(var0: java_time_temporal_TemporalField | null): number;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareTo(var0: BasicOrJavaType | null): Promise<number>;
    // ================== Method compareTo ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    public compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.time.OffsetTime'
     * @return original return type: 'int'
     */
    public compareTo(var0: OffsetTimeClass | null): Promise<number>;
    /**
     * @param var0 original type: 'java.time.OffsetTime'
     * @return original return type: 'int'
     */
    public compareToSync(var0: OffsetTimeClass | null): number;
    // ================== Method getLong ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'long'
     */
    public getLong(var0: java_time_temporal_TemporalField | null): Promise<number>;
    // ================== Method getLong ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'long'
     */
    public getLongSync(var0: java_time_temporal_TemporalField | null): number;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.lang.String'
     */
    public format(var0: java_time_format_DateTimeFormatter | null): Promise<string | null>;
    // ================== Method format ==================
    /**
     * @param var0 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.lang.String'
     */
    public formatSync(var0: java_time_format_DateTimeFormatter | null): string | null;
    // ================== Method query ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalQuery'
     * @return original return type: 'java.lang.Object'
     */
    public query(var0: java_time_temporal_TemporalQuery | null): Promise<BasicOrJavaType | null>;
    // ================== Method query ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalQuery'
     * @return original return type: 'java.lang.Object'
     */
    public querySync(var0: java_time_temporal_TemporalQuery | null): BasicOrJavaType | null;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'java.time.LocalTime'
     * @param var1 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static of(var0: java_time_LocalTime | null, var1: java_time_ZoneOffset | null): Promise<OffsetTime | null>;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'java.time.LocalTime'
     * @param var1 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static ofSync(var0: java_time_LocalTime | null, var1: java_time_ZoneOffset | null): OffsetTime | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static of(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_time_ZoneOffset | null): Promise<OffsetTime | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @param var3 original type: 'int'
     * @param var4 original type: 'java.time.ZoneOffset'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static ofSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number, var3: java_lang_Integer | number, var4: java_time_ZoneOffset | null): OffsetTime | null;
    // ================== Method getOffset ==================
    /**
     * @return original return type: 'java.time.ZoneOffset'
     */
    public getOffset(): Promise<java_time_ZoneOffset | null>;
    // ================== Method getOffset ==================
    /**
     * @return original return type: 'java.time.ZoneOffset'
     */
    public getOffsetSync(): java_time_ZoneOffset | null;
    // ================== Method isSupported ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'boolean'
     */
    public isSupported(var0: java_time_temporal_TemporalField | null): Promise<boolean>;
    // ================== Method isSupported ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'boolean'
     */
    public isSupportedSync(var0: java_time_temporal_TemporalField | null): boolean;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'boolean'
     */
    public isSupported(var0: java_time_temporal_TemporalUnit | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'boolean'
     */
    public isSupportedSync(var0: java_time_temporal_TemporalUnit | null): boolean;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static parse(var0: java_lang_CharSequence | null, var1: java_time_format_DateTimeFormatter | null): Promise<OffsetTime | null>;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @param var1 original type: 'java.time.format.DateTimeFormatter'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static parseSync(var0: java_lang_CharSequence | null, var1: java_time_format_DateTimeFormatter | null): OffsetTime | null;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static parse(var0: java_lang_CharSequence | null): Promise<OffsetTime | null>;
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.time.OffsetTime'
     */
    public static parseSync(var0: java_lang_CharSequence | null): OffsetTime | null;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'java.time.temporal.ValueRange'
     */
    public range(var0: java_time_temporal_TemporalField | null): Promise<java_time_temporal_ValueRange | null>;
    // ================== Method range ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalField'
     * @return original return type: 'java.time.temporal.ValueRange'
     */
    public rangeSync(var0: java_time_temporal_TemporalField | null): java_time_temporal_ValueRange | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.time.OffsetTime.
 *
 * This actually imports the java class for further use.
 * The class OffsetTimeClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class OffsetTime extends importClass<typeof OffsetTimeClass>("java.time.OffsetTime") {
}
export default OffsetTime;