import { importClass, JavaClass, BasicOrJavaType } from "java-bridge";
import { IsoChronology as java_time_chrono_IsoChronology } from "./chrono/IsoChronology";
import { Chronology as java_time_chrono_Chronology } from "./chrono/Chronology";
import { Integer as java_lang_Integer } from "./../lang/Integer";
import { ChronoPeriod as java_time_chrono_ChronoPeriod } from "./chrono/ChronoPeriod";
import { TemporalAmount as java_time_temporal_TemporalAmount } from "./temporal/TemporalAmount";
import { Temporal as java_time_temporal_Temporal } from "./temporal/Temporal";
import { LocalDate as java_time_LocalDate } from "./LocalDate";
import { List as java_util_List } from "./../util/List";
import { Long as java_lang_Long } from "./../lang/Long";
import { TemporalUnit as java_time_temporal_TemporalUnit } from "./temporal/TemporalUnit";
import { CharSequence as java_lang_CharSequence } from "./../lang/CharSequence";
import { Class as java_lang_Class } from "./../lang/Class";

/**
 * This class just defines types, you should import Period instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PeriodClass extends JavaClass {
    // ================== Field ZERO ==================
    /**
     * Original type: 'java.time.Period'
     */
    public static readonly ZERO: PeriodClass | null;
    // ================== Method getChronology ==================
    /**
     * @return original return type: 'java.time.chrono.IsoChronology'
     */
    public getChronology(): Promise<java_time_chrono_IsoChronology | null>;
    // ================== Method getChronology ==================
    /**
     * @return original return type: 'java.time.chrono.IsoChronology'
     */
    public getChronologySync(): java_time_chrono_IsoChronology | null;
    /**
     * @return original return type: 'java.time.chrono.Chronology'
     */
    public getChronology(): Promise<java_time_chrono_Chronology | null>;
    /**
     * @return original return type: 'java.time.chrono.Chronology'
     */
    public getChronologySync(): java_time_chrono_Chronology | null;
    // ================== Method ofDays ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofDays(var0: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method ofDays ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofDaysSync(var0: java_lang_Integer | number): Period | null;
    // ================== Method isZero ==================
    /**
     * @return original return type: 'boolean'
     */
    public isZero(): Promise<boolean>;
    // ================== Method isZero ==================
    /**
     * @return original return type: 'boolean'
     */
    public isZeroSync(): boolean;
    // ================== Method multipliedBy ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public multipliedBy(var0: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method multipliedBy ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public multipliedBySync(var0: java_lang_Integer | number): Period | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public multipliedBy(var0: java_lang_Integer | number): Promise<java_time_chrono_ChronoPeriod | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public multipliedBySync(var0: java_lang_Integer | number): java_time_chrono_ChronoPeriod | null;
    // ================== Method negated ==================
    /**
     * @return original return type: 'java.time.Period'
     */
    public negated(): Promise<Period | null>;
    // ================== Method negated ==================
    /**
     * @return original return type: 'java.time.Period'
     */
    public negatedSync(): Period | null;
    /**
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public negated(): Promise<java_time_chrono_ChronoPeriod | null>;
    /**
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public negatedSync(): java_time_chrono_ChronoPeriod | null;
    // ================== Method toTotalMonths ==================
    /**
     * @return original return type: 'long'
     */
    public toTotalMonths(): Promise<number>;
    // ================== Method toTotalMonths ==================
    /**
     * @return original return type: 'long'
     */
    public toTotalMonthsSync(): number;
    // ================== Method getDays ==================
    /**
     * @return original return type: 'int'
     */
    public getDays(): Promise<number>;
    // ================== Method getDays ==================
    /**
     * @return original return type: 'int'
     */
    public getDaysSync(): number;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_chrono_ChronoPeriod | null>;
    // ================== Method plus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): java_time_chrono_ChronoPeriod | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.Period'
     */
    public plus(var0: java_time_temporal_TemporalAmount | null): Promise<Period | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.Period'
     */
    public plusSync(var0: java_time_temporal_TemporalAmount | null): Period | null;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.Period'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<Period | null>;
    // ================== Method minus ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.Period'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): Period | null;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public minus(var0: java_time_temporal_TemporalAmount | null): Promise<java_time_chrono_ChronoPeriod | null>;
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public minusSync(var0: java_time_temporal_TemporalAmount | null): java_time_chrono_ChronoPeriod | null;
    // ================== Method addTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public addTo(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method addTo ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public addToSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method subtractFrom ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public subtractFrom(var0: java_time_temporal_Temporal | null): Promise<java_time_temporal_Temporal | null>;
    // ================== Method subtractFrom ==================
    /**
     * @param var0 original type: 'java.time.temporal.Temporal'
     * @return original return type: 'java.time.temporal.Temporal'
     */
    public subtractFromSync(var0: java_time_temporal_Temporal | null): java_time_temporal_Temporal | null;
    // ================== Method between ==================
    /**
     * @param var0 original type: 'java.time.LocalDate'
     * @param var1 original type: 'java.time.LocalDate'
     * @return original return type: 'java.time.Period'
     */
    public static between(var0: java_time_LocalDate | null, var1: java_time_LocalDate | null): Promise<Period | null>;
    // ================== Method between ==================
    /**
     * @param var0 original type: 'java.time.LocalDate'
     * @param var1 original type: 'java.time.LocalDate'
     * @return original return type: 'java.time.Period'
     */
    public static betweenSync(var0: java_time_LocalDate | null, var1: java_time_LocalDate | null): Period | null;
    // ================== Method isNegative ==================
    /**
     * @return original return type: 'boolean'
     */
    public isNegative(): Promise<boolean>;
    // ================== Method isNegative ==================
    /**
     * @return original return type: 'boolean'
     */
    public isNegativeSync(): boolean;
    // ================== Method getUnits ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getUnits(): Promise<java_util_List | null>;
    // ================== Method getUnits ==================
    /**
     * @return original return type: 'java.util.List'
     */
    public getUnitsSync(): java_util_List | null;
    // ================== Method plusYears ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public plusYears(var0: java_lang_Long | bigint | number): Promise<Period | null>;
    // ================== Method plusYears ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public plusYearsSync(var0: java_lang_Long | bigint | number): Period | null;
    // ================== Method plusMonths ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public plusMonths(var0: java_lang_Long | bigint | number): Promise<Period | null>;
    // ================== Method plusMonths ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public plusMonthsSync(var0: java_lang_Long | bigint | number): Period | null;
    // ================== Method plusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public plusDays(var0: java_lang_Long | bigint | number): Promise<Period | null>;
    // ================== Method plusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public plusDaysSync(var0: java_lang_Long | bigint | number): Period | null;
    // ================== Method minusYears ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public minusYears(var0: java_lang_Long | bigint | number): Promise<Period | null>;
    // ================== Method minusYears ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public minusYearsSync(var0: java_lang_Long | bigint | number): Period | null;
    // ================== Method minusMonths ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public minusMonths(var0: java_lang_Long | bigint | number): Promise<Period | null>;
    // ================== Method minusMonths ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public minusMonthsSync(var0: java_lang_Long | bigint | number): Period | null;
    // ================== Method minusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public minusDays(var0: java_lang_Long | bigint | number): Promise<Period | null>;
    // ================== Method minusDays ==================
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.time.Period'
     */
    public minusDaysSync(var0: java_lang_Long | bigint | number): Period | null;
    // ================== Method ofYears ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofYears(var0: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method ofYears ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofYearsSync(var0: java_lang_Integer | number): Period | null;
    // ================== Method ofMonths ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofMonths(var0: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method ofMonths ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofMonthsSync(var0: java_lang_Integer | number): Period | null;
    // ================== Method ofWeeks ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofWeeks(var0: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method ofWeeks ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofWeeksSync(var0: java_lang_Integer | number): Period | null;
    // ================== Method getYears ==================
    /**
     * @return original return type: 'int'
     */
    public getYears(): Promise<number>;
    // ================== Method getYears ==================
    /**
     * @return original return type: 'int'
     */
    public getYearsSync(): number;
    // ================== Method getMonths ==================
    /**
     * @return original return type: 'int'
     */
    public getMonths(): Promise<number>;
    // ================== Method getMonths ==================
    /**
     * @return original return type: 'int'
     */
    public getMonthsSync(): number;
    // ================== Method withYears ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public withYears(var0: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method withYears ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public withYearsSync(var0: java_lang_Integer | number): Period | null;
    // ================== Method withMonths ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public withMonths(var0: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method withMonths ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public withMonthsSync(var0: java_lang_Integer | number): Period | null;
    // ================== Method withDays ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public withDays(var0: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method withDays ==================
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public withDaysSync(var0: java_lang_Integer | number): Period | null;
    // ================== Method normalized ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public normalized(): Promise<java_time_chrono_ChronoPeriod | null>;
    // ================== Method normalized ==================
    /**
     * @return original return type: 'java.time.chrono.ChronoPeriod'
     */
    public normalizedSync(): java_time_chrono_ChronoPeriod | null;
    /**
     * @return original return type: 'java.time.Period'
     */
    public normalized(): Promise<Period | null>;
    /**
     * @return original return type: 'java.time.Period'
     */
    public normalizedSync(): Period | null;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.Period'
     */
    public static from(var0: java_time_temporal_TemporalAmount | null): Promise<Period | null>;
    // ================== Method from ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalAmount'
     * @return original return type: 'java.time.Period'
     */
    public static fromSync(var0: java_time_temporal_TemporalAmount | null): Period | null;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public get(var0: java_time_temporal_TemporalUnit | null): Promise<number>;
    // ================== Method get ==================
    /**
     * @param var0 original type: 'java.time.temporal.TemporalUnit'
     * @return original return type: 'long'
     */
    public getSync(var0: java_time_temporal_TemporalUnit | null): number;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equals(var0: BasicOrJavaType | null): Promise<boolean>;
    // ================== Method equals ==================
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    public equalsSync(var0: BasicOrJavaType | null): boolean;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toString(): Promise<string>;
    // ================== Method toString ==================
    /**
     * @return original return type: 'java.lang.String'
     */
    public toStringSync(): string;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCode(): Promise<number>;
    // ================== Method hashCode ==================
    /**
     * @return original return type: 'int'
     */
    public hashCodeSync(): number;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static of(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<Period | null>;
    // ================== Method of ==================
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.time.Period'
     */
    public static ofSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Period | null;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.time.Period'
     */
    public static parse(var0: java_lang_CharSequence | null): Promise<Period | null>;
    // ================== Method parse ==================
    /**
     * @param var0 original type: 'java.lang.CharSequence'
     * @return original return type: 'java.time.Period'
     */
    public static parseSync(var0: java_lang_CharSequence | null): Period | null;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    // ================== Method wait ==================
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    public waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'void'
     */
    public wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    public waitSync(): void;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClass(): Promise<java_lang_Class>;
    // ================== Method getClass ==================
    /**
     * @return original return type: 'java.lang.Class'
     */
    public getClassSync(): java_lang_Class;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notify(): Promise<void>;
    // ================== Method notify ==================
    /**
     * @return original return type: 'void'
     */
    public notifySync(): void;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAll(): Promise<void>;
    // ================== Method notifyAll ==================
    /**
     * @return original return type: 'void'
     */
    public notifyAllSync(): void;
}

/**
 * Class java.time.Period.
 *
 * This actually imports the java class for further use.
 * The class PeriodClass only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export class Period extends importClass<typeof PeriodClass>("java.time.Period") {
}
export default Period;